#!/usr/bin/env python3
"""Builds the golden seed corpus (Agent Interface Plan, Milestone L): a
fixed set of seeded games, each with its replay record, outcome, and final
`state_hash`. A pure-performance change must leave every one byte-
identical -- see tests/test_golden_corpus.py, which checks exactly that.

Deliberately bypasses the engine-version stamp (keyforge/version.py): that
stamp exists to refuse a REPLAY RECORD generated under different rules, but
the golden corpus's whole job is to be replayed again under engine code
that may have changed (that's what "pure-performance change" means to
verify) -- so entries here store `GameConfig`'s own fields directly, not a
version-stamped dict, and the corpus is regenerated by hand (this script)
only when an engine change is deliberately meant to alter play.

Run from Code/Non-GUI: `python -m tools.build_golden_corpus`
"""

from __future__ import annotations

import json
import os

from bots.heuristic_bot import HeuristicBot
from bots.random_bot import RandomBot
from keyforge.config import GameConfig
from keyforge.game import Game

_OUT_PATH = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "tests", "golden_corpus.json")

_AGENTS = {"random": RandomBot, "heuristic": HeuristicBot}


def _play(decks, seed, max_turns, agents, first_player=None, starting_chains=None, setup_script=None):
    config = GameConfig(
        decks=tuple(decks), seed=seed, max_turns=max_turns, first_player=first_player,
        starting_chains=starting_chains, setup_script=setup_script,
    )
    game = Game(config)
    bots = {
        1: _AGENTS[agents[0]](seed=seed),
        2: _AGENTS[agents[1]](seed=(seed or 0) + 1),
    }
    while not game.is_over:
        d = game.pending_decision
        game.submit(bots[d.player].decide(game.view_for(d.player), d))
    return config, game


def _entry(name, decks, seed, max_turns, agents, **kwargs):
    config, game = _play(decks, seed, max_turns, agents, **kwargs)
    return {
        "name": name,
        "decks": list(config.decks),
        "seed": config.seed,
        "max_turns": config.max_turns,
        "first_player": config.first_player,
        "starting_chains": config.starting_chains,
        "setup_script": config.setup_script,
        "agents": list(agents),
        "choice_record": game.choice_record,
        "outcome": game.result,
        "turns": game.turn_number,
        "state_hash": game.state_hash(),
    }


def build():
    entries = []
    for seed in range(6):
        entries.append(_entry(f"fignor_igor_random_seed{seed}", ("fignor", "igor"), seed, 200, ("random", "random")))
        entries.append(_entry(f"igor_fignor_random_seed{seed}", ("igor", "fignor"), seed, 200, ("random", "random")))
    for seed in range(6):
        entries.append(_entry(f"fignor_igor_heuristic_seed{seed}", ("fignor", "igor"), seed, 60, ("heuristic", "heuristic")))
    for seed in range(3):
        entries.append(_entry(f"fignor_igor_mixed_seed{seed}", ("fignor", "igor"), seed, 100, ("heuristic", "random")))
    entries.append(
        _entry(
            "setup_script_position", ("fignor", "igor"), 1, 20, ("random", "random"),
            setup_script=[["put_creature", 1, "Doc Bookton", "left"], ["set_aember", 1, 4]],
        )
    )
    return entries


def main():
    entries = build()
    with open(_OUT_PATH, "w", encoding="utf-8") as f:
        json.dump(entries, f, indent=2)
        f.write("\n")
    print(f"Wrote {len(entries)} golden corpus entries to {_OUT_PATH}")


if __name__ == "__main__":
    main()
