"""Routines generated by `tools/compile_engine.py` (Agent Observation Plan,
Part R) -- one module per engine module with generator functions, checked
into git. Don't edit them: change the source and recompile.

`load_all()` registers every routine in `keyforge.vm.ROUTINES`, keyed by the
ORIGINAL generator function's code object, after checking that each
generated module was made from the source as it is now. A routine's step and
binder functions are rebuilt to run in the source module's own globals, so
they see exactly the names the original code sees.
"""

from __future__ import annotations

import hashlib
import importlib
import os
import types
from typing import Dict, List, Tuple

from .. import vm

_PACKAGE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# generated module -> source module (dotted, under keyforge)
MODULES: Tuple[Tuple[str, str], ...] = (
    ("game", "game"),
    ("match", "match"),
    ("effects_steps", "effects.steps"),
    ("effects_generic", "effects.generic"),
    ("effects_named_brobnar", "effects.named.brobnar"),
    ("effects_named_dis", "effects.named.dis"),
    ("effects_named_logos", "effects.named.logos"),
    ("effects_named_mars", "effects.named.mars"),
    ("effects_named_sanctum", "effects.named.sanctum"),
    ("effects_named_shadows", "effects.named.shadows"),
    ("effects_named_untamed", "effects.named.untamed"),
)


class StaleCompiledModule(RuntimeError):
    pass


def _resolve(module, qualname: str, line: int) -> types.CodeType:
    """The code object of the function `qualname` (first line `line`) in
    `module`: an attribute path for a top-level function or method, then a
    search of each enclosing function's `co_consts` for a nested one."""
    first, *nested = qualname.split(".<locals>.")
    code = _function_of(module, first).__code__
    for depth, name in enumerate(nested):
        last = depth == len(nested) - 1
        matches = [c for c in code.co_consts if isinstance(c, types.CodeType) and c.co_name == name
                   and (not last or c.co_firstlineno == line)]
        if len(matches) != 1:
            raise LookupError(f"{module.__name__}: {len(matches)} nested code objects for {qualname!r} (line {line})")
        code = matches[0]
    return code


def _nested_codes(code: types.CodeType, wanted: Tuple[Tuple[str, int], ...]) -> Tuple[types.CodeType, ...]:
    """The nested code objects a routine rebuilds functions from, in the
    compiler's order: matched by name and first line, ties by order."""
    pool = [c for c in code.co_consts if isinstance(c, types.CodeType)]
    out = []
    used = set()
    for name, line in wanted:
        for i, c in enumerate(pool):
            if i not in used and c.co_name == name and c.co_firstlineno == line:
                used.add(i)
                out.append(c)
                break
        else:
            raise LookupError(f"{code.co_qualname if hasattr(code, 'co_qualname') else code.co_name}: no nested {name!r} at line {line}")
    return tuple(out)


def _load(gen_name: str, src_name: str) -> List[vm.Routine]:
    gen = importlib.import_module(f"{__name__}.{gen_name}")
    target = importlib.import_module(f"keyforge.{src_name}")
    path = os.path.join(_PACKAGE_DIR, *src_name.split(".")) + ".py"
    with open(path, "rb") as f:
        digest = hashlib.sha256(f.read()).hexdigest()
    if digest != gen.SOURCE_SHA256:
        raise StaleCompiledModule(f"keyforge/compiled/{gen_name}.py is stale for {gen.SOURCE}: run python -m tools.compile_engine")
    return register(gen.ROUTINES, target, src_name)


def register(entries, target, src_name: str) -> List[vm.Routine]:
    """Registers a generated module's `ROUTINES` entries against the
    functions of `target` (the module they were compiled from)."""
    g = target.__dict__
    for k, v in vm.SUPPORT.items():
        g.setdefault(k, v)
    out = []
    for qualname, line, step, binder, slots, freevars, nested, line_of_pc in entries:
        code = _resolve(target, qualname, line)
        dynamic = ".<locals>." in qualname
        nested_codes = _nested_codes(code, nested)
        step_fn = types.FunctionType(step.__code__, g, step.__name__, (nested_codes,))
        if dynamic:
            binder_fn = types.FunctionType(binder.__code__, g, binder.__name__, binder.__defaults__)
        else:
            orig = _function_of(target, qualname)
            binder_fn = types.FunctionType(binder.__code__, g, binder.__name__, orig.__defaults__)
            binder_fn.__kwdefaults__ = orig.__kwdefaults__
        rid = f"{src_name}:{qualname}"
        routine = vm.Routine(rid, qualname, src_name, step_fn, binder_fn, dynamic_defaults=dynamic, freevars=tuple(freevars),
                             local_names=tuple(slots), code=code, line_of_pc=dict(line_of_pc))
        vm.ROUTINES[code] = routine
        vm.ROUTINES_BY_ID[rid] = routine
        out.append(routine)
    return out


def _function_of(module, qualname: str):
    obj = module
    for part in qualname.split("."):
        obj = obj.__dict__[part] if hasattr(obj, "__dict__") and part in obj.__dict__ else getattr(obj, part)
    return getattr(obj, "__func__", obj)


def load_all() -> List[vm.Routine]:
    out = []
    for gen_name, src_name in MODULES:
        out.extend(_load(gen_name, src_name))
    return out
