"""Generated by tools/compile_engine.py from keyforge/effects/named/shadows.py -- do not edit.

Each pausing function of the source, as a routine for keyforge/vm.py's Machine:
`_kfr_*` runs it from a frame's pc, `_kfb_*` binds a call into a frame's locals.
"""

# fmt: off
# flake8: noqa
SOURCE = 'keyforge/effects/named/shadows.py'
SOURCE_SHA256 = 'ee566ded138c7267b546b802f75c2dc3641239b32376fb4736f5580bd15191ec'

# Placeholder defaults: the loader rebuilds every function here in the source module's globals,
# with the original function's own defaults.
_kf_U = None


def _kfr_bait_and_switch(F, _sent, _kfN):
    # effects/named/shadows.py:11 bait_and_switch
    (game, card, opponent, player,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 11
            player = controller_of(game, card)
            opponent = opponent_of(game, card)
            if not opponent.aember > player.aember:
                steps.shortfall(game, card, f"steals nothing: {{pos:{opponent.id}}} Æmber ({opponent.aember}) isn't more than {{mine:{player.id}}} ({player.aember})", "Enemy doesn't have more Æmber")
                return (3, None)
            steps.steal(game, opponent, player, 1)
            if opponent.aember > player.aember:
                steps.steal(game, opponent, player, 1)
            return (3, None)
            _kfd = None
            F.L = [game, card, opponent, player]
            F.pc = 1
            return (2, _kfd)
        elif _pc == 1:  # line 31
            return (3, None)

def _kfb_bait_and_switch(game, card):
    return [game, card, _kf_U, _kf_U]


def _kfr_booby_trap(F, _sent, _kfN):
    # effects/named/shadows.py:34 booby_trap
    (game, card, choice, neighbor, non_flank, owner_area, target,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 34
            non_flank = [c for pid in (1, 2) for c in game.players[pid].play_area.creatures if not game.players[pid].play_area.is_flank(c)]
            if not non_flank:
                steps.shortfall(game, card, 'deals no damage: every creature in play is on a flank', 'No non-flank creature')
                return (3, None)
            _kff = game.choose_cards
            _kfa = (card.controller, 'Booby Trap: choose a non-flank creature', non_flank, 1, 1,)
            _kfk = {'source_card': card, 'intent': DecisionIntent.DAMAGE, 'affects': Affects.ANY}
            F.L = [game, card, choice, neighbor, non_flank, owner_area, target]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 44
            choice = _sent
            target = choice[0]
            steps.deal_damage(game, target, 4)
            owner_area = game.players[target.controller].play_area
            for neighbor in owner_area.neighbors(target):
                steps.deal_damage(game, neighbor, 2)
            _kff = game.check_destroyed
            _kfa = ([target] + owner_area.neighbors(target),)
            _kfk = None
            F.L = [game, card, choice, neighbor, non_flank, owner_area, target]
            F.pc = 2
            return (1, _kff, _kfa, _kfk)
        elif _pc == 2:  # line 53
            return (3, None)

def _kfb_booby_trap(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U, _kf_U, _kf_U]


def _kfr_duskrunner_effect(F, _sent, _kfN):
    # effects/named/shadows.py:68 duskrunner_effect
    (game, host_card, controller,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 68
            controller = game.players[host_card.controller]
            steps.steal(game, game.players[3 - host_card.controller], controller, 1, source='Duskrunner')
            return (3, None)
            _kfd = None
            F.L = [game, host_card, controller]
            F.pc = 1
            return (2, _kfd)
        elif _pc == 1:  # line 72
            return (3, None)

def _kfb_duskrunner_effect(game, host_card):
    return [game, host_card, _kf_U]


def _kfr_ghostly_hand(F, _sent, _kfN):
    # effects/named/shadows.py:75 ghostly_hand
    (game, card, opponent,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 75
            opponent = opponent_of(game, card)
            if opponent.aember == 1:
                steps.steal(game, opponent, controller_of(game, card), 1)
            else:
                steps.shortfall(game, card, f'steals nothing: {{pos:{opponent.id}}} Æmber is {opponent.aember}, and it steals only when that is exactly 1', 'Needs exactly 1 enemy Æmber')
            return (3, None)
            _kfd = None
            F.L = [game, card, opponent]
            F.pc = 1
            return (2, _kfd)
        elif _pc == 1:  # line 82
            return (3, None)

def _kfb_ghostly_hand(game, card):
    return [game, card, _kf_U]


def _kfr_lights_out(F, _sent, _kfN):
    # effects/named/shadows.py:85 lights_out
    (game, card, c, choice, n, opponent, options,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 85
            opponent = opponent_of(game, card)
            options = list(opponent.play_area.creatures)
            if not options:
                steps.shortfall(game, card, 'returns nothing: there are no enemy creatures in play', 'No enemy creatures')
                return (3, None)
            n = min(2, len(options))
            if n < 2:
                steps.shortfall(game, card, 'returns only 1 creature: it was the only enemy creature in play', 'Only 1 enemy creature')
            _kff = game.choose_cards
            _kfa = (card.controller, f"Lights Out: return {n} enemy creature{('s' if n != 1 else '')}", options, n, n,)
            _kfk = {'source_card': card, 'intent': DecisionIntent.RETURN_TO_HAND, 'affects': Affects.ENEMY}
            F.L = [game, card, c, choice, n, opponent, options]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 95
            choice = _sent
            for c in choice:
                steps.return_to_hand(game, c)
            return (3, None)

def _kfb_lights_out(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U, _kf_U, _kf_U]


def _kfr_nerve_blast(F, _sent, _kfN):
    # effects/named/shadows.py:103 nerve_blast
    (game, card, choice, ok, opponent, player, targets,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 103
            player = controller_of(game, card)
            opponent = opponent_of(game, card)
            ok = steps.steal(game, opponent, player, 1)
            if not ok:
                steps.shortfall(game, card, f'steals nothing, so deals no damage: {{pos:{opponent.id}}} Æmber pool is empty', 'Nothing to steal')
                return (3, None)
            targets = game.all_creatures('any', card)
            if not targets:
                steps.shortfall(game, card, 'steals 1 but deals no damage: there are no creatures in play', 'No creature to damage')
                return (3, None)
            _kff = game.choose_cards
            _kfa = (player.id, 'Nerve Blast: deal 2 damage', targets, 1, 1,)
            _kfk = {'source_card': card, 'intent': DecisionIntent.DAMAGE, 'affects': Affects.ANY}
            F.L = [game, card, choice, ok, opponent, player, targets]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 114
            choice = _sent
            steps.deal_damage(game, choice[0], 2)
            _kff = game.check_destroyed
            _kfa = (choice,)
            _kfk = None
            F.L = [game, card, choice, ok, opponent, player, targets]
            F.pc = 2
            return (1, _kff, _kfa, _kfk)
        elif _pc == 2:  # line 119
            return (3, None)

def _kfb_nerve_blast(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U, _kf_U, _kf_U]


def _kfr_noddy_action(F, _sent, _kfN):
    # effects/named/shadows.py:122 noddy_action
    (game, card,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 122
            steps.steal(game, opponent_of(game, card), controller_of(game, card), 1, source=card)
            return (3, None)
            _kfd = None
            F.L = [game, card]
            F.pc = 1
            return (2, _kfd)
        elif _pc == 1:  # line 125
            return (3, None)

def _kfb_noddy_action(game, card):
    return [game, card]


def _kfr_old_bruno_play(F, _sent, _kfN):
    # effects/named/shadows.py:128 old_bruno_play
    (game, card,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 128
            steps.capture(game, card, 3)
            return (3, None)
            _kfd = None
            F.L = [game, card]
            F.pc = 1
            return (2, _kfd)
        elif _pc == 1:  # line 131
            return (3, None)

def _kfb_old_bruno_play(game, card):
    return [game, card]


def _kfr_one_last_job(F, _sent, _kfN):
    # effects/named/shadows.py:134 one_last_job
    (game, card, c, n, player, targets,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 134
            player = controller_of(game, card)
            targets = [c for c in player.play_area.creatures if c.house == House.SHADOWS]
            n = 0
            for c in list(targets):
                if steps.purge(game, c):
                    n += 1
            if n:
                steps.steal(game, opponent_of(game, card), player, n, source=card)
            else:
                steps.shortfall(game, card, 'purges nothing, so steals nothing: there are no friendly Shadows creatures in play', 'No Shadows creatures')
            return (3, None)
            _kfd = None
            F.L = [game, card, c, n, player, targets]
            F.pc = 1
            return (2, _kfd)
        elif _pc == 1:  # line 146
            return (3, None)

def _kfb_one_last_job(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U, _kf_U]


def _kfr_oubliette(F, _sent, _kfN):
    # effects/named/shadows.py:149 oubliette
    (game, card, choice, targets,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 149
            targets = [c for c in game.all_creatures('any', card) if game.get_power(c) <= 3]
            if not targets:
                steps.shortfall(game, card, 'purges nothing: no creature in play has power 3 or less', 'No creature with power 3 or less')
                return (3, None)
            _kff = game.choose_cards
            _kfa = (card.controller, 'Oubliette: purge a creature (power <= 3)', targets, 1, 1,)
            _kfk = {'source_card': card, 'intent': DecisionIntent.PURGE, 'affects': Affects.ANY}
            F.L = [game, card, choice, targets]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 154
            choice = _sent
            steps.purge(game, choice[0])
            return (3, None)

def _kfb_oubliette(game, card):
    return [game, card, _kf_U, _kf_U]


def _kfr_pawn_sacrifice(F, _sent, _kfN):
    # effects/named/shadows.py:161 pawn_sacrifice
    (game, card, choice, ok, options, player, remaining_targets, t, targets, victim,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 161
            player = controller_of(game, card)
            options = list(player.play_area.creatures)
            if not options:
                steps.shortfall(game, card, 'does nothing: there is no friendly creature to sacrifice', 'Nothing to sacrifice')
                return (3, None)
            _kff = game.choose_cards
            _kfa = (player.id, 'Pawn Sacrifice: sacrifice a friendly creature', options, 1, 1,)
            _kfk = {'source_card': card, 'intent': DecisionIntent.SACRIFICE, 'affects': Affects.FRIENDLY}
            F.L = [game, card, choice, ok, options, player, remaining_targets, t, targets, victim]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 167
            choice = _sent
            victim = choice[0]
            _kff = steps.sacrifice
            _kfa = (game, victim,)
            _kfk = None
            F.L = [game, card, choice, ok, options, player, remaining_targets, t, targets, victim]
            F.pc = 2
            return (1, _kff, _kfa, _kfk)
        elif _pc == 2:  # line 172
            ok = _sent
            if not ok:
                return (3, None)
            remaining_targets = game.all_creatures('any', card)
            if not remaining_targets:
                steps.shortfall(game, card, 'deals no damage: no creatures are left in play after the sacrifice', 'No creatures left')
                return (3, None)
            _pc = 3 if len(remaining_targets) == 1 else 4
            continue
        elif _pc == 3:  # line 180
            steps.shortfall(game, card, 'damages only 1 creature: it was the only one left in play', 'Only 1 creature left')
            targets = remaining_targets
            _pc = 5
            continue
        elif _pc == 4:  # line 183
            _kff = game.choose_cards
            _kfa = (player.id, 'Pawn Sacrifice: choose 2 different creatures', remaining_targets, 2, 2,)
            _kfk = {'source_card': card, 'intent': DecisionIntent.DAMAGE, 'affects': Affects.ANY}
            F.L = [game, card, choice, ok, options, player, remaining_targets, t, targets, victim]
            F.pc = 6
            return (1, _kff, _kfa, _kfk)
        elif _pc == 5:  # line 179
            for t in targets:
                steps.deal_damage(game, t, 3)
            _kff = game.check_destroyed
            _kfa = (targets,)
            _kfk = None
            F.L = [game, card, choice, ok, options, player, remaining_targets, t, targets, victim]
            F.pc = 7
            return (1, _kff, _kfa, _kfk)
        elif _pc == 6:  # line 183
            targets = _sent
            _pc = 5
            continue
        elif _pc == 7:  # line 189
            return (3, None)

def _kfb_pawn_sacrifice(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U, _kf_U, _kf_U, _kf_U, _kf_U, _kf_U]


def _kfr_relentless_whispers(F, _sent, _kfN):
    # effects/named/shadows.py:192 relentless_whispers
    (game, card, choice, destroyed, player, target, targets,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 192
            player = controller_of(game, card)
            targets = game.all_creatures('any', card)
            if not targets:
                steps.shortfall(game, card, 'deals no damage: there are no creatures in play', 'No creature to damage')
                return (3, None)
            _kff = game.choose_cards
            _kfa = (player.id, 'Relentless Whispers: deal 2 damage', targets, 1, 1,)
            _kfk = {'source_card': card, 'intent': DecisionIntent.DAMAGE, 'affects': Affects.ANY}
            F.L = [game, card, choice, destroyed, player, target, targets]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 198
            choice = _sent
            target = choice[0]
            steps.deal_damage(game, target, 2)
            _kff = game.check_destroyed
            _kfa = ([target],)
            _kfk = None
            F.L = [game, card, choice, destroyed, player, target, targets]
            F.pc = 2
            return (1, _kff, _kfa, _kfk)
        elif _pc == 2:  # line 204
            destroyed = _sent
            if target in destroyed:
                steps.steal(game, opponent_of(game, card), player, 1, source=card)
            return (3, None)

def _kfb_relentless_whispers(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U, _kf_U, _kf_U]


def _kfr_silvertooth_play(F, _sent, _kfN):
    # effects/named/shadows.py:209 silvertooth_play
    (game, card,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 209
            steps.ready(game, card)
            return (3, None)
            _kfd = None
            F.L = [game, card]
            F.pc = 1
            return (2, _kfd)
        elif _pc == 1:  # line 212
            return (3, None)

def _kfb_silvertooth_play(game, card):
    return [game, card]


def _kfr_subtle_maul(F, _sent, _kfN):
    # effects/named/shadows.py:215 subtle_maul
    (game, card,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 215
            _kff = steps.discard_random
            _kfa = (game, opponent_of(game, card),)
            _kfk = {'source': card}
            F.L = [game, card]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 216
            return (3, None)

def _kfb_subtle_maul(game, card):
    return [game, card]


def _kfr_too_much_to_protect(F, _sent, _kfN):
    # effects/named/shadows.py:219 too_much_to_protect
    (game, card, amount, opponent,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 219
            opponent = opponent_of(game, card)
            amount = max(opponent.aember - 6, 0)
            if amount == 0:
                steps.shortfall(game, card, f'steals nothing: {{pos:{opponent.id}}} Æmber is {opponent.aember}, and it takes only what is above 6', '6 or less to take')
            steps.steal(game, opponent, controller_of(game, card), amount)
            return (3, None)
            _kfd = None
            F.L = [game, card, amount, opponent]
            F.pc = 1
            return (2, _kfd)
        elif _pc == 1:  # line 226
            return (3, None)

def _kfb_too_much_to_protect(game, card):
    return [game, card, _kf_U, _kf_U]


def _kfr_urchin_play(F, _sent, _kfN):
    # effects/named/shadows.py:229 urchin_play
    (game, card,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 229
            steps.steal(game, opponent_of(game, card), controller_of(game, card), 1, source=card)
            return (3, None)
            _kfd = None
            F.L = [game, card]
            F.pc = 1
            return (2, _kfd)
        elif _pc == 1:  # line 232
            return (3, None)

def _kfb_urchin_play(game, card):
    return [game, card]


def _kfr_bad_penny_destroyed(F, _sent, _kfN):
    # effects/named/shadows.py:235 bad_penny_destroyed
    (game, card,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 235
            card.destined_zone = 'hand'
            return (3, None)
            _kfd = None
            F.L = [game, card]
            F.pc = 1
            return (2, _kfd)
        elif _pc == 1:  # line 238
            return (3, None)

def _kfb_bad_penny_destroyed(game, card):
    return [game, card]


def _kfr_finishing_blow(F, _sent, _kfN):
    # effects/named/shadows.py:243 finishing_blow
    (game, card, choice, destroyed, player, targets,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 243
            player = controller_of(game, card)
            targets = [c for c in game.all_creatures('any', card) if c.type_object.damage > 0]
            if not targets:
                steps.shortfall(game, card, 'destroys nothing: no creature in play is damaged', 'No damaged creature')
                return (3, None)
            _kff = game.choose_cards
            _kfa = (player.id, 'Finishing Blow: destroy a damaged creature', targets, 1, 1,)
            _kfk = {'source_card': card, 'intent': DecisionIntent.DESTROY, 'affects': Affects.ANY}
            F.L = [game, card, choice, destroyed, player, targets]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 249
            choice = _sent
            _kff = game.destroy_cards
            _kfa = (choice,)
            _kfk = None
            F.L = [game, card, choice, destroyed, player, targets]
            F.pc = 2
            return (1, _kff, _kfa, _kfk)
        elif _pc == 2:  # line 253
            destroyed = _sent
            if choice[0] in destroyed:
                steps.steal(game, opponent_of(game, card), player, 1, source=card)
            return (3, None)

def _kfb_finishing_blow(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U, _kf_U]


def _kfr_imperial_traitor(F, _sent, _kfN):
    # effects/named/shadows.py:258 imperial_traitor
    (game, card, choice, opponent, player, targets,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 258
            player = controller_of(game, card)
            opponent = opponent_of(game, card)
            game.reveal_hand(opponent.id, player.id, source=card)
            targets = [c for c in opponent.hand.cards() if c.house == House.SANCTUM]
            if not targets:
                steps.shortfall(game, card, f'purges nothing: {{pos:{opponent.id}}} hand has no Sanctum card', 'No Sanctum card in hand')
                return (3, None)
            _kff = game.choose_cards
            _kfa = (player.id, "Imperial Traitor: you may purge a Sanctum card from the opponent's hand", targets, 0, 1,)
            _kfk = {'source_card': card, 'intent': DecisionIntent.PURGE, 'affects': Affects.ENEMY, 'optional': True}
            F.L = [game, card, choice, opponent, player, targets]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 266
            choice = _sent
            if choice:
                steps.purge(game, choice[0])
            return (3, None)

def _kfb_imperial_traitor(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U, _kf_U]


def _kfr_key_of_darkness(F, _sent, _kfN):
    # effects/named/shadows.py:274 key_of_darkness
    (game, card, modifier, opponent,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 274
            opponent = opponent_of(game, card)
            modifier = 2 if opponent.aember == 0 else 6
            _kff = game.forge_key
            _kfa = (card.controller,)
            _kfk = {'cost_modifier': modifier, 'source': card}
            F.L = [game, card, modifier, opponent]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 277
            return (3, None)

def _kfb_key_of_darkness(game, card):
    return [game, card, _kf_U, _kf_U]


def _kfr_poison_wave(F, _sent, _kfN):
    # effects/named/shadows.py:280 poison_wave
    (game, card, c, targets,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 280
            targets = game.all_creatures('any', card)
            if not targets:
                steps.shortfall(game, card, 'deals no damage: there are no creatures in play', 'No creatures')
                return (3, None)
            for c in targets:
                steps.deal_damage(game, c, 2)
            _kff = game.check_destroyed
            _kfa = (targets,)
            _kfk = None
            F.L = [game, card, c, targets]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 287
            return (3, None)

def _kfb_poison_wave(game, card):
    return [game, card, _kf_U, _kf_U]


def _kfr_routine_job(F, _sent, _kfN):
    # effects/named/shadows.py:290 routine_job
    (game, card, copies_in_discard, opponent, player,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 290
            player = controller_of(game, card)
            opponent = opponent_of(game, card)
            copies_in_discard = sum((1 for c in player.discard.cards() if c.name == 'Routine Job'))
            steps.steal(game, opponent, player, 1 + copies_in_discard, source=card)
            return (3, None)
            _kfd = None
            F.L = [game, card, copies_in_discard, opponent, player]
            F.pc = 1
            return (2, _kfd)
        elif _pc == 1:  # line 296
            return (3, None)

def _kfb_routine_job(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U]


def _kfr_treasure_map(F, _sent, _kfN):
    # effects/named/shadows.py:299 treasure_map
    (game, card, player,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 299
            player = controller_of(game, card)
            if player.hand_plays_this_turn == 1:
                steps.gain(game, player, 3)
            else:
                steps.shortfall(game, card, 'gains nothing: you already played another card this turn', 'Already played a card')
            game.active_effects.add(DurationEffect(card, card.controller, 1, card.controller, 'CanPlayCards', '=', False))
            game.log.add('duration_effect', card=card.name, iid=card.instance_id, variable='CanPlayCards', op='=', value=False, player=card.controller, affected=[card.controller])
            return (3, None)
            _kfd = None
            F.L = [game, card, player]
            F.pc = 1
            return (2, _kfd)
        elif _pc == 1:  # line 311
            return (3, None)

def _kfb_treasure_map(game, card):
    return [game, card, _kf_U]


def _kfr__evasion_sigil_handler(F, _sent, _kfN):
    # effects/named/shadows.py:323 _evasion_sigil_handler
    (game, event, attacker, controller, top,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 323
            attacker = event['attacker']
            controller = game.players[attacker.controller]
            top = controller.deck.draw_top()
            if top is not None:
                controller.discard.push(top)
                game.log.add('discard', player=controller.id, card=top.name, iid=top.instance_id)
                if top.house == controller.selected_house:
                    event['cancelled'] = True
                    steps.shortfall(game, attacker, 'is exhausted with no effect: Evasion Sigil discarded a card of the active house', 'Evasion Sigil: no effect')
            return (3, None)
            _kfd = None
            F.L = [game, event, attacker, controller, top]
            F.pc = 1
            return (2, _kfd)
        elif _pc == 1:  # line 334
            return (3, None)

def _kfb__evasion_sigil_handler(game, event):
    return [game, event, _kf_U, _kf_U, _kf_U]


def _kfr_longfused_mines(F, _sent, _kfN):
    # effects/named/shadows.py:337 longfused_mines
    (game, card, c, opponent, targets,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 337
            opponent = opponent_of(game, card)
            _kff = steps.sacrifice
            _kfa = (game, card,)
            _kfk = None
            F.L = [game, card, c, opponent, targets]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 339
            targets = [c for c in opponent.play_area.creatures if not opponent.play_area.is_flank(c)]
            if not targets:
                steps.shortfall(game, card, 'deals no damage: every enemy creature is on a flank', 'No non-flank enemy creature')
                return (3, None)
            for c in targets:
                steps.deal_damage(game, c, 3)
            _kff = game.check_destroyed
            _kfa = (targets,)
            _kfk = None
            F.L = [game, card, c, opponent, targets]
            F.pc = 2
            return (1, _kff, _kfa, _kfk)
        elif _pc == 2:  # line 346
            return (3, None)

def _kfb_longfused_mines(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U]


def _kfr_masterplan_play(F, _sent, _kfN):
    # effects/named/shadows.py:349 masterplan_play
    (game, card, c, choice, options, player,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 349
            player = controller_of(game, card)
            options = player.hand.cards()
            if not options:
                steps.shortfall(game, card, f'has no card to place beneath it: {{pos:{player.id}}} hand is empty', 'Hand is empty')
                return (3, None)
            _kff = game.choose_cards
            _kfa = (player.id, 'Masterplan: put a card from your hand facedown beneath it', options, 1, 1,)
            _kfk = {'source_card': card, 'intent': DecisionIntent.MODIFY, 'affects': Affects.FRIENDLY}
            F.L = [game, card, c, choice, options, player]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 355
            choice = _sent
            c = choice[0]
            player.hand.remove(c)
            card.under_cards.append(c)
            game.log.add('under_card', visible_to={player.id}, player=player.id, card=card.name, iid=card.instance_id, under=c.name, under_iid=c.instance_id)
            return (3, None)

def _kfb_masterplan_play(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U, _kf_U]


def _kfr_masterplan_omni(F, _sent, _kfN):
    # effects/named/shadows.py:369 masterplan_omni
    (game, card, ok, player, to_play,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 369
            player = controller_of(game, card)
            _pc = 1 if not card.under_cards else 2
            continue
        elif _pc == 1:  # line 372
            steps.shortfall(game, card, 'has no card to play: nothing is beneath it', 'Nothing beneath it')
            _pc = 3
            continue
        elif _pc == 2:  # line 374
            to_play = card.under_cards.pop(0)
            _kff = game._play_card
            _kfa = (player.id, to_play,)
            _kfk = {'from_deck_top': True}
            F.L = [game, card, ok, player, to_play]
            F.pc = 4
            return (1, _kff, _kfa, _kfk)
        elif _pc == 3:  # line 371
            _kff = steps.sacrifice
            _kfa = (game, card,)
            _kfk = None
            F.L = [game, card, ok, player, to_play]
            F.pc = 5
            return (1, _kff, _kfa, _kfk)
        elif _pc == 4:  # line 375
            ok = _sent
            if not ok:
                card.under_cards.insert(0, to_play)
                steps.shortfall(game, card, f"can't play {to_play.name} right now; it stays beneath Masterplan", f"Can't play {to_play.name}")
            _pc = 3
            continue
        elif _pc == 5:  # line 379
            return (3, None)

def _kfb_masterplan_omni(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U]


def _kfr_seeker_needle(F, _sent, _kfN):
    # effects/named/shadows.py:382 seeker_needle
    (game, card, choice, destroyed, player, target, targets,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 382
            player = controller_of(game, card)
            targets = game.all_creatures('any', card)
            if not targets:
                steps.shortfall(game, card, 'deals no damage: there are no creatures in play', 'No creature to damage')
                return (3, None)
            _kff = game.choose_cards
            _kfa = (player.id, f'{card.name}: deal 1 damage', targets, 1, 1,)
            _kfk = {'source_card': card, 'intent': DecisionIntent.DAMAGE, 'affects': Affects.ANY}
            F.L = [game, card, choice, destroyed, player, target, targets]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 388
            choice = _sent
            target = choice[0]
            steps.deal_damage(game, target, 1)
            _kff = game.check_destroyed
            _kfa = ([target],)
            _kfk = None
            F.L = [game, card, choice, destroyed, player, target, targets]
            F.pc = 2
            return (1, _kff, _kfa, _kfk)
        elif _pc == 2:  # line 394
            destroyed = _sent
            if target in destroyed:
                steps.gain(game, player, 1)
            return (3, None)

def _kfb_seeker_needle(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U, _kf_U, _kf_U]


def _kfr_skeleton_key(F, _sent, _kfN):
    # effects/named/shadows.py:402 skeleton_key
    (game, card, choice, player, targets,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 402
            player = controller_of(game, card)
            targets = list(player.play_area.creatures)
            if not targets:
                steps.shortfall(game, card, 'captures nothing: there is no friendly creature in play', 'No friendly creature')
                return (3, None)
            _kff = game.choose_cards
            _kfa = (player.id, 'Skeleton Key: choose a friendly creature to capture 1Æ', targets, 1, 1,)
            _kfk = {'source_card': card, 'intent': DecisionIntent.CAPTURE, 'affects': Affects.FRIENDLY}
            F.L = [game, card, choice, player, targets]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 408
            choice = _sent
            steps.capture(game, choice[0], 1)
            return (3, None)

def _kfb_skeleton_key(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U]


def _kfr_special_delivery(F, _sent, _kfN):
    # effects/named/shadows.py:415 special_delivery
    (game, card, choice, destroyed, player, target, targets,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 415
            player = controller_of(game, card)
            _kff = steps.sacrifice
            _kfa = (game, card,)
            _kfk = None
            F.L = [game, card, choice, destroyed, player, target, targets]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 417
            targets = [c for pid in (1, 2) for c in game.players[pid].play_area.creatures if game.players[pid].play_area.is_flank(c)]
            if not targets:
                steps.shortfall(game, card, 'deals no damage: there are no flank creatures in play', 'No flank creature')
                return (3, None)
            _kff = game.choose_cards
            _kfa = (player.id, 'Special Delivery: deal 3 damage to a flank creature', targets, 1, 1,)
            _kfk = {'source_card': card, 'intent': DecisionIntent.DAMAGE, 'affects': Affects.ANY}
            F.L = [game, card, choice, destroyed, player, target, targets]
            F.pc = 2
            return (1, _kff, _kfa, _kfk)
        elif _pc == 2:  # line 422
            choice = _sent
            target = choice[0]
            steps.deal_damage(game, target, 3)
            _kff = game.check_destroyed
            _kfa = ([target],)
            _kfk = None
            F.L = [game, card, choice, destroyed, player, target, targets]
            F.pc = 3
            return (1, _kff, _kfa, _kfk)
        elif _pc == 3:  # line 428
            destroyed = _sent
            if target in destroyed:
                steps.purge(game, target)
            return (3, None)

def _kfb_special_delivery(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U, _kf_U, _kf_U]


def _kfr_the_sting_action(F, _sent, _kfN):
    # effects/named/shadows.py:442 the_sting_action
    (game, card,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 442
            _kff = steps.sacrifice
            _kfa = (game, card,)
            _kfk = None
            F.L = [game, card]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 443
            return (3, None)

def _kfb_the_sting_action(game, card):
    return [game, card]


def _kfr_bulleteye(F, _sent, _kfN):
    # effects/named/shadows.py:446 bulleteye
    (game, card, choice, player, targets,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 446
            player = controller_of(game, card)
            targets = [c for pid in (1, 2) for c in game.players[pid].play_area.creatures if game.players[pid].play_area.is_flank(c)]
            if not targets:
                steps.shortfall(game, card, 'destroys nothing: there are no flank creatures in play', 'No flank creature')
                return (3, None)
            _kff = game.choose_cards
            _kfa = (player.id, 'Bulleteye: destroy a flank creature', targets, 1, 1,)
            _kfk = {'source_card': card, 'intent': DecisionIntent.DESTROY, 'affects': Affects.ANY}
            F.L = [game, card, choice, player, targets]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 452
            choice = _sent
            _kff = game.destroy_cards
            _kfa = (choice,)
            _kfk = None
            F.L = [game, card, choice, player, targets]
            F.pc = 2
            return (1, _kff, _kfa, _kfk)
        elif _pc == 2:  # line 456
            return (3, None)

def _kfb_bulleteye(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U]


def _kfr__carlo_phantom_handler__handler(F, _sent, _kfN):
    # effects/named/shadows.py:464 _carlo_phantom_handler.<locals>.handler
    (game, event, _kfc_carlo_card,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 464
            if event['card'].type == CardType.ARTIFACT:
                steps.steal(game, game.players[3 - _kfc_carlo_card.cell_contents.controller], game.players[_kfc_carlo_card.cell_contents.controller], 1, source=_kfc_carlo_card.cell_contents)
            return (3, None)
            _kfd = None
            F.L = [game, event, _kfc_carlo_card]
            F.pc = 1
            return (2, _kfd)
        elif _pc == 1:  # line 468
            return (3, None)

def _kfb__carlo_phantom_handler__handler(game, event):
    return [game, event, _kf_U]


def _kfr_deipno_spymaster(F, _sent, _kfN):
    # effects/named/shadows.py:472 deipno_spymaster
    (game, card, choice, may_use, options, player, target,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 472
            player = controller_of(game, card)
            options = list(player.play_area.creatures)
            if not options:
                steps.shortfall(game, card, 'chooses nothing: there are no friendly creatures in play', 'No friendly creature')
                return (3, None)
            _kff = game.choose_cards
            _kfa = (player.id, 'Deipno Spymaster: choose a friendly creature', options, 1, 1,)
            _kfk = {'source_card': card, 'intent': DecisionIntent.USE_TARGET, 'affects': Affects.FRIENDLY}
            F.L = [game, card, choice, may_use, options, player, target]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 478
            choice = _sent
            target = choice[0]
            if target.Exhausted:
                steps.shortfall(game, card, f"can't use {target.name}: it is already exhausted", f'{target.name} is exhausted')
                return (3, None)
            _kff = game.yes_no
            _kfa = (player.id, f'Deipno Spymaster: use {target.name} this turn?',)
            _kfk = {'source_card': card, 'intent': DecisionIntent.OPTIONAL_TRIGGER}
            F.L = [game, card, choice, may_use, options, player, target]
            F.pc = 2
            return (1, _kff, _kfa, _kfk)
        elif _pc == 2:  # line 486
            may_use = _sent
            _pc = 3 if may_use else 4
            continue
        elif _pc == 3:  # line 491
            _kff = steps.use_creature
            _kfa = (game, target,)
            _kfk = None
            F.L = [game, card, choice, may_use, options, player, target]
            F.pc = 6
            return (1, _kff, _kfa, _kfk)
        elif _pc == 4:  # line 490
            _pc = 5
            continue
        elif _pc == 5:  # line 490
            return (3, None)
        elif _pc == 6:  # line 491
            _pc = 5
            continue

def _kfb_deipno_spymaster(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U, _kf_U, _kf_U]


def _kfr_faygin(F, _sent, _kfN):
    # effects/named/shadows.py:494 faygin
    (game, card, choice, in_play, options, player, target,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 494
            player = controller_of(game, card)
            in_play = [c for pid in (1, 2) for c in game.players[pid].play_area.creatures if c.name == 'Urchin']
            options = in_play + [c for c in player.discard.cards() if c.name == 'Urchin']
            if not options:
                steps.shortfall(game, card, 'returns nothing: there is no Urchin in play or in your discard pile', 'No Urchin')
                return (3, None)
            _kff = game.choose_cards
            _kfa = (player.id, "Faygin: return an Urchin to its owner's hand", options, 1, 1,)
            _kfk = {'source_card': card, 'intent': DecisionIntent.RETURN_TO_HAND, 'affects': Affects.ANY}
            F.L = [game, card, choice, in_play, options, player, target]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 506
            choice = _sent
            target = choice[0]
            if target in in_play:
                steps.return_to_hand(game, target)
            else:
                player.discard.remove(target)
                player.hand.add(target)
                game.log.add('return_to_hand', card=target.name, iid=target.instance_id, owner=player.id)
            return (3, None)

def _kfb_faygin(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U, _kf_U, _kf_U]


def _kfr_magda_the_rat_play(F, _sent, _kfN):
    # effects/named/shadows.py:519 magda_the_rat_play
    (game, card,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 519
            steps.steal(game, opponent_of(game, card), controller_of(game, card), 2, source=card)
            return (3, None)
            _kfd = None
            F.L = [game, card]
            F.pc = 1
            return (2, _kfd)
        elif _pc == 1:  # line 522
            return (3, None)

def _kfb_magda_the_rat_play(game, card):
    return [game, card]


def _kfr_nexus(F, _sent, _kfN):
    # effects/named/shadows.py:529 nexus
    (game, card, choice, opponent, player, targets,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 529
            player = controller_of(game, card)
            opponent = opponent_of(game, card)
            targets = [a for a in opponent.play_area.artifacts if (a.card_def.on_action is not None or a.card_def.on_omni is not None) and (not a.Exhausted)]
            if not targets:
                steps.shortfall(game, card, 'uses nothing: the opponent has no usable artifact in play', 'No usable enemy artifact')
                return (3, None)
            _kff = game.choose_cards
            _kfa = (player.id, "Nexus: use an opponent's artifact as if it were yours", targets, 1, 1,)
            _kfk = {'source_card': card, 'intent': DecisionIntent.USE_TARGET, 'affects': Affects.ENEMY}
            F.L = [game, card, choice, opponent, player, targets]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 539
            choice = _sent
            _kff = game.use_artifact_ability
            _kfa = (choice[0], player.id,)
            _kfk = None
            F.L = [game, card, choice, opponent, player, targets]
            F.pc = 2
            return (1, _kff, _kfa, _kfk)
        elif _pc == 2:  # line 543
            return (3, None)

def _kfb_nexus(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U, _kf_U]


def _kfr_selwyn_the_fence(F, _sent, _kfN):
    # effects/named/shadows.py:546 selwyn_the_fence
    (game, card, choice, player, source_card, sources,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 546
            player = controller_of(game, card)
            sources = [c for c in player.play_area.creatures if c.aember_captured > 0] + [c for c in player.play_area.artifacts if c.aember_stored > 0]
            if not sources:
                steps.shortfall(game, card, 'moves nothing: none of your cards have Æmber on them', 'No Æmber on your cards')
                return (3, None)
            _kff = game.choose_cards
            _kfa = (player.id, 'Selwyn the Fence: move 1Æ from one of your cards to your pool', sources, 1, 1,)
            _kfk = {'source_card': card, 'intent': DecisionIntent.DRAIN, 'affects': Affects.FRIENDLY}
            F.L = [game, card, choice, player, source_card, sources]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 552
            choice = _sent
            source_card = choice[0]
            if source_card.aember_captured > 0:
                source_card.aember_captured -= 1
            else:
                source_card.aember_stored -= 1
            player.aember += 1
            game.log.add('move_aember', player=player.id, card=source_card.name, iid=source_card.instance_id, amount=1, to='pool')
            return (3, None)

def _kfb_selwyn_the_fence(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U, _kf_U]


def _kfr_smiling_ruth(F, _sent, _kfN):
    # effects/named/shadows.py:582 smiling_ruth
    (game, card, choice, opponent, player, targets,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 582
            player = controller_of(game, card)
            if not game.forged_key_on_turn(player.id, game.turn_number):
                steps.shortfall(game, card, 'takes control of nothing: you have not forged a key this turn', 'No key forged this turn')
                return (3, None)
            opponent = opponent_of(game, card)
            targets = [c for c in opponent.play_area.creatures if opponent.play_area.is_flank(c)]
            if not targets:
                steps.shortfall(game, card, 'takes control of nothing: the opponent has no flank creature', 'No enemy flank creature')
                return (3, None)
            _kff = game.choose_cards
            _kfa = (player.id, 'Smiling Ruth: take control of an enemy flank creature', targets, 1, 1,)
            _kfk = {'source_card': card, 'intent': DecisionIntent.TAKE_CONTROL, 'affects': Affects.ENEMY}
            F.L = [game, card, choice, opponent, player, targets]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 592
            choice = _sent
            _kff = game.take_control
            _kfa = (choice[0], player.id,)
            _kfk = None
            F.L = [game, card, choice, opponent, player, targets]
            F.pc = 2
            return (1, _kff, _kfa, _kfk)
        elif _pc == 2:  # line 596
            return (3, None)

def _kfb_smiling_ruth(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U, _kf_U]


def _kfr_sneklifter(F, _sent, _kfN):
    # effects/named/shadows.py:599 sneklifter
    (game, card, choice, opponent, player, target, targets,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 599
            player = controller_of(game, card)
            opponent = opponent_of(game, card)
            targets = list(opponent.play_area.artifacts)
            if not targets:
                steps.shortfall(game, card, 'takes control of nothing: the opponent has no artifact in play', 'No enemy artifact')
                return (3, None)
            _kff = game.choose_cards
            _kfa = (player.id, 'Sneklifter: take control of an enemy artifact', targets, 1, 1,)
            _kfk = {'source_card': card, 'intent': DecisionIntent.TAKE_CONTROL, 'affects': Affects.ENEMY}
            F.L = [game, card, choice, opponent, player, target, targets]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 606
            choice = _sent
            target = choice[0]
            _kff = game.take_control
            _kfa = (target, player.id,)
            _kfk = None
            F.L = [game, card, choice, opponent, player, target, targets]
            F.pc = 2
            return (1, _kff, _kfa, _kfk)
        elif _pc == 2:  # line 611
            if target.house not in game.player_houses(player.id):
                target.house_override = House.SHADOWS
            return (3, None)

def _kfb_sneklifter(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U, _kf_U, _kf_U]


def _kfr__silent_dagger_effect(F, _sent, _kfN):
    # effects/named/shadows.py:628 _silent_dagger_effect
    (game, host_card, choice, targets,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 628
            targets = [c for pid in (1, 2) for c in game.players[pid].play_area.creatures if game.players[pid].play_area.is_flank(c)]
            if not targets:
                steps.shortfall(game, host_card, 'deals no damage: there are no flank creatures in play', 'No flank creature')
                return (3, None)
            _kff = game.choose_cards
            _kfa = (host_card.controller, 'Silent Dagger: deal 4 damage to a flank creature', targets, 1, 1,)
            _kfk = {'source_card': host_card, 'intent': DecisionIntent.DAMAGE, 'affects': Affects.ANY}
            F.L = [game, host_card, choice, targets]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 633
            choice = _sent
            steps.deal_damage(game, choice[0], 4)
            _kff = game.check_destroyed
            _kfa = (choice,)
            _kfk = None
            F.L = [game, host_card, choice, targets]
            F.pc = 2
            return (1, _kff, _kfa, _kfk)
        elif _pc == 2:  # line 638
            return (3, None)

def _kfb__silent_dagger_effect(game, host_card):
    return [game, host_card, _kf_U, _kf_U]


# (qualname, first line, step, binder, slots, freevar slots, nested code (name, line), line of each pc)
ROUTINES = [
    ('bait_and_switch', 11, _kfr_bait_and_switch, _kfb_bait_and_switch, ('game', 'card', 'opponent', 'player'), (), (), {0: 11, 1: 31}),
    ('booby_trap', 34, _kfr_booby_trap, _kfb_booby_trap, ('game', 'card', 'choice', 'neighbor', 'non_flank', 'owner_area', 'target'), (), (), {0: 34, 1: 44, 2: 53}),
    ('duskrunner_effect', 68, _kfr_duskrunner_effect, _kfb_duskrunner_effect, ('game', 'host_card', 'controller'), (), (), {0: 68, 1: 72}),
    ('ghostly_hand', 75, _kfr_ghostly_hand, _kfb_ghostly_hand, ('game', 'card', 'opponent'), (), (), {0: 75, 1: 82}),
    ('lights_out', 85, _kfr_lights_out, _kfb_lights_out, ('game', 'card', 'c', 'choice', 'n', 'opponent', 'options'), (), (), {0: 85, 1: 95}),
    ('nerve_blast', 103, _kfr_nerve_blast, _kfb_nerve_blast, ('game', 'card', 'choice', 'ok', 'opponent', 'player', 'targets'), (), (), {0: 103, 1: 114, 2: 119}),
    ('noddy_action', 122, _kfr_noddy_action, _kfb_noddy_action, ('game', 'card'), (), (), {0: 122, 1: 125}),
    ('old_bruno_play', 128, _kfr_old_bruno_play, _kfb_old_bruno_play, ('game', 'card'), (), (), {0: 128, 1: 131}),
    ('one_last_job', 134, _kfr_one_last_job, _kfb_one_last_job, ('game', 'card', 'c', 'n', 'player', 'targets'), (), (), {0: 134, 1: 146}),
    ('oubliette', 149, _kfr_oubliette, _kfb_oubliette, ('game', 'card', 'choice', 'targets'), (), (), {0: 149, 1: 154}),
    ('pawn_sacrifice', 161, _kfr_pawn_sacrifice, _kfb_pawn_sacrifice, ('game', 'card', 'choice', 'ok', 'options', 'player', 'remaining_targets', 't', 'targets', 'victim'), (), (), {0: 161, 1: 167, 2: 172, 3: 180, 4: 183, 5: 179, 6: 183, 7: 189}),
    ('relentless_whispers', 192, _kfr_relentless_whispers, _kfb_relentless_whispers, ('game', 'card', 'choice', 'destroyed', 'player', 'target', 'targets'), (), (), {0: 192, 1: 198, 2: 204}),
    ('silvertooth_play', 209, _kfr_silvertooth_play, _kfb_silvertooth_play, ('game', 'card'), (), (), {0: 209, 1: 212}),
    ('subtle_maul', 215, _kfr_subtle_maul, _kfb_subtle_maul, ('game', 'card'), (), (), {0: 215, 1: 216}),
    ('too_much_to_protect', 219, _kfr_too_much_to_protect, _kfb_too_much_to_protect, ('game', 'card', 'amount', 'opponent'), (), (), {0: 219, 1: 226}),
    ('urchin_play', 229, _kfr_urchin_play, _kfb_urchin_play, ('game', 'card'), (), (), {0: 229, 1: 232}),
    ('bad_penny_destroyed', 235, _kfr_bad_penny_destroyed, _kfb_bad_penny_destroyed, ('game', 'card'), (), (), {0: 235, 1: 238}),
    ('finishing_blow', 243, _kfr_finishing_blow, _kfb_finishing_blow, ('game', 'card', 'choice', 'destroyed', 'player', 'targets'), (), (), {0: 243, 1: 249, 2: 253}),
    ('imperial_traitor', 258, _kfr_imperial_traitor, _kfb_imperial_traitor, ('game', 'card', 'choice', 'opponent', 'player', 'targets'), (), (), {0: 258, 1: 266}),
    ('key_of_darkness', 274, _kfr_key_of_darkness, _kfb_key_of_darkness, ('game', 'card', 'modifier', 'opponent'), (), (), {0: 274, 1: 277}),
    ('poison_wave', 280, _kfr_poison_wave, _kfb_poison_wave, ('game', 'card', 'c', 'targets'), (), (), {0: 280, 1: 287}),
    ('routine_job', 290, _kfr_routine_job, _kfb_routine_job, ('game', 'card', 'copies_in_discard', 'opponent', 'player'), (), (), {0: 290, 1: 296}),
    ('treasure_map', 299, _kfr_treasure_map, _kfb_treasure_map, ('game', 'card', 'player'), (), (), {0: 299, 1: 311}),
    ('_evasion_sigil_handler', 323, _kfr__evasion_sigil_handler, _kfb__evasion_sigil_handler, ('game', 'event', 'attacker', 'controller', 'top'), (), (), {0: 323, 1: 334}),
    ('longfused_mines', 337, _kfr_longfused_mines, _kfb_longfused_mines, ('game', 'card', 'c', 'opponent', 'targets'), (), (), {0: 337, 1: 339, 2: 346}),
    ('masterplan_play', 349, _kfr_masterplan_play, _kfb_masterplan_play, ('game', 'card', 'c', 'choice', 'options', 'player'), (), (), {0: 349, 1: 355}),
    ('masterplan_omni', 369, _kfr_masterplan_omni, _kfb_masterplan_omni, ('game', 'card', 'ok', 'player', 'to_play'), (), (), {0: 369, 1: 372, 2: 374, 3: 371, 4: 375, 5: 379}),
    ('seeker_needle', 382, _kfr_seeker_needle, _kfb_seeker_needle, ('game', 'card', 'choice', 'destroyed', 'player', 'target', 'targets'), (), (), {0: 382, 1: 388, 2: 394}),
    ('skeleton_key', 402, _kfr_skeleton_key, _kfb_skeleton_key, ('game', 'card', 'choice', 'player', 'targets'), (), (), {0: 402, 1: 408}),
    ('special_delivery', 415, _kfr_special_delivery, _kfb_special_delivery, ('game', 'card', 'choice', 'destroyed', 'player', 'target', 'targets'), (), (), {0: 415, 1: 417, 2: 422, 3: 428}),
    ('the_sting_action', 442, _kfr_the_sting_action, _kfb_the_sting_action, ('game', 'card'), (), (), {0: 442, 1: 443}),
    ('bulleteye', 446, _kfr_bulleteye, _kfb_bulleteye, ('game', 'card', 'choice', 'player', 'targets'), (), (), {0: 446, 1: 452, 2: 456}),
    ('_carlo_phantom_handler.<locals>.handler', 464, _kfr__carlo_phantom_handler__handler, _kfb__carlo_phantom_handler__handler, ('game', 'event', '_kfc_carlo_card'), ((2, 'carlo_card'),), (), {0: 464, 1: 468}),
    ('deipno_spymaster', 472, _kfr_deipno_spymaster, _kfb_deipno_spymaster, ('game', 'card', 'choice', 'may_use', 'options', 'player', 'target'), (), (), {0: 472, 1: 478, 2: 486, 3: 491, 4: 490, 5: 490, 6: 491}),
    ('faygin', 494, _kfr_faygin, _kfb_faygin, ('game', 'card', 'choice', 'in_play', 'options', 'player', 'target'), (), (), {0: 494, 1: 506}),
    ('magda_the_rat_play', 519, _kfr_magda_the_rat_play, _kfb_magda_the_rat_play, ('game', 'card'), (), (), {0: 519, 1: 522}),
    ('nexus', 529, _kfr_nexus, _kfb_nexus, ('game', 'card', 'choice', 'opponent', 'player', 'targets'), (), (), {0: 529, 1: 539, 2: 543}),
    ('selwyn_the_fence', 546, _kfr_selwyn_the_fence, _kfb_selwyn_the_fence, ('game', 'card', 'choice', 'player', 'source_card', 'sources'), (), (), {0: 546, 1: 552}),
    ('smiling_ruth', 582, _kfr_smiling_ruth, _kfb_smiling_ruth, ('game', 'card', 'choice', 'opponent', 'player', 'targets'), (), (), {0: 582, 1: 592, 2: 596}),
    ('sneklifter', 599, _kfr_sneklifter, _kfb_sneklifter, ('game', 'card', 'choice', 'opponent', 'player', 'target', 'targets'), (), (), {0: 599, 1: 606, 2: 611}),
    ('_silent_dagger_effect', 628, _kfr__silent_dagger_effect, _kfb__silent_dagger_effect, ('game', 'host_card', 'choice', 'targets'), (), (), {0: 628, 1: 633, 2: 638}),
]
