"""Generated by tools/compile_engine.py from keyforge/effects/named/dis.py -- do not edit.

Each pausing function of the source, as a routine for keyforge/vm.py's Machine:
`_kfr_*` runs it from a frame's pc, `_kfb_*` binds a call into a frame's locals.
"""

# fmt: off
# flake8: noqa
SOURCE = 'keyforge/effects/named/dis.py'
SOURCE_SHA256 = '5d13ef8824372c4ce869cf37081534e5eb66a9af181396cb109c3d62ab72cdff'

# Placeholder defaults: the loader rebuilds every function here in the source module's globals,
# with the original function's own defaults.
_kf_U = None


def _kfr_arise(F, _sent, _kfN):
    # effects/named/dis.py:11 arise
    (game, card, before, c, chosen, creatures, houses, player,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 11
            player = controller_of(game, card)
            houses = game.player_houses(player.id)
            _kff = game.choose_house
            _kfa = (player.id, 'Arise: choose one of your houses', houses,)
            _kfk = None
            F.L = [game, card, before, c, chosen, creatures, houses, player]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 14
            chosen = _sent
            creatures = [c for c in player.discard.cards() if c.house == chosen and c.type == CardType.CREATURE]
            for c in creatures:
                player.discard.remove(c)
                player.hand.add(c)
            if not creatures:
                steps.shortfall(game, card, f'returns no creatures: {{pos:{player.id}}} discard pile has no {chosen.value} creatures (the chain is still gained)', 'No creatures to return')
            before = player.chains
            player.chains = min(24, player.chains + 1)
            game.log.add('gain_chains', player=player.id, n=player.chains - before, total=player.chains, card=card.name, iid=card.instance_id)
            game.log.add('arise', player=player.id, house=chosen.value, n=len(creatures), iids=[c.instance_id for c in creatures])
            return (3, None)

def _kfb_arise(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U, _kf_U, _kf_U, _kf_U]


def _kfr_control_the_weak(F, _sent, _kfN):
    # effects/named/dis.py:27 control_the_weak
    (game, card, chosen, houses, opponent,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 27
            opponent = opponent_of(game, card)
            houses = game.player_houses(opponent.id)
            _kff = game.choose_house
            _kfa = (card.controller, "Control the Weak: choose the enemy's house", houses,)
            _kfk = None
            F.L = [game, card, chosen, houses, opponent]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 30
            chosen = _sent
            game.active_effects.add(DurationEffect(card, card.controller, 2, opponent.id, 'HouseSelection', '=', chosen))
            return (3, None)

def _kfb_control_the_weak(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U]


def _kfr_creeping_oblivion(F, _sent, _kfN):
    # effects/named/dis.py:36 creeping_oblivion
    (game, card, c, choice, n_max, options, pile_choice, piles, player_id, target_player,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 36
            player_id = card.controller
            piles = []
            if game.players[1].discard.cards():
                piles.append(1)
            if game.players[2].discard.cards():
                piles.append(2)
            if not piles:
                steps.shortfall(game, card, 'purges nothing: both discard piles are empty', 'Nothing to purge')
                return (3, None)
            _kff = game.choose_cards
            _kfa = (player_id, 'Choose a discard pile', piles, 1, 1,)
            _kfk = {'source_card': card, 'intent': DecisionIntent.PURGE, 'affects': Affects.NONE}
            F.L = [game, card, c, choice, n_max, options, pile_choice, piles, player_id, target_player]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 46
            pile_choice = _sent
            target_player = game.players[pile_choice[0]]
            options = target_player.discard.cards()
            n_max = min(2, len(options))
            _kff = game.choose_cards
            _kfa = (player_id, 'Purge 0-2 cards from that discard pile', options, 0, n_max,)
            _kfk = {'source_card': card, 'intent': DecisionIntent.PURGE, 'affects': Affects.ANY, 'optional': True}
            F.L = [game, card, c, choice, n_max, options, pile_choice, piles, player_id, target_player]
            F.pc = 2
            return (1, _kff, _kfa, _kfk)
        elif _pc == 2:  # line 53
            choice = _sent
            for c in choice:
                steps.purge(game, c)
            return (3, None)

def _kfb_creeping_oblivion(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U, _kf_U, _kf_U, _kf_U, _kf_U, _kf_U]


def _kfr_dominator_bauble(F, _sent, _kfN):
    # effects/named/dis.py:61 dominator_bauble
    (game, card, choice, options, player,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 61
            player = controller_of(game, card)
            options = [c for c in player.play_area.creatures if not c.Exhausted and game._rule_of_six_ok(player, c.name)]
            if not options:
                if player.play_area.creatures:
                    steps.shortfall(game, card, 'does nothing: every friendly creature is exhausted (or already used 6 times this turn)', 'No ready creature')
                else:
                    steps.shortfall(game, card, 'does nothing: there are no friendly creatures in play', 'No creature to use')
                return (3, None)
            _kff = game.choose_cards
            _kfa = (player.id, 'Choose a friendly creature to use', options, 1, 1,)
            _kfk = {'source_card': card, 'intent': DecisionIntent.USE_TARGET, 'affects': Affects.FRIENDLY}
            F.L = [game, card, choice, options, player]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 75
            choice = _sent
            _kff = steps.use_creature
            _kfa = (game, choice[0],)
            _kfk = None
            F.L = [game, card, choice, options, player]
            F.pc = 2
            return (1, _kff, _kfa, _kfk)
        elif _pc == 2:  # line 79
            return (3, None)

def _kfb_dominator_bauble(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U]


def _kfr_dust_imp_destroyed(F, _sent, _kfN):
    # effects/named/dis.py:82 dust_imp_destroyed
    (game, card,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 82
            steps.gain(game, game.players[card.controller], 2)
            return (3, None)
            _kfd = None
            F.L = [game, card]
            F.pc = 1
            return (2, _kfd)
        elif _pc == 1:  # line 88
            return (3, None)

def _kfb_dust_imp_destroyed(game, card):
    return [game, card]


def _kfr_gateway_to_dis(F, _sent, _kfN):
    # effects/named/dis.py:105 gateway_to_dis
    (game, card, before, player, targets,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 105
            player = controller_of(game, card)
            targets = game.all_creatures('any', card)
            _kff = game.destroy_cards
            _kfa = (targets,)
            _kfk = None
            F.L = [game, card, before, player, targets]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 108
            before = player.chains
            player.chains = min(24, player.chains + 3)
            game.log.add('gain_chains', player=player.id, n=player.chains - before, total=player.chains, card=card.name, iid=card.instance_id)
            return (3, None)

def _kfb_gateway_to_dis(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U]


def _kfr_guardian_demon(F, _sent, _kfN):
    # effects/named/dis.py:114 guardian_demon
    (game, card, creatures, damage_targets, dmg_choice, heal_choice, healed, options, player,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 114
            player = controller_of(game, card)
            creatures = game.all_creatures('any', card)
            options = [c for c in creatures if c.type_object.damage > 0]
            if not options:
                steps.shortfall(game, card, 'heals nothing and deals no damage: no creature is damaged', 'No damage to heal')
                return (3, None)
            _kff = game.choose_cards
            _kfa = (player.id, 'Guardian Demon: heal up to 2 from a creature', options, 1, 1,)
            _kfk = {'source_card': card, 'intent': DecisionIntent.HEAL, 'affects': Affects.ANY}
            F.L = [game, card, creatures, damage_targets, dmg_choice, heal_choice, healed, options, player]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 123
            heal_choice = _sent
            healed = steps.heal(game, heal_choice[0], 2)
            if healed <= 0:
                return (3, None)
            damage_targets = [c for c in creatures if c is not heal_choice[0]]
            if not damage_targets:
                steps.shortfall(game, card, f'heals {healed} but deals no damage: there is no other creature in play', 'No creature to damage')
                return (3, None)
            _kff = game.choose_cards
            _kfa = (player.id, f'Deal {healed} damage to another creature', damage_targets, 1, 1,)
            _kfk = {'source_card': card, 'intent': DecisionIntent.DAMAGE, 'affects': Affects.ANY}
            F.L = [game, card, creatures, damage_targets, dmg_choice, heal_choice, healed, options, player]
            F.pc = 2
            return (1, _kff, _kfa, _kfk)
        elif _pc == 2:  # line 135
            dmg_choice = _sent
            steps.deal_damage(game, dmg_choice[0], healed)
            _kff = game.check_destroyed
            _kfa = (dmg_choice,)
            _kfk = None
            F.L = [game, card, creatures, damage_targets, dmg_choice, heal_choice, healed, options, player]
            F.pc = 3
            return (1, _kff, _kfa, _kfk)
        elif _pc == 3:  # line 140
            return (3, None)

def _kfb_guardian_demon(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U, _kf_U, _kf_U, _kf_U, _kf_U]


def _kfr_lifeward_omni(F, _sent, _kfN):
    # effects/named/dis.py:143 lifeward_omni
    (game, card,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 143
            _kff = steps.sacrifice
            _kfa = (game, card,)
            _kfk = None
            F.L = [game, card]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 144
            game.active_effects.add(DurationEffect(card, card.controller, 2, 3 - card.controller, 'CanPlayCreatures', '=', False))
            return (3, None)

def _kfb_lifeward_omni(game, card):
    return [game, card]


def _kfr_shooler_play(F, _sent, _kfN):
    # effects/named/dis.py:150 shooler_play
    (game, card, opponent,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 150
            opponent = opponent_of(game, card)
            if opponent.aember >= 4:
                steps.steal(game, opponent, controller_of(game, card), 1, source=card)
            else:
                steps.shortfall(game, card, f'steals nothing: {{pos:{opponent.id}}} Æmber is {opponent.aember}, and it needs 4 or more', 'Needs 4+ enemy Æmber')
            return (3, None)
            _kfd = None
            F.L = [game, card, opponent]
            F.pc = 1
            return (2, _kfd)
        elif _pc == 1:  # line 157
            return (3, None)

def _kfb_shooler_play(game, card):
    return [game, card, _kf_U]


def _kfr_snudge(F, _sent, _kfN):
    # effects/named/dis.py:160 snudge
    (game, card, artifacts, choice, flank_creatures, options, player,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 160
            player = controller_of(game, card)
            artifacts = game.players[1].play_area.artifacts + game.players[2].play_area.artifacts
            flank_creatures = [c for pid in (1, 2) for c in game.players[pid].play_area.creatures if game.players[pid].play_area.is_flank(c)]
            options = artifacts + flank_creatures
            if not options:
                steps.shortfall(game, card, 'returns nothing: there are no artifacts or flank creatures in play', 'Nothing to return')
                return (3, None)
            _kff = game.choose_cards
            _kfa = (player.id, 'Snudge: return an artifact or a flank creature', options, 1, 1,)
            _kfk = {'source_card': card, 'intent': DecisionIntent.RETURN_TO_HAND, 'affects': Affects.ANY}
            F.L = [game, card, artifacts, choice, flank_creatures, options, player]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 173
            choice = _sent
            steps.return_to_hand(game, choice[0])
            return (3, None)

def _kfb_snudge(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U, _kf_U, _kf_U]


def _kfr_the_terror_play(F, _sent, _kfN):
    # effects/named/dis.py:185 the_terror_play
    (game, card, opponent,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 185
            opponent = opponent_of(game, card)
            if opponent.aember == 0:
                steps.gain(game, controller_of(game, card), 2)
            else:
                steps.shortfall(game, card, f'gains nothing: {{pos:{opponent.id}}} Æmber is {opponent.aember}, and it pays out only at 0', 'Enemy has Æmber')
            return (3, None)
            _kfd = None
            F.L = [game, card, opponent]
            F.pc = 1
            return (2, _kfd)
        elif _pc == 1:  # line 192
            return (3, None)

def _kfb_the_terror_play(game, card):
    return [game, card, _kf_U]


def _kfr_three_fates(F, _sent, _kfN):
    # effects/named/dis.py:195 three_fates
    (game, card, c, chosen, max_power, picked, remaining, slots, targets, tied,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 195
            targets = game.all_creatures('any', card)
            if not targets:
                steps.shortfall(game, card, 'destroys nothing: there are no creatures in play', 'No creatures')
                return (3, None)
            if len(targets) < 3:
                steps.shortfall(game, card, f'destroys only {len(targets)}: that is every creature in play', f'Only {len(targets)} in play')
            remaining = list(targets)
            chosen = []
            _pc = 1
            continue
        elif _pc == 1:  # line 204
            _pc = 2 if remaining and len(chosen) < 3 else 3
            continue
        elif _pc == 2:  # line 205
            slots = 3 - len(chosen)
            max_power = max((game.get_power(c) for c in remaining))
            tied = [c for c in remaining if game.get_power(c) == max_power]
            _pc = 4 if len(tied) > slots else 5
            continue
        elif _pc == 3:  # line 204
            _kff = game.destroy_cards
            _kfa = (chosen,)
            _kfk = None
            F.L = [game, card, c, chosen, max_power, picked, remaining, slots, targets, tied]
            F.pc = 8
            return (1, _kff, _kfa, _kfk)
        elif _pc == 4:  # line 211
            _kff = game.choose_cards
            _kfa = (card.controller, f'Three Fates: choose {slots} of the tied creatures to destroy', tied, slots, slots,)
            _kfk = {'source_card': card, 'intent': DecisionIntent.DESTROY, 'affects': Affects.ANY}
            F.L = [game, card, c, chosen, max_power, picked, remaining, slots, targets, tied]
            F.pc = 7
            return (1, _kff, _kfa, _kfk)
        elif _pc == 5:  # line 216
            picked = tied
            _pc = 6
            continue
        elif _pc == 6:  # line 208
            for c in picked:
                chosen.append(c)
                remaining.remove(c)
            _pc = 1
            continue
        elif _pc == 7:  # line 211
            picked = _sent
            _pc = 6
            continue
        elif _pc == 8:  # line 220
            return (3, None)

def _kfb_three_fates(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U, _kf_U, _kf_U, _kf_U, _kf_U, _kf_U]


def _kfr_a_fair_game(F, _sent, _kfN):
    # effects/named/dis.py:225 a_fair_game
    (game, card,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 225
            _fair_game_step(game, card, controller_of(game, card), opponent_of(game, card))
            _fair_game_step(game, card, opponent_of(game, card), controller_of(game, card))
            return (3, None)
            _kfd = None
            F.L = [game, card]
            F.pc = 1
            return (2, _kfd)
        elif _pc == 1:  # line 229
            return (3, None)

def _kfb_a_fair_game(game, card):
    return [game, card]


def _kfr_dance_of_doom(F, _sent, _kfN):
    # effects/named/dis.py:244 dance_of_doom
    (game, card, chosen, creatures, powers, targets,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 244
            creatures = game.all_creatures('any', card)
            if not creatures:
                steps.shortfall(game, card, 'destroys nothing: there are no creatures in play', 'No creatures')
                return (3, None)
            powers = sorted({game.get_power(c) for c in creatures})
            _kff = game.choose_number
            _kfa = (card.controller, 'Dance of Doom: choose a number', powers,)
            _kfk = {'source_card': card}
            F.L = [game, card, chosen, creatures, powers, targets]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 250
            chosen = _sent
            targets = [c for c in creatures if game.get_power(c) == chosen]
            _kff = game.destroy_cards
            _kfa = (targets,)
            _kfk = None
            F.L = [game, card, chosen, creatures, powers, targets]
            F.pc = 2
            return (1, _kff, _kfa, _kfk)
        elif _pc == 2:  # line 252
            return (3, None)

def _kfb_dance_of_doom(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U, _kf_U]


def _kfr_fear(F, _sent, _kfN):
    # effects/named/dis.py:255 fear
    (game, card, choice, targets,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 255
            targets = game.all_creatures('enemy', card)
            if not targets:
                steps.shortfall(game, card, 'returns nothing: there are no enemy creatures in play', 'No enemy creatures')
                return (3, None)
            _kff = game.choose_cards
            _kfa = (card.controller, 'Fear: return an enemy creature to hand', targets, 1, 1,)
            _kfk = {'source_card': card, 'intent': DecisionIntent.RETURN_TO_HAND, 'affects': Affects.ENEMY}
            F.L = [game, card, choice, targets]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 260
            choice = _sent
            steps.return_to_hand(game, choice[0])
            return (3, None)

def _kfb_fear(game, card):
    return [game, card, _kf_U, _kf_U]


def _kfr_gongoozle(F, _sent, _kfN):
    # effects/named/dis.py:267 gongoozle
    (game, card, choice, destroyed, target, targets,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 267
            targets = game.all_creatures('any', card)
            if not targets:
                steps.shortfall(game, card, 'deals no damage: there are no creatures in play', 'No creature to damage')
                return (3, None)
            _kff = game.choose_cards
            _kfa = (card.controller, 'Gongoozle: deal 3 damage', targets, 1, 1,)
            _kfk = {'source_card': card, 'intent': DecisionIntent.DAMAGE, 'affects': Affects.ANY}
            F.L = [game, card, choice, destroyed, target, targets]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 272
            choice = _sent
            target = choice[0]
            steps.deal_damage(game, target, 3)
            _kff = game.check_destroyed
            _kfa = ([target],)
            _kfk = None
            F.L = [game, card, choice, destroyed, target, targets]
            F.pc = 2
            return (1, _kff, _kfa, _kfk)
        elif _pc == 2:  # line 278
            destroyed = _sent
            _pc = 3 if target not in destroyed else 4
            continue
        elif _pc == 3:  # line 280
            _kff = steps.discard_random
            _kfa = (game, game.players[target.owner],)
            _kfk = {'source': card}
            F.L = [game, card, choice, destroyed, target, targets]
            F.pc = 6
            return (1, _kff, _kfa, _kfk)
        elif _pc == 4:  # line 279
            _pc = 5
            continue
        elif _pc == 5:  # line 279
            return (3, None)
        elif _pc == 6:  # line 280
            _pc = 5
            continue

def _kfb_gongoozle(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U, _kf_U]


def _kfr_guilty_hearts(F, _sent, _kfN):
    # effects/named/dis.py:283 guilty_hearts
    (game, card, targets,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 283
            targets = [c for c in game.all_creatures('any', card) if c.aember_captured > 0]
            if not targets:
                steps.shortfall(game, card, 'destroys nothing: no creature has any Æmber on it', 'No creature with Æmber')
                return (3, None)
            _kff = game.destroy_cards
            _kfa = (targets,)
            _kfk = None
            F.L = [game, card, targets]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 288
            return (3, None)

def _kfb_guilty_hearts(game, card):
    return [game, card, _kf_U]


def _kfr_hand_of_dis(F, _sent, _kfN):
    # effects/named/dis.py:291 hand_of_dis
    (game, card, choice, targets,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 291
            targets = [c for c in game.all_creatures('any', card) if not game.players[c.controller].play_area.is_flank(c)]
            if not targets:
                steps.shortfall(game, card, 'destroys nothing: every creature in play is on a flank', 'No non-flank creature')
                return (3, None)
            _kff = game.choose_cards
            _kfa = (card.controller, 'Hand of Dis: destroy a creature not on a flank', targets, 1, 1,)
            _kfk = {'source_card': card, 'intent': DecisionIntent.DESTROY, 'affects': Affects.ANY}
            F.L = [game, card, choice, targets]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 296
            choice = _sent
            _kff = game.destroy_cards
            _kfa = (choice,)
            _kfk = None
            F.L = [game, card, choice, targets]
            F.pc = 2
            return (1, _kff, _kfa, _kfk)
        elif _pc == 2:  # line 300
            return (3, None)

def _kfb_hand_of_dis(game, card):
    return [game, card, _kf_U, _kf_U]


def _kfr_hecatomb(F, _sent, _kfN):
    # effects/named/dis.py:303 hecatomb
    (game, card, c, counts, n, pid, targets,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 303
            targets = [c for c in game.all_creatures('any', card) if c.house == House.DIS]
            if not targets:
                steps.shortfall(game, card, 'destroys nothing: there are no Dis creatures in play', 'No Dis creatures')
                return (3, None)
            counts = {1: 0, 2: 0}
            for c in targets:
                counts[c.controller] += 1
            _kff = game.destroy_cards
            _kfa = (targets,)
            _kfk = None
            F.L = [game, card, c, counts, n, pid, targets]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 311
            for pid, n in counts.items():
                steps.gain(game, game.players[pid], n)
            return (3, None)

def _kfb_hecatomb(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U, _kf_U, _kf_U]


def _kfr_tendrils_of_pain(F, _sent, _kfN):
    # effects/named/dis.py:316 tendrils_of_pain
    (game, card, amount, c, opponent, targets,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 316
            opponent = opponent_of(game, card)
            amount = 4 if game.forged_key_on_turn(opponent.id, game.turn_number - 1) else 1
            targets = game.all_creatures('any', card)
            if not targets:
                steps.shortfall(game, card, 'deals no damage: there are no creatures in play', 'No creatures')
                return (3, None)
            for c in targets:
                steps.deal_damage(game, c, amount)
            _kff = game.check_destroyed
            _kfa = (targets,)
            _kfk = None
            F.L = [game, card, amount, c, opponent, targets]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 325
            return (3, None)

def _kfb_tendrils_of_pain(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U, _kf_U]


def _kfr_hysteria(F, _sent, _kfN):
    # effects/named/dis.py:328 hysteria
    (game, card, c, targets,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 328
            targets = game.all_creatures('any', card)
            if not targets:
                steps.shortfall(game, card, 'returns nothing: there are no creatures in play', 'No creatures')
                return (3, None)
            for c in list(targets):
                steps.return_to_hand(game, c)
            return (3, None)
            _kfd = None
            F.L = [game, card, c, targets]
            F.pc = 1
            return (2, _kfd)
        elif _pc == 1:  # line 336
            return (3, None)

def _kfb_hysteria(game, card):
    return [game, card, _kf_U, _kf_U]


def _kfr_key_hammer(F, _sent, _kfN):
    # effects/named/dis.py:339 key_hammer
    (game, card, opponent,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 339
            opponent = opponent_of(game, card)
            if game.forged_key_on_turn(opponent.id, game.turn_number - 1):
                opponent.keys = max(0, opponent.keys - 1)
                game.log.add('unforge', player=opponent.id, keys=opponent.keys, card=card.name, iid=card.instance_id)
            else:
                steps.shortfall(game, card, f'unforges nothing: {{pos:{opponent.id}}} did not forge a key on their previous turn', 'No key forged last turn')
            steps.gain(game, opponent, 6)
            return (3, None)
            _kfd = None
            F.L = [game, card, opponent]
            F.pc = 1
            return (2, _kfd)
        elif _pc == 1:  # line 348
            return (3, None)

def _kfb_key_hammer(game, card):
    return [game, card, _kf_U]


def _kfr_mind_barb(F, _sent, _kfN):
    # effects/named/dis.py:351 mind_barb
    (game, card,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 351
            _kff = steps.discard_random
            _kfa = (game, opponent_of(game, card),)
            _kfk = {'source': card}
            F.L = [game, card]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 352
            return (3, None)

def _kfb_mind_barb(game, card):
    return [game, card]


def _kfr_pandemonium(F, _sent, _kfN):
    # effects/named/dis.py:355 pandemonium
    (game, card, c, targets,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 355
            targets = [c for c in game.all_creatures('any', card) if c.type_object.damage == 0]
            if not targets:
                steps.shortfall(game, card, 'captures nothing: every creature in play is damaged', 'No undamaged creature')
                return (3, None)
            for c in targets:
                steps.capture(game, c, 1)
            return (3, None)
            _kfd = None
            F.L = [game, card, c, targets]
            F.pc = 1
            return (2, _kfd)
        elif _pc == 1:  # line 363
            return (3, None)

def _kfb_pandemonium(game, card):
    return [game, card, _kf_U, _kf_U]


def _kfr_poltergeist(F, _sent, _kfN):
    # effects/named/dis.py:366 poltergeist
    (game, card, choice, target, targets,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 366
            targets = [a for a in list(game.players[1].play_area.artifacts) + list(game.players[2].play_area.artifacts) if (a.card_def.on_action is not None or a.card_def.on_omni is not None) and (not a.Exhausted)]
            if not targets:
                steps.shortfall(game, card, 'uses nothing: there is no usable artifact in play', 'No usable artifact')
                return (3, None)
            _kff = game.choose_cards
            _kfa = (card.controller, 'Poltergeist: use an artifact as if it were yours', targets, 1, 1,)
            _kfk = {'source_card': card, 'intent': DecisionIntent.USE_TARGET, 'affects': Affects.ANY}
            F.L = [game, card, choice, target, targets]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 374
            choice = _sent
            target = choice[0]
            _kff = game.use_artifact_ability
            _kfa = (target, card.controller,)
            _kfk = None
            F.L = [game, card, choice, target, targets]
            F.pc = 2
            return (1, _kff, _kfa, _kfk)
        elif _pc == 2:  # line 379
            _kff = game.destroy_cards
            _kfa = ([target],)
            _kfk = None
            F.L = [game, card, choice, target, targets]
            F.pc = 3
            return (1, _kff, _kfa, _kfk)
        elif _pc == 3:  # line 380
            return (3, None)

def _kfb_poltergeist(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U]


def _kfr_red_hot_armor(F, _sent, _kfN):
    # effects/named/dis.py:390 red_hot_armor
    (game, card, c, lost, opponent, targets,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 390
            opponent = opponent_of(game, card)
            targets = [c for c in opponent.play_area.creatures if game.get_armor(c) > 0]
            if not targets:
                steps.shortfall(game, card, 'destroys nothing: no enemy creature has any armor', 'No armored enemy creature')
                return (3, None)
            for c in targets:
                lost = game.get_armor(c)
                c.armor_negated = True
                game._end_of_turn_cleanups.append(('dis.clear_armor_negated', c.instance_id))
                steps.deal_damage(game, c, lost)
            _kff = game.check_destroyed
            _kfa = (targets,)
            _kfk = None
            F.L = [game, card, c, lost, opponent, targets]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 401
            return (3, None)

def _kfb_red_hot_armor(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U, _kf_U]


def _kfr_key_to_dis(F, _sent, _kfN):
    # effects/named/dis.py:408 key_to_dis
    (game, card, targets,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 408
            _kff = steps.sacrifice
            _kfa = (game, card,)
            _kfk = None
            F.L = [game, card, targets]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 409
            targets = game.all_creatures('any', card)
            _kff = game.destroy_cards
            _kfa = (targets,)
            _kfk = None
            F.L = [game, card, targets]
            F.pc = 2
            return (1, _kff, _kfa, _kfk)
        elif _pc == 2:  # line 411
            return (3, None)

def _kfb_key_to_dis(game, card):
    return [game, card, _kf_U]


def _kfr_sacrificial_altar(F, _sent, _kfN):
    # effects/named/dis.py:414 sacrificial_altar
    (game, card, choice, choice2, discard_creatures, ok, options, player, to_play, victim,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 414
            player = controller_of(game, card)
            options = [c for c in player.play_area.creatures if 'Human' in c.tags]
            if not options:
                steps.shortfall(game, card, 'purges nothing: there is no friendly Human creature in play', 'No Human creature')
                return (3, None)
            _kff = game.choose_cards
            _kfa = (player.id, 'Sacrificial Altar: purge a friendly Human creature', options, 1, 1,)
            _kfk = {'source_card': card, 'intent': DecisionIntent.PURGE, 'affects': Affects.FRIENDLY}
            F.L = [game, card, choice, choice2, discard_creatures, ok, options, player, to_play, victim]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 420
            choice = _sent
            victim = choice[0]
            if not steps.purge(game, victim):
                return (3, None)
            discard_creatures = [c for c in player.discard.cards() if c.type == CardType.CREATURE]
            if not discard_creatures:
                steps.shortfall(game, card, f'purges {victim.name} but plays nothing: your discard pile has no creature', 'No creature in discard')
                return (3, None)
            _kff = game.choose_cards
            _kfa = (player.id, 'Sacrificial Altar: play a creature from your discard pile', discard_creatures, 1, 1,)
            _kfk = {'source_card': card, 'intent': DecisionIntent.PLAY, 'affects': Affects.FRIENDLY}
            F.L = [game, card, choice, choice2, discard_creatures, ok, options, player, to_play, victim]
            F.pc = 2
            return (1, _kff, _kfa, _kfk)
        elif _pc == 2:  # line 431
            choice2 = _sent
            to_play = choice2[0]
            player.discard.remove(to_play)
            _kff = game._play_card
            _kfa = (player.id, to_play,)
            _kfk = {'from_deck_top': True}
            F.L = [game, card, choice, choice2, discard_creatures, ok, options, player, to_play, victim]
            F.pc = 3
            return (1, _kff, _kfa, _kfk)
        elif _pc == 3:  # line 437
            ok = _sent
            if not ok:
                player.discard.push(to_play)
                steps.shortfall(game, card, f"can't play {to_play.name} from the discard pile right now; it stays there", f"Can't play {to_play.name}")
            return (3, None)

def _kfb_sacrificial_altar(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U, _kf_U, _kf_U, _kf_U, _kf_U, _kf_U]


def _kfr_screaming_cave(F, _sent, _kfN):
    # effects/named/dis.py:443 screaming_cave
    (game, card, cards, player,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 443
            player = controller_of(game, card)
            cards = player.hand.take_all() + player.discard.take_all()
            if not cards:
                steps.shortfall(game, card, 'shuffles nothing: your hand and discard pile are both empty', 'Nothing to shuffle')
                return (3, None)
            player.deck.shuffle_in(cards, game.event_rng('reshuffle', player.id))
            game.log.add('reshuffle', player=player.id)
            return (3, None)
            _kfd = None
            F.L = [game, card, cards, player]
            F.pc = 1
            return (2, _kfd)
        elif _pc == 1:  # line 452
            return (3, None)

def _kfb_screaming_cave(game, card):
    return [game, card, _kf_U, _kf_U]


def _kfr_soul_snatcher_trigger(F, _sent, _kfN):
    # effects/named/dis.py:459 soul_snatcher_trigger
    (game, event, destroyed_card,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 459
            destroyed_card = event['card']
            steps.gain(game, game.players[destroyed_card.owner], 1)
            return (3, None)
            _kfd = None
            F.L = [game, event, destroyed_card]
            F.pc = 1
            return (2, _kfd)
        elif _pc == 1:  # line 463
            return (3, None)

def _kfb_soul_snatcher_trigger(game, event):
    return [game, event, _kf_U]


def _kfr_drumble_play(F, _sent, _kfN):
    # effects/named/dis.py:466 drumble_play
    (game, card, opponent,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 466
            opponent = opponent_of(game, card)
            if opponent.aember >= 7:
                steps.capture(game, card, opponent.aember)
            else:
                steps.shortfall(game, card, f'captures nothing: {{pos:{opponent.id}}} Æmber is {opponent.aember}, and it needs 7 or more', 'Needs 7+ enemy Æmber')
            return (3, None)
            _kfd = None
            F.L = [game, card, opponent]
            F.pc = 1
            return (2, _kfd)
        elif _pc == 1:  # line 473
            return (3, None)

def _kfb_drumble_play(game, card):
    return [game, card, _kf_U]


def _kfr_eater_of_the_dead(F, _sent, _kfN):
    # effects/named/dis.py:476 eater_of_the_dead
    (game, card, choice, options, player,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 476
            player = controller_of(game, card)
            options = [c for c in list(game.players[1].discard.cards()) + list(game.players[2].discard.cards()) if c.type == CardType.CREATURE]
            if not options:
                steps.shortfall(game, card, 'purges nothing: neither discard pile has a creature', 'No creature in either discard pile')
                return (3, None)
            _kff = game.choose_cards
            _kfa = (player.id, 'Eater of the Dead: purge a creature from a discard pile', options, 1, 1,)
            _kfk = {'source_card': card, 'intent': DecisionIntent.PURGE, 'affects': Affects.ANY}
            F.L = [game, card, choice, options, player]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 482
            choice = _sent
            if steps.purge(game, choice[0]):
                card.power_counters += 1
                game.log.add('power_counter', card=card.name, iid=card.instance_id, amount=1, total=card.power_counters)
            return (3, None)

def _kfb_eater_of_the_dead(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U]


def _kfr__gabos_before_fight__handler(F, _sent, _kfN):
    # effects/named/dis.py:500 _gabos_before_fight.<locals>.handler
    (game, event, choice, targets, _kfc_gabos_card,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 500
            if event['attacker'] is not _kfc_gabos_card.cell_contents:
                return (3, None)
            targets = game.all_creatures('any', _kfc_gabos_card.cell_contents)
            if not targets:
                return (3, None)
            _kff = game.choose_cards
            _kfa = (_kfc_gabos_card.cell_contents.controller, 'Gabos Longarms: choose a creature to deal its fight damage to instead', targets, 1, 1,)
            _kfk = {'source_card': _kfc_gabos_card.cell_contents, 'intent': DecisionIntent.REDIRECT, 'affects': Affects.ANY}
            F.L = [game, event, choice, targets, _kfc_gabos_card]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 506
            choice = _sent
            _kfc_gabos_card.cell_contents.redirect_fight_damage_to = choice[0]
            return (3, None)

def _kfb__gabos_before_fight__handler(game, event):
    return [game, event, _kf_U, _kf_U, _kf_U]


def _kfr_overlord_greking_on_destroyed_fighting(F, _sent, _kfN):
    # effects/named/dis.py:514 overlord_greking_on_destroyed_fighting
    (game, survivor, victim, new_controller, owner,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 514
            owner = game.players[victim.owner]
            _pc = 1 if not owner.discard.remove(victim) or victim.type != CardType.CREATURE else 2
            continue
        elif _pc == 1:  # line 517
            return (3, None)
            _kfd = None
            F.L = [game, survivor, victim, new_controller, owner]
            F.pc = 4
            return (2, _kfd)
        elif _pc == 2:  # line 516
            _pc = 3
            continue
        elif _pc == 3:  # line 516
            new_controller = survivor.controller
            victim.reset_on_leave_play()
            game.players[new_controller].play_area.add_creature(victim, 'left')
            victim.controller = new_controller
            victim.Exhausted = True
            if victim.card_def.register_passive:
                victim.card_def.register_passive(game, victim)
            game.log.add('put_into_play', card=victim.name, iid=victim.instance_id, player=new_controller, source=survivor.name)
            return (3, None)
            _kfd = None
            F.L = [game, survivor, victim, new_controller, owner]
            F.pc = 5
            return (2, _kfd)
        elif _pc == 4:  # line 518
            _pc = 3
            continue
        elif _pc == 5:  # line 528
            return (3, None)

def _kfb_overlord_greking_on_destroyed_fighting(game, survivor, victim):
    return [game, survivor, victim, _kf_U, _kf_U]


def _kfr_stealer_of_souls_on_destroyed_fighting(F, _sent, _kfN):
    # effects/named/dis.py:531 stealer_of_souls_on_destroyed_fighting
    (game, survivor, victim, owner,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 531
            owner = game.players[victim.owner]
            if victim in owner.discard.cards():
                steps.purge(game, victim)
            steps.gain(game, game.players[survivor.controller], 1)
            return (3, None)
            _kfd = None
            F.L = [game, survivor, victim, owner]
            F.pc = 1
            return (2, _kfd)
        elif _pc == 1:  # line 544
            return (3, None)

def _kfb_stealer_of_souls_on_destroyed_fighting(game, survivor, victim):
    return [game, survivor, victim, _kf_U]


def _kfr_master_of_n__effect(F, _sent, _kfN):
    # effects/named/dis.py:548 master_of_n.<locals>.effect
    (game, card, choice, do_it, targets, _kfc_n,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 548
            targets = [c for c in game.all_creatures('any', card) if game.get_power(c) == _kfc_n.cell_contents]
            if not targets:
                steps.shortfall(game, card, f'destroys nothing: no creature in play has {_kfc_n.cell_contents} power', f'No {_kfc_n.cell_contents}-power creature')
                return (3, None)
            _kff = game.yes_no
            _kfa = (card.controller, f'{card.name}: destroy a creature with {_kfc_n.cell_contents} power?',)
            _kfk = {'source_card': card, 'intent': DecisionIntent.OPTIONAL_TRIGGER}
            F.L = [game, card, choice, do_it, targets, _kfc_n]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 553
            do_it = _sent
            if not do_it:
                return (3, None)
            _kff = game.choose_cards
            _kfa = (card.controller, f'{card.name}: choose a creature with {_kfc_n.cell_contents} power to destroy', targets, 1, 1,)
            _kfk = {'source_card': card, 'intent': DecisionIntent.DESTROY, 'affects': Affects.ANY}
            F.L = [game, card, choice, do_it, targets, _kfc_n]
            F.pc = 2
            return (1, _kff, _kfa, _kfk)
        elif _pc == 2:  # line 559
            choice = _sent
            _kff = game.destroy_cards
            _kfa = (choice,)
            _kfk = None
            F.L = [game, card, choice, do_it, targets, _kfc_n]
            F.pc = 3
            return (1, _kff, _kfa, _kfk)
        elif _pc == 3:  # line 563
            return (3, None)

def _kfb_master_of_n__effect(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U, _kf_U]


def _kfr_restringuntus(F, _sent, _kfN):
    # effects/named/dis.py:572 restringuntus
    (game, card, chosen, houses, opponent,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 572
            opponent = opponent_of(game, card)
            houses = game.player_houses(opponent.id)
            _kff = game.choose_house
            _kfa = (card.controller, 'Restringuntus: choose a house to deny your opponent', houses,)
            _kfk = None
            F.L = [game, card, chosen, houses, opponent]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 575
            chosen = _sent
            game.active_effects.add(DurationEffect(card, card.controller, INFINITE, opponent.id, 'CannotChooseHouse', 'add', chosen))
            return (3, None)

def _kfb_restringuntus(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U]


def _kfr__shaffles_handler__handler(F, _sent, _kfN):
    # effects/named/dis.py:584 _shaffles_handler.<locals>.handler
    (game, event, _kfc_shaffles_card,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 584
            if event['player'] == _kfc_shaffles_card.cell_contents.controller:
                steps.lose(game, game.players[3 - _kfc_shaffles_card.cell_contents.controller], 1)
            return (3, None)
            _kfd = None
            F.L = [game, event, _kfc_shaffles_card]
            F.pc = 1
            return (2, _kfd)
        elif _pc == 1:  # line 588
            return (3, None)

def _kfb__shaffles_handler__handler(game, event):
    return [game, event, _kf_U]


def _kfr_tocsin(F, _sent, _kfN):
    # effects/named/dis.py:592 tocsin
    (game, card,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 592
            _kff = steps.discard_random
            _kfa = (game, opponent_of(game, card),)
            _kfk = {'source': card}
            F.L = [game, card]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 593
            return (3, None)

def _kfb_tocsin(game, card):
    return [game, card]


def _kfr_tolas_trigger(F, _sent, _kfN):
    # effects/named/dis.py:600 tolas_trigger
    (game, event, destroyed_card,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 600
            destroyed_card = event['card']
            steps.gain(game, game.players[3 - destroyed_card.owner], 1)
            return (3, None)
            _kfd = None
            F.L = [game, event, destroyed_card]
            F.pc = 1
            return (2, _kfd)
        elif _pc == 1:  # line 604
            return (3, None)

def _kfb_tolas_trigger(game, event):
    return [game, event, _kf_U]


def _kfr_truebaru_destroyed(F, _sent, _kfN):
    # effects/named/dis.py:607 truebaru_destroyed
    (game, card,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 607
            steps.gain(game, game.players[card.controller], 5)
            return (3, None)
            _kfd = None
            F.L = [game, card]
            F.pc = 1
            return (2, _kfd)
        elif _pc == 1:  # line 611
            return (3, None)

def _kfb_truebaru_destroyed(game, card):
    return [game, card]


# (qualname, first line, step, binder, slots, freevar slots, nested code (name, line), line of each pc)
ROUTINES = [
    ('arise', 11, _kfr_arise, _kfb_arise, ('game', 'card', 'before', 'c', 'chosen', 'creatures', 'houses', 'player'), (), (), {0: 11, 1: 14}),
    ('control_the_weak', 27, _kfr_control_the_weak, _kfb_control_the_weak, ('game', 'card', 'chosen', 'houses', 'opponent'), (), (), {0: 27, 1: 30}),
    ('creeping_oblivion', 36, _kfr_creeping_oblivion, _kfb_creeping_oblivion, ('game', 'card', 'c', 'choice', 'n_max', 'options', 'pile_choice', 'piles', 'player_id', 'target_player'), (), (), {0: 36, 1: 46, 2: 53}),
    ('dominator_bauble', 61, _kfr_dominator_bauble, _kfb_dominator_bauble, ('game', 'card', 'choice', 'options', 'player'), (), (), {0: 61, 1: 75, 2: 79}),
    ('dust_imp_destroyed', 82, _kfr_dust_imp_destroyed, _kfb_dust_imp_destroyed, ('game', 'card'), (), (), {0: 82, 1: 88}),
    ('gateway_to_dis', 105, _kfr_gateway_to_dis, _kfb_gateway_to_dis, ('game', 'card', 'before', 'player', 'targets'), (), (), {0: 105, 1: 108}),
    ('guardian_demon', 114, _kfr_guardian_demon, _kfb_guardian_demon, ('game', 'card', 'creatures', 'damage_targets', 'dmg_choice', 'heal_choice', 'healed', 'options', 'player'), (), (), {0: 114, 1: 123, 2: 135, 3: 140}),
    ('lifeward_omni', 143, _kfr_lifeward_omni, _kfb_lifeward_omni, ('game', 'card'), (), (), {0: 143, 1: 144}),
    ('shooler_play', 150, _kfr_shooler_play, _kfb_shooler_play, ('game', 'card', 'opponent'), (), (), {0: 150, 1: 157}),
    ('snudge', 160, _kfr_snudge, _kfb_snudge, ('game', 'card', 'artifacts', 'choice', 'flank_creatures', 'options', 'player'), (), (), {0: 160, 1: 173}),
    ('the_terror_play', 185, _kfr_the_terror_play, _kfb_the_terror_play, ('game', 'card', 'opponent'), (), (), {0: 185, 1: 192}),
    ('three_fates', 195, _kfr_three_fates, _kfb_three_fates, ('game', 'card', 'c', 'chosen', 'max_power', 'picked', 'remaining', 'slots', 'targets', 'tied'), (), (), {0: 195, 1: 204, 2: 205, 3: 204, 4: 211, 5: 216, 6: 208, 7: 211, 8: 220}),
    ('a_fair_game', 225, _kfr_a_fair_game, _kfb_a_fair_game, ('game', 'card'), (), (), {0: 225, 1: 229}),
    ('dance_of_doom', 244, _kfr_dance_of_doom, _kfb_dance_of_doom, ('game', 'card', 'chosen', 'creatures', 'powers', 'targets'), (), (), {0: 244, 1: 250, 2: 252}),
    ('fear', 255, _kfr_fear, _kfb_fear, ('game', 'card', 'choice', 'targets'), (), (), {0: 255, 1: 260}),
    ('gongoozle', 267, _kfr_gongoozle, _kfb_gongoozle, ('game', 'card', 'choice', 'destroyed', 'target', 'targets'), (), (), {0: 267, 1: 272, 2: 278, 3: 280, 4: 279, 5: 279, 6: 280}),
    ('guilty_hearts', 283, _kfr_guilty_hearts, _kfb_guilty_hearts, ('game', 'card', 'targets'), (), (), {0: 283, 1: 288}),
    ('hand_of_dis', 291, _kfr_hand_of_dis, _kfb_hand_of_dis, ('game', 'card', 'choice', 'targets'), (), (), {0: 291, 1: 296, 2: 300}),
    ('hecatomb', 303, _kfr_hecatomb, _kfb_hecatomb, ('game', 'card', 'c', 'counts', 'n', 'pid', 'targets'), (), (), {0: 303, 1: 311}),
    ('tendrils_of_pain', 316, _kfr_tendrils_of_pain, _kfb_tendrils_of_pain, ('game', 'card', 'amount', 'c', 'opponent', 'targets'), (), (), {0: 316, 1: 325}),
    ('hysteria', 328, _kfr_hysteria, _kfb_hysteria, ('game', 'card', 'c', 'targets'), (), (), {0: 328, 1: 336}),
    ('key_hammer', 339, _kfr_key_hammer, _kfb_key_hammer, ('game', 'card', 'opponent'), (), (), {0: 339, 1: 348}),
    ('mind_barb', 351, _kfr_mind_barb, _kfb_mind_barb, ('game', 'card'), (), (), {0: 351, 1: 352}),
    ('pandemonium', 355, _kfr_pandemonium, _kfb_pandemonium, ('game', 'card', 'c', 'targets'), (), (), {0: 355, 1: 363}),
    ('poltergeist', 366, _kfr_poltergeist, _kfb_poltergeist, ('game', 'card', 'choice', 'target', 'targets'), (), (), {0: 366, 1: 374, 2: 379, 3: 380}),
    ('red_hot_armor', 390, _kfr_red_hot_armor, _kfb_red_hot_armor, ('game', 'card', 'c', 'lost', 'opponent', 'targets'), (), (), {0: 390, 1: 401}),
    ('key_to_dis', 408, _kfr_key_to_dis, _kfb_key_to_dis, ('game', 'card', 'targets'), (), (), {0: 408, 1: 409, 2: 411}),
    ('sacrificial_altar', 414, _kfr_sacrificial_altar, _kfb_sacrificial_altar, ('game', 'card', 'choice', 'choice2', 'discard_creatures', 'ok', 'options', 'player', 'to_play', 'victim'), (), (), {0: 414, 1: 420, 2: 431, 3: 437}),
    ('screaming_cave', 443, _kfr_screaming_cave, _kfb_screaming_cave, ('game', 'card', 'cards', 'player'), (), (), {0: 443, 1: 452}),
    ('soul_snatcher_trigger', 459, _kfr_soul_snatcher_trigger, _kfb_soul_snatcher_trigger, ('game', 'event', 'destroyed_card'), (), (), {0: 459, 1: 463}),
    ('drumble_play', 466, _kfr_drumble_play, _kfb_drumble_play, ('game', 'card', 'opponent'), (), (), {0: 466, 1: 473}),
    ('eater_of_the_dead', 476, _kfr_eater_of_the_dead, _kfb_eater_of_the_dead, ('game', 'card', 'choice', 'options', 'player'), (), (), {0: 476, 1: 482}),
    ('_gabos_before_fight.<locals>.handler', 500, _kfr__gabos_before_fight__handler, _kfb__gabos_before_fight__handler, ('game', 'event', 'choice', 'targets', '_kfc_gabos_card'), ((4, 'gabos_card'),), (), {0: 500, 1: 506}),
    ('overlord_greking_on_destroyed_fighting', 514, _kfr_overlord_greking_on_destroyed_fighting, _kfb_overlord_greking_on_destroyed_fighting, ('game', 'survivor', 'victim', 'new_controller', 'owner'), (), (), {0: 514, 1: 517, 2: 516, 3: 516, 4: 518, 5: 528}),
    ('stealer_of_souls_on_destroyed_fighting', 531, _kfr_stealer_of_souls_on_destroyed_fighting, _kfb_stealer_of_souls_on_destroyed_fighting, ('game', 'survivor', 'victim', 'owner'), (), (), {0: 531, 1: 544}),
    ('master_of_n.<locals>.effect', 548, _kfr_master_of_n__effect, _kfb_master_of_n__effect, ('game', 'card', 'choice', 'do_it', 'targets', '_kfc_n'), ((5, 'n'),), (), {0: 548, 1: 553, 2: 559, 3: 563}),
    ('restringuntus', 572, _kfr_restringuntus, _kfb_restringuntus, ('game', 'card', 'chosen', 'houses', 'opponent'), (), (), {0: 572, 1: 575}),
    ('_shaffles_handler.<locals>.handler', 584, _kfr__shaffles_handler__handler, _kfb__shaffles_handler__handler, ('game', 'event', '_kfc_shaffles_card'), ((2, 'shaffles_card'),), (), {0: 584, 1: 588}),
    ('tocsin', 592, _kfr_tocsin, _kfb_tocsin, ('game', 'card'), (), (), {0: 592, 1: 593}),
    ('tolas_trigger', 600, _kfr_tolas_trigger, _kfb_tolas_trigger, ('game', 'event', 'destroyed_card'), (), (), {0: 600, 1: 604}),
    ('truebaru_destroyed', 607, _kfr_truebaru_destroyed, _kfb_truebaru_destroyed, ('game', 'card'), (), (), {0: 607, 1: 611}),
]
