"""Generated by tools/compile_engine.py from keyforge/effects/named/sanctum.py -- do not edit.

Each pausing function of the source, as a routine for keyforge/vm.py's Machine:
`_kfr_*` runs it from a frame's pc, `_kfb_*` binds a call into a frame's locals.
"""

# fmt: off
# flake8: noqa
SOURCE = 'keyforge/effects/named/sanctum.py'
SOURCE_SHA256 = '2981b894ad1a43822f620a1eafc60f9410d89a56a6112626c28f5bb755e22cc5'

# Placeholder defaults: the loader rebuilds every function here in the source module's globals,
# with the original function's own defaults.
_kf_U = None


def _kfr_begone(F, _sent, _kfN):
    # effects/named/sanctum.py:15 begone
    (game, card, mode, player, targets,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 15
            player = controller_of(game, card)
            _kff = game.choose_mode
            _kfa = (player.id, f'{card.name}: choose one', ['Destroy each Dis creature', 'Gain 1Æ'],)
            _kfk = {'source_card': card}
            F.L = [game, card, mode, player, targets]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 17
            mode = _sent
            if mode == 'Gain 1Æ':
                steps.gain(game, player, 1)
                return (3, None)
            targets = [c for c in game.all_creatures('any', card) if c.house == House.DIS]
            if not targets:
                steps.shortfall(game, card, 'destroys nothing: there is no Dis creature in play', 'No Dis creature')
                return (3, None)
            _kff = game.destroy_cards
            _kfa = (targets,)
            _kfk = None
            F.L = [game, card, mode, player, targets]
            F.pc = 2
            return (1, _kff, _kfa, _kfk)
        elif _pc == 2:  # line 27
            return (3, None)

def _kfb_begone(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U]


def _kfr_blinding_light(F, _sent, _kfN):
    # effects/named/sanctum.py:30 blinding_light
    (game, card, chosen, player, t, targets,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 30
            player = controller_of(game, card)
            _kff = game.choose_house
            _kfa = (player.id, f'{card.name}: choose a house', list(House),)
            _kfk = None
            F.L = [game, card, chosen, player, t, targets]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 32
            chosen = _sent
            targets = [c for c in game.all_creatures('any', card) if c.house == chosen]
            if not targets:
                steps.shortfall(game, card, f'stuns nothing: there is no {chosen.value} creature in play', 'No matching creature')
                return (3, None)
            for t in targets:
                steps.stun(game, t)
            return (3, None)

def _kfb_blinding_light(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U, _kf_U]


def _kfr_charge(F, _sent, _kfN):
    # effects/named/sanctum.py:41 charge
    (game, _kfc_card, handler, _kfc_player,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 41
            _kfc_player.cell_contents = controller_of(game, _kfc_card.cell_contents)
            handler = _kf_fn(_kfN[0], globals(), None, None, {'card': _kfc_card, 'player': _kfc_player})
            game.active_effects.add(TriggerEffect(_kfc_card.cell_contents, _kfc_player.cell_contents.id, 'card_played', handler, remaining_duration=1))
            return (3, None)
            _kfd = None
            F.L = [game, _kfc_card, handler, _kfc_player]
            F.pc = 1
            return (2, _kfd)
        elif _pc == 1:  # line 59
            return (3, None)

def _kfb_charge(game, card):
    return [game, _kf_cell(card), _kf_U, _kf_cell()]


def _kfr_charge__handler(F, _sent, _kfN):
    # effects/named/sanctum.py:44 charge.<locals>.handler
    (g, event, choice, options, _kfc_card, _kfc_player,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 44
            if event['card'].type != CardType.CREATURE:
                return (3, None)
            options = g.all_creatures('enemy', _kfc_card.cell_contents)
            if not options:
                return (3, None)
            _kff = g.choose_cards
            _kfa = (_kfc_player.cell_contents.id, f'{_kfc_card.cell_contents.name}: deal 2 damage to an enemy creature', options, 1, 1,)
            _kfk = {'source_card': _kfc_card.cell_contents, 'intent': DecisionIntent.DAMAGE, 'affects': Affects.ENEMY}
            F.L = [g, event, choice, options, _kfc_card, _kfc_player]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 50
            choice = _sent
            steps.deal_damage(g, choice[0], 2)
            _kff = g.check_destroyed
            _kfa = (choice,)
            _kfk = None
            F.L = [g, event, choice, options, _kfc_card, _kfc_player]
            F.pc = 2
            return (1, _kff, _kfa, _kfk)
        elif _pc == 2:  # line 55
            return (3, None)

def _kfb_charge__handler(g, event):
    return [g, event, _kf_U, _kf_U, _kf_U, _kf_U]


def _kfr_cleansing_wave(F, _sent, _kfN):
    # effects/named/sanctum.py:62 cleansing_wave
    (game, card, healed_count, player, t, targets,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 62
            player = controller_of(game, card)
            targets = game.all_creatures('any', card)
            healed_count = 0
            for t in targets:
                if steps.heal(game, t, 1):
                    healed_count += 1
            if healed_count:
                steps.gain(game, player, healed_count)
            else:
                steps.shortfall(game, card, 'heals nothing: no creature in play has any damage', 'No damaged creature')
            return (3, None)
            _kfd = None
            F.L = [game, card, healed_count, player, t, targets]
            F.pc = 1
            return (2, _kfd)
        elif _pc == 1:  # line 74
            return (3, None)

def _kfb_cleansing_wave(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U, _kf_U]


def _kfr_clear_mind(F, _sent, _kfN):
    # effects/named/sanctum.py:77 clear_mind
    (game, card, c, player,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 77
            player = controller_of(game, card)
            for c in player.play_area.creatures:
                c.stunned = False
            return (3, None)
            _kfd = None
            F.L = [game, card, c, player]
            F.pc = 1
            return (2, _kfd)
        elif _pc == 1:  # line 82
            return (3, None)

def _kfb_clear_mind(game, card):
    return [game, card, _kf_U, _kf_U]


def _kfr_doorstep_to_heaven(F, _sent, _kfN):
    # effects/named/sanctum.py:85 doorstep_to_heaven
    (game, card, lost, p,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 85
            for p in game.players.values():
                if p.aember >= 6:
                    lost = p.aember - 5
                    p.aember = 5
                    game.log.add('lose', player=p.id, amount=lost)
            return (3, None)
            _kfd = None
            F.L = [game, card, lost, p]
            F.pc = 1
            return (2, _kfd)
        elif _pc == 1:  # line 92
            return (3, None)

def _kfb_doorstep_to_heaven(game, card):
    return [game, card, _kf_U, _kf_U]


def _kfr_glorious_few(F, _sent, _kfN):
    # effects/named/sanctum.py:95 glorious_few
    (game, card, excess, opponent, player,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 95
            player = controller_of(game, card)
            opponent = opponent_of(game, card)
            excess = len(opponent.play_area.creatures) - len(player.play_area.creatures)
            if excess > 0:
                steps.gain(game, player, excess)
            else:
                steps.shortfall(game, card, 'gains nothing: your opponent does not control more creatures than you', 'No excess')
            return (3, None)
            _kfd = None
            F.L = [game, card, excess, opponent, player]
            F.pc = 1
            return (2, _kfd)
        elif _pc == 1:  # line 104
            return (3, None)

def _kfb_glorious_few(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U]


def _kfr_honorable_claim(F, _sent, _kfN):
    # effects/named/sanctum.py:107 honorable_claim
    (game, card, player, t, targets,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 107
            player = controller_of(game, card)
            targets = [c for c in player.play_area.creatures if 'Knight' in c.tags]
            if not targets:
                steps.shortfall(game, card, 'captures nothing: there is no friendly Knight creature in play', 'No Knight creature')
                return (3, None)
            for t in targets:
                steps.capture(game, t, 1)
            return (3, None)
            _kfd = None
            F.L = [game, card, player, t, targets]
            F.pc = 1
            return (2, _kfd)
        elif _pc == 1:  # line 116
            return (3, None)

def _kfb_honorable_claim(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U]


def _kfr_inspiration(F, _sent, _kfN):
    # effects/named/sanctum.py:119 inspiration
    (game, card, choice, creatures, player, target,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 119
            player = controller_of(game, card)
            creatures = player.play_area.creatures
            if not creatures:
                steps.shortfall(game, card, 'has no friendly creature to ready and use', 'No creature')
                return (3, None)
            _kff = game.choose_cards
            _kfa = (player.id, f'{card.name}: choose a friendly creature to ready and use', creatures, 1, 1,)
            _kfk = {'source_card': card, 'intent': DecisionIntent.READY, 'affects': Affects.FRIENDLY}
            F.L = [game, card, choice, creatures, player, target]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 125
            choice = _sent
            target = choice[0]
            steps.ready(game, target)
            _kff = game.use_creature_ability
            _kfa = (target,)
            _kfk = None
            F.L = [game, card, choice, creatures, player, target]
            F.pc = 2
            return (1, _kff, _kfa, _kfk)
        elif _pc == 2:  # line 131
            return (3, None)

def _kfb_inspiration(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U, _kf_U]


def _kfr_mighty_lance(F, _sent, _kfN):
    # effects/named/sanctum.py:134 mighty_lance
    (game, card, area, choice, hit_neighbor, nchoice, neighbors, options, target,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 134
            options = game.all_creatures('any', card)
            if not options:
                steps.shortfall(game, card, 'deals no damage: there is no creature in play', 'No creature')
                return (3, None)
            _kff = game.choose_cards
            _kfa = (card.controller, f'{card.name}: choose a creature', options, 1, 1,)
            _kfk = {'source_card': card, 'intent': DecisionIntent.DAMAGE, 'affects': Affects.ANY}
            F.L = [game, card, area, choice, hit_neighbor, nchoice, neighbors, options, target]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 139
            choice = _sent
            target = choice[0]
            steps.deal_damage(game, target, 3)
            area = game.find_play_area(target)
            neighbors = area.neighbors(target) if area is not None else []
            hit_neighbor = None
            _pc = 2 if len(neighbors) == 1 else 3
            continue
        elif _pc == 2:  # line 149
            hit_neighbor = neighbors[0]
            _pc = 4
            continue
        elif _pc == 3:  # line 150
            _pc = 5 if len(neighbors) > 1 else 6
            continue
        elif _pc == 4:  # line 148
            if hit_neighbor is not None:
                steps.deal_damage(game, hit_neighbor, 3)
            _kff = game.check_destroyed
            _kfa = ([target] + ([hit_neighbor] if hit_neighbor else []),)
            _kfk = None
            F.L = [game, card, area, choice, hit_neighbor, nchoice, neighbors, options, target]
            F.pc = 9
            return (1, _kff, _kfa, _kfk)
        elif _pc == 5:  # line 151
            _kff = game.choose_cards
            _kfa = (card.controller, f'{card.name}: choose a neighbor to also deal 3 damage to', neighbors, 1, 1,)
            _kfk = {'source_card': card, 'intent': DecisionIntent.DAMAGE, 'affects': Affects.ANY}
            F.L = [game, card, area, choice, hit_neighbor, nchoice, neighbors, options, target]
            F.pc = 8
            return (1, _kff, _kfa, _kfk)
        elif _pc == 6:  # line 150
            _pc = 7
            continue
        elif _pc == 7:  # line 150
            _pc = 4
            continue
        elif _pc == 8:  # line 151
            nchoice = _sent
            hit_neighbor = nchoice[0]
            _pc = 7
            continue
        elif _pc == 9:  # line 158
            return (3, None)

def _kfb_mighty_lance(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U, _kf_U, _kf_U, _kf_U, _kf_U]


def _kfr_oath_of_poverty(F, _sent, _kfN):
    # effects/named/sanctum.py:161 oath_of_poverty
    (game, card, a, area, destroyed, player, targets,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 161
            player = controller_of(game, card)
            targets = list(player.play_area.artifacts)
            if not targets:
                steps.shortfall(game, card, 'destroys nothing: you have no artifacts in play', 'No artifacts')
                return (3, None)
            destroyed = []
            for a in targets:
                area = game.find_play_area(a)
                if area is not None:
                    area.remove(a)
                    game.leave_play(a)
                    player.discard.push(a)
                    game.log.add('destroyed', card=a.name, iid=a.instance_id, destination='discard')
                    destroyed.append(a)
            steps.gain(game, player, len(destroyed) * 2)
            return (3, None)
            _kfd = None
            F.L = [game, card, a, area, destroyed, player, targets]
            F.pc = 1
            return (2, _kfd)
        elif _pc == 1:  # line 178
            return (3, None)

def _kfb_oath_of_poverty(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U, _kf_U, _kf_U]


def _kfr_one_stood_against_many(F, _sent, _kfN):
    # effects/named/sanctum.py:181 one_stood_against_many
    (game, card, _, choice, creatures, fighter, fought_ids, player, target, _kfs0, _kfi1,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 181
            player = controller_of(game, card)
            creatures = player.play_area.creatures
            if not creatures:
                steps.shortfall(game, card, 'has no friendly creature to ready and fight with', 'No creature')
                return (3, None)
            _kff = game.choose_cards
            _kfa = (player.id, f'{card.name}: choose a friendly creature to ready and fight 3 times', creatures, 1, 1,)
            _kfk = {'source_card': card, 'intent': DecisionIntent.READY, 'affects': Affects.FRIENDLY}
            F.L = [game, card, _, choice, creatures, fighter, fought_ids, player, target, _kfs0, _kfi1]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 187
            choice = _sent
            fighter = choice[0]
            fought_ids = set()
            _kfs0 = _kf_seq(range(3))
            _kfi1 = 0
            _pc = 2
            continue
        elif _pc == 2:  # line 193
            _pc = 3 if _kfi1 < len(_kfs0) else 4
            continue
        elif _pc == 3:  # line 194
            _ = _kfs0[_kfi1]
            _kfi1 += 1
            _pc = 5 if not game.legal_fight_targets(fighter, exclude=frozenset(fought_ids)) else 6
            continue
        elif _pc == 4:  # line 193
            return (3, None)
        elif _pc == 5:  # line 195
            _pc = 4
            continue
        elif _pc == 6:  # line 194
            _pc = 7
            continue
        elif _pc == 7:  # line 194
            _kff = game.ready_and_fight
            _kfa = (fighter,)
            _kfk = {'exclude': frozenset(fought_ids)}
            F.L = [game, card, _, choice, creatures, fighter, fought_ids, player, target, _kfs0, _kfi1]
            F.pc = 8
            return (1, _kff, _kfa, _kfk)
        elif _pc == 8:  # line 196
            target = _sent
            _pc = 9 if target is None else 10
            continue
        elif _pc == 9:  # line 198
            _pc = 4
            continue
        elif _pc == 10:  # line 197
            _pc = 11
            continue
        elif _pc == 11:  # line 197
            fought_ids.add(target.instance_id)
            _pc = 2
            continue

def _kfb_one_stood_against_many(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U, _kf_U, _kf_U, _kf_U, _kf_U, _kf_U, _kf_U]


def _kfr_radiant_truth(F, _sent, _kfN):
    # effects/named/sanctum.py:202 radiant_truth
    (game, card, opponent, t, targets,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 202
            opponent = opponent_of(game, card)
            targets = [c for c in opponent.play_area.creatures if not opponent.play_area.is_flank(c)]
            if not targets:
                steps.shortfall(game, card, 'stuns nothing: every enemy creature is on a flank', 'No non-flank enemy creature')
                return (3, None)
            for t in targets:
                steps.stun(game, t)
            return (3, None)
            _kfd = None
            F.L = [game, card, opponent, t, targets]
            F.pc = 1
            return (2, _kfd)
        elif _pc == 1:  # line 211
            return (3, None)

def _kfb_radiant_truth(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U]


def _kfr_take_hostages(F, _sent, _kfN):
    # effects/named/sanctum.py:214 take_hostages
    (game, _kfc_card, handler,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 214
            handler = _kf_fn(_kfN[0], globals(), None, None, {'card': _kfc_card})
            game.active_effects.add(TriggerEffect(_kfc_card.cell_contents, _kfc_card.cell_contents.controller, 'fight_resolved', handler, remaining_duration=1))
            return (3, None)
            _kfd = None
            F.L = [game, _kfc_card, handler]
            F.pc = 1
            return (2, _kfd)
        elif _pc == 1:  # line 223
            return (3, None)

def _kfb_take_hostages(game, card):
    return [game, _kf_cell(card), _kf_U]


def _kfr_take_hostages__handler(F, _sent, _kfN):
    # effects/named/sanctum.py:215 take_hostages.<locals>.handler
    (g, event, _kfc_card,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 215
            if event['attacker'].controller == _kfc_card.cell_contents.controller:
                steps.capture(g, event['attacker'], 1)
            return (3, None)
            _kfd = None
            F.L = [g, event, _kfc_card]
            F.pc = 1
            return (2, _kfd)
        elif _pc == 1:  # line 219
            return (3, None)

def _kfb_take_hostages__handler(g, event):
    return [g, event, _kf_U]


def _kfr_terms_of_redress(F, _sent, _kfN):
    # effects/named/sanctum.py:226 terms_of_redress
    (game, card, choice, creatures, player,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 226
            player = controller_of(game, card)
            creatures = player.play_area.creatures
            if not creatures:
                steps.shortfall(game, card, 'captures nothing: there is no friendly creature in play', 'No creature')
                return (3, None)
            _kff = game.choose_cards
            _kfa = (player.id, f'{card.name}: choose a friendly creature to capture 2Æ', creatures, 1, 1,)
            _kfk = {'source_card': card, 'intent': DecisionIntent.CAPTURE, 'affects': Affects.FRIENDLY}
            F.L = [game, card, choice, creatures, player]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 232
            choice = _sent
            steps.capture(game, choice[0], 2)
            return (3, None)

def _kfb_terms_of_redress(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U]


def _kfr_the_harder_they_come(F, _sent, _kfN):
    # effects/named/sanctum.py:239 the_harder_they_come
    (game, card, choice, options,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 239
            options = [c for c in game.all_creatures('any', card) if game.get_power(c) >= 5]
            if not options:
                steps.shortfall(game, card, 'purges nothing: no creature has power 5 or higher', 'No high-power creature')
                return (3, None)
            _kff = game.choose_cards
            _kfa = (card.controller, f'{card.name}: choose a creature to purge', options, 1, 1,)
            _kfk = {'source_card': card, 'intent': DecisionIntent.PURGE, 'affects': Affects.ANY}
            F.L = [game, card, choice, options]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 244
            choice = _sent
            steps.purge(game, choice[0])
            return (3, None)

def _kfb_the_harder_they_come(game, card):
    return [game, card, _kf_U, _kf_U]


def _kfr_the_spirits_way(F, _sent, _kfN):
    # effects/named/sanctum.py:251 the_spirits_way
    (game, card, targets,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 251
            targets = [c for c in game.all_creatures('any', card) if game.get_power(c) >= 3]
            if not targets:
                steps.shortfall(game, card, 'destroys nothing: no creature has power 3 or higher', 'No high-power creature')
                return (3, None)
            _kff = game.destroy_cards
            _kfa = (targets,)
            _kfk = None
            F.L = [game, card, targets]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 256
            return (3, None)

def _kfb_the_spirits_way(game, card):
    return [game, card, _kf_U]


def _kfr_epic_quest_play(F, _sent, _kfN):
    # effects/named/sanctum.py:261 epic_quest_play
    (game, card, player, t, targets,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 261
            player = controller_of(game, card)
            targets = [c for c in player.play_area.creatures if 'Knight' in c.tags]
            if not targets:
                steps.shortfall(game, card, 'archives nothing: there is no friendly Knight creature in play', 'No Knight creature')
                return (3, None)
            for t in targets:
                player.play_area.remove(t)
                game.leave_play(t)
                player.archive.add(t)
                game.log.add('archive', player=player.id, card=t.name, iid=t.instance_id)
            return (3, None)
            _kfd = None
            F.L = [game, card, player, t, targets]
            F.pc = 1
            return (2, _kfd)
        elif _pc == 1:  # line 273
            return (3, None)

def _kfb_epic_quest_play(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U]


def _kfr_epic_quest_omni(F, _sent, _kfN):
    # effects/named/sanctum.py:276 epic_quest_omni
    (game, card, name_to_house, player, sanctum_played,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 276
            player = controller_of(game, card)
            name_to_house = {c.name: c.house for c in player.all_cards}
            sanctum_played = sum((n for name, n in player.CardsPlayed.items() if name_to_house.get(name) == House.SANCTUM))
            if sanctum_played < 7:
                steps.shortfall(game, card, f'cannot forge a key: only {sanctum_played} Sanctum cards played this turn (needs 7)', 'Not enough Sanctum cards')
                return (3, None)
            _kff = steps.sacrifice
            _kfa = (game, card,)
            _kfk = None
            F.L = [game, card, name_to_house, player, sanctum_played]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 287
            _kff = game.forge_key
            _kfa = (player.id,)
            _kfk = {'cost_modifier': -999, 'source': card}
            F.L = [game, card, name_to_house, player, sanctum_played]
            F.pc = 2
            return (1, _kff, _kfa, _kfk)
        elif _pc == 2:  # line 288
            return (3, None)

def _kfb_epic_quest_omni(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U]


def _kfr_gorm_of_omm(F, _sent, _kfN):
    # effects/named/sanctum.py:291 gorm_of_omm
    (game, card, area, choice, options, owner, target,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 291
            _kff = steps.sacrifice
            _kfa = (game, card,)
            _kfk = None
            F.L = [game, card, area, choice, options, owner, target]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 292
            options = list(game.players[1].play_area.artifacts) + list(game.players[2].play_area.artifacts)
            if not options:
                steps.shortfall(game, card, 'destroys nothing: there is no artifact in play', 'No artifact')
                return (3, None)
            _kff = game.choose_cards
            _kfa = (card.controller, f'{card.name}: choose an artifact to destroy', options, 1, 1,)
            _kfk = {'source_card': card, 'intent': DecisionIntent.DESTROY, 'affects': Affects.ANY}
            F.L = [game, card, area, choice, options, owner, target]
            F.pc = 2
            return (1, _kff, _kfa, _kfk)
        elif _pc == 2:  # line 297
            choice = _sent
            target = choice[0]
            owner = game.players[target.owner]
            area = game.find_play_area(target)
            if area is not None:
                area.remove(target)
                game.leave_play(target)
                owner.discard.push(target)
                game.log.add('destroyed', card=target.name, iid=target.instance_id, destination='discard')
            return (3, None)

def _kfb_gorm_of_omm(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U, _kf_U, _kf_U]


def _kfr_hallowed_blaster(F, _sent, _kfN):
    # effects/named/sanctum.py:311 hallowed_blaster
    (game, card, choice, options,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 311
            options = game.all_creatures('any', card)
            if not options:
                steps.shortfall(game, card, 'heals nothing: there is no creature in play', 'No creature')
                return (3, None)
            _kff = game.choose_cards
            _kfa = (card.controller, f'{card.name}: choose a creature to heal 3 damage from', options, 1, 1,)
            _kfk = {'source_card': card, 'intent': DecisionIntent.HEAL, 'affects': Affects.ANY}
            F.L = [game, card, choice, options]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 316
            choice = _sent
            steps.heal(game, choice[0], 3)
            return (3, None)

def _kfb_hallowed_blaster(game, card):
    return [game, card, _kf_U, _kf_U]


def _kfr_potion_of_invulnerability(F, _sent, _kfN):
    # effects/named/sanctum.py:323 potion_of_invulnerability
    (game, card, player,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 323
            player = controller_of(game, card)
            _kff = steps.sacrifice
            _kfa = (game, card,)
            _kfk = None
            F.L = [game, card, player]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 325
            game.active_effects.add(DurationEffect(card, player.id, 1, player.id, 'CannotBeDealtDamage', '=', True))
            return (3, None)

def _kfb_potion_of_invulnerability(game, card):
    return [game, card, _kf_U]


def _kfr_sigil_of_brotherhood(F, _sent, _kfN):
    # effects/named/sanctum.py:342 sigil_of_brotherhood
    (game, card, c, player,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 342
            player = controller_of(game, card)
            _kff = steps.sacrifice
            _kfa = (game, card,)
            _kfk = None
            F.L = [game, card, c, player]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 344
            game.active_effects.add(DurationEffect(card, player.id, 1, player.id, 'UsePermittedHouse', 'add', House.SANCTUM))
            for c in player.play_area.creatures:
                if c.house == House.SANCTUM:
                    c.CanBeUsed = True
            return (3, None)

def _kfb_sigil_of_brotherhood(game, card):
    return [game, card, _kf_U, _kf_U]


def _kfr_whispering_reliquary(F, _sent, _kfN):
    # effects/named/sanctum.py:351 whispering_reliquary
    (game, card, choice, options,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 351
            options = list(game.players[1].play_area.artifacts) + list(game.players[2].play_area.artifacts)
            if not options:
                steps.shortfall(game, card, 'returns nothing: there is no artifact in play', 'No artifact')
                return (3, None)
            _kff = game.choose_cards
            _kfa = (card.controller, f"{card.name}: choose an artifact to return to its owner's hand", options, 1, 1,)
            _kfk = {'source_card': card, 'intent': DecisionIntent.RETURN_TO_HAND, 'affects': Affects.ANY}
            F.L = [game, card, choice, options]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 356
            choice = _sent
            steps.return_to_hand(game, choice[0])
            return (3, None)

def _kfb_whispering_reliquary(game, card):
    return [game, card, _kf_U, _kf_U]


def _kfr_commander_remiel(F, _sent, _kfN):
    # effects/named/sanctum.py:375 commander_remiel
    (game, card, choice, options, player,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 375
            player = controller_of(game, card)
            options = [c for c in player.play_area.creatures if c.house != House.SANCTUM]
            if not options:
                steps.shortfall(game, card, 'does nothing: there is no friendly non-Sanctum creature in play', 'No non-Sanctum creature')
                return (3, None)
            _kff = game.choose_cards
            _kfa = (player.id, f'{card.name}: choose a friendly non-Sanctum creature to use', options, 1, 1,)
            _kfk = {'source_card': card, 'intent': DecisionIntent.USE_TARGET, 'affects': Affects.FRIENDLY}
            F.L = [game, card, choice, options, player]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 381
            choice = _sent
            _kff = game.use_creature_ability
            _kfa = (choice[0],)
            _kfk = None
            F.L = [game, card, choice, options, player]
            F.pc = 2
            return (1, _kff, _kfa, _kfk)
        elif _pc == 2:  # line 385
            return (3, None)

def _kfb_commander_remiel(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U]


def _kfr_duma_the_martyr_destroyed(F, _sent, _kfN):
    # effects/named/sanctum.py:388 duma_the_martyr_destroyed
    (game, card, c, player,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 388
            player = controller_of(game, card)
            for c in player.play_area.creatures:
                if c is not card:
                    steps.fully_heal(game, c)
            steps.draw(game, player, 2, source=card)
            return (3, None)
            _kfd = None
            F.L = [game, card, c, player]
            F.pc = 1
            return (2, _kfd)
        elif _pc == 1:  # line 395
            return (3, None)

def _kfb_duma_the_martyr_destroyed(game, card):
    return [game, card, _kf_U, _kf_U]


def _kfr_francus_on_destroyed_fighting(F, _sent, _kfN):
    # effects/named/sanctum.py:398 francus_on_destroyed_fighting
    (game, survivor, victim,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 398
            steps.capture(game, survivor, 1)
            return (3, None)
            _kfd = None
            F.L = [game, survivor, victim]
            F.pc = 1
            return (2, _kfd)
        elif _pc == 1:  # line 401
            return (3, None)

def _kfb_francus_on_destroyed_fighting(game, survivor, victim):
    return [game, survivor, victim]


def _kfr_grey_monk_after_reap(F, _sent, _kfN):
    # effects/named/sanctum.py:411 grey_monk_after_reap
    (game, card, choice, options,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 411
            options = game.all_creatures('any', card)
            if not options:
                steps.shortfall(game, card, 'heals nothing: there is no creature in play', 'No creature')
                return (3, None)
            _kff = game.choose_cards
            _kfa = (card.controller, f'{card.name}: choose a creature to heal 2 damage from', options, 1, 1,)
            _kfk = {'source_card': card, 'intent': DecisionIntent.HEAL, 'affects': Affects.ANY}
            F.L = [game, card, choice, options]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 416
            choice = _sent
            steps.heal(game, choice[0], 2)
            return (3, None)

def _kfb_grey_monk_after_reap(game, card):
    return [game, card, _kf_U, _kf_U]


def _kfr_hayyel_the_merchant_register__handler(F, _sent, _kfN):
    # effects/named/sanctum.py:424 hayyel_the_merchant_register.<locals>.handler
    (g, event, _kfc_card,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 424
            if event['card'].type == CardType.ARTIFACT:
                steps.gain(g, g.players[_kfc_card.cell_contents.controller], 1)
            return (3, None)
            _kfd = None
            F.L = [g, event, _kfc_card]
            F.pc = 1
            return (2, _kfd)
        elif _pc == 1:  # line 428
            return (3, None)

def _kfb_hayyel_the_merchant_register__handler(g, event):
    return [g, event, _kf_U]


def _kfr_horseman_of_death(F, _sent, _kfN):
    # effects/named/sanctum.py:433 horseman_of_death
    (game, card, player, t, targets,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 433
            player = controller_of(game, card)
            targets = [c for c in player.discard.cards() if 'Horseman' in c.tags]
            if not targets:
                steps.shortfall(game, card, 'returns nothing: there is no Horseman creature in your discard pile', 'No Horseman in discard')
                return (3, None)
            for t in targets:
                player.discard.remove(t)
                player.hand.add(t)
                game.log.add('return_to_hand', card=t.name, iid=t.instance_id, owner=player.id)
            return (3, None)
            _kfd = None
            F.L = [game, card, player, t, targets]
            F.pc = 1
            return (2, _kfd)
        elif _pc == 1:  # line 444
            return (3, None)

def _kfb_horseman_of_death(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U]


def _kfr_horseman_of_famine(F, _sent, _kfN):
    # effects/named/sanctum.py:447 horseman_of_famine
    (game, card, least, targets,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 447
            targets = game.all_creatures('any', card)
            _kff = choose_least_powerful
            _kfa = (game, card.controller, targets, f'{card.name}: choose the least powerful creature',)
            _kfk = {'source_card': card}
            F.L = [game, card, least, targets]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 449
            least = _sent
            if least is None:
                steps.shortfall(game, card, 'destroys nothing: there is no creature in play', 'No creature')
                return (3, None)
            _kff = game.destroy_cards
            _kfa = ([least],)
            _kfk = None
            F.L = [game, card, least, targets]
            F.pc = 2
            return (1, _kff, _kfa, _kfk)
        elif _pc == 2:  # line 455
            return (3, None)

def _kfb_horseman_of_famine(game, card):
    return [game, card, _kf_U, _kf_U]


def _kfr_horseman_of_pestilence(F, _sent, _kfN):
    # effects/named/sanctum.py:458 horseman_of_pestilence
    (game, card, t, targets,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 458
            targets = [c for c in game.all_creatures('any', card) if 'Horseman' not in c.tags]
            if not targets:
                steps.shortfall(game, card, 'deals no damage: every creature in play is a Horseman', 'No non-Horseman creature')
                return (3, None)
            for t in targets:
                steps.deal_damage(game, t, 1)
            _kff = game.check_destroyed
            _kfa = (targets,)
            _kfk = None
            F.L = [game, card, t, targets]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 465
            return (3, None)

def _kfb_horseman_of_pestilence(game, card):
    return [game, card, _kf_U, _kf_U]


def _kfr_horseman_of_war(F, _sent, _kfN):
    # effects/named/sanctum.py:468 horseman_of_war
    (game, card, c, player,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 468
            player = controller_of(game, card)
            game.active_effects.add(DurationEffect(card, player.id, 1, player.id, 'UsePermittedHouse', 'add', True))
            game.active_effects.add(DurationEffect(card, player.id, 1, player.id, 'CanOnlyFight', '=', True))
            for c in player.play_area.creatures:
                c.CanBeUsed = True
            return (3, None)
            _kfd = None
            F.L = [game, card, c, player]
            F.pc = 1
            return (2, _kfd)
        elif _pc == 1:  # line 475
            return (3, None)

def _kfb_horseman_of_war(game, card):
    return [game, card, _kf_U, _kf_U]


def _kfr_jehu_the_bureaucrat_register__handler(F, _sent, _kfN):
    # effects/named/sanctum.py:479 jehu_the_bureaucrat_register.<locals>.handler
    (g, event, _kfc_card,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 479
            if event['player'] == _kfc_card.cell_contents.controller and event['house'] == House.SANCTUM:
                steps.gain(g, g.players[_kfc_card.cell_contents.controller], 2)
            return (3, None)
            _kfd = None
            F.L = [g, event, _kfc_card]
            F.pc = 1
            return (2, _kfd)
        elif _pc == 1:  # line 483
            return (3, None)

def _kfb_jehu_the_bureaucrat_register__handler(g, event):
    return [g, event, _kf_U]


def _kfr_lady_maxena_play(F, _sent, _kfN):
    # effects/named/sanctum.py:488 lady_maxena_play
    (game, card, choice, options,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 488
            options = game.all_creatures('any', card)
            if not options:
                steps.shortfall(game, card, 'stuns nothing: there are no creatures in play', 'No creature')
                return (3, None)
            _kff = game.choose_cards
            _kfa = (card.controller, f'{card.name}: choose a creature to stun', options, 1, 1,)
            _kfk = {'source_card': card, 'intent': DecisionIntent.STUN, 'affects': Affects.ANY}
            F.L = [game, card, choice, options]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 493
            choice = _sent
            steps.stun(game, choice[0])
            return (3, None)

def _kfb_lady_maxena_play(game, card):
    return [game, card, _kf_U, _kf_U]


def _kfr_lady_maxena_action(F, _sent, _kfN):
    # effects/named/sanctum.py:500 lady_maxena_action
    (game, card,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 500
            steps.return_to_hand(game, card)
            return (3, None)
            _kfd = None
            F.L = [game, card]
            F.pc = 1
            return (2, _kfd)
        elif _pc == 1:  # line 503
            return (3, None)

def _kfb_lady_maxena_action(game, card):
    return [game, card]


def _kfr_lord_golgotha_before_fight(F, _sent, _kfN):
    # effects/named/sanctum.py:506 lord_golgotha_before_fight
    (game, card, target, area, n, neighbors,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 506
            area = game.find_play_area(target)
            neighbors = area.neighbors(target) if area is not None else []
            for n in neighbors:
                steps.deal_damage(game, n, 3)
            return (3, None)
            _kfd = None
            F.L = [game, card, target, area, n, neighbors]
            F.pc = 1
            return (2, _kfd)
        elif _pc == 1:  # line 512
            return (3, None)

def _kfb_lord_golgotha_before_fight(game, card, target):
    return [game, card, target, _kf_U, _kf_U, _kf_U]


def _kfr_numquid_the_fair(F, _sent, _kfN):
    # effects/named/sanctum.py:515 numquid_the_fair
    (game, card, choice, opponent, options, player,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 515
            player = controller_of(game, card)
            opponent = opponent_of(game, card)
            _pc = 1
            continue
        elif _pc == 1:  # line 518
            _pc = 2 if True else 3
            continue
        elif _pc == 2:  # line 519
            options = list(opponent.play_area.creatures)
            if not options:
                steps.shortfall(game, card, 'destroys nothing: there is no enemy creature in play', 'No enemy creature')
                return (3, None)
            _kff = game.choose_cards
            _kfa = (player.id, f'{card.name}: choose an enemy creature to destroy', options, 1, 1,)
            _kfk = {'source_card': card, 'intent': DecisionIntent.DESTROY, 'affects': Affects.ENEMY}
            F.L = [game, card, choice, opponent, options, player]
            F.pc = 4
            return (1, _kff, _kfa, _kfk)
        elif _pc == 3:  # line 518
            return (3, None)
        elif _pc == 4:  # line 523
            choice = _sent
            _kff = game.destroy_cards
            _kfa = (choice,)
            _kfk = None
            F.L = [game, card, choice, opponent, options, player]
            F.pc = 5
            return (1, _kff, _kfa, _kfk)
        elif _pc == 5:  # line 527
            if len(opponent.play_area.creatures) <= len(player.play_area.creatures):
                return (3, None)
            _pc = 1
            continue

def _kfb_numquid_the_fair(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U, _kf_U]


def _kfr_protectrix_after_reap(F, _sent, _kfN):
    # effects/named/sanctum.py:539 protectrix_after_reap
    (game, card, choice, do_it, options, target,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 539
            options = game.all_creatures('any', card)
            if not options:
                return (3, None)
            _kff = game.yes_no
            _kfa = (card.controller, f'{card.name}: fully heal a creature?',)
            _kfk = {'source_card': card, 'intent': DecisionIntent.OPTIONAL_TRIGGER}
            F.L = [game, card, choice, do_it, options, target]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 543
            do_it = _sent
            if not do_it:
                return (3, None)
            _kff = game.choose_cards
            _kfa = (card.controller, f'{card.name}: choose a creature to fully heal', options, 1, 1,)
            _kfk = {'source_card': card, 'intent': DecisionIntent.HEAL, 'affects': Affects.ANY}
            F.L = [game, card, choice, do_it, options, target]
            F.pc = 2
            return (1, _kff, _kfa, _kfk)
        elif _pc == 2:  # line 548
            choice = _sent
            target = choice[0]
            steps.fully_heal(game, target)
            target.damage_prevented = True
            game._end_of_turn_cleanups.append(('sanctum.clear_damage_prevented', target.instance_id))
            return (3, None)

def _kfb_protectrix_after_reap(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U, _kf_U]


def _kfr_sanctum_guardian_after(F, _sent, _kfN):
    # effects/named/sanctum.py:558 sanctum_guardian_after
    (game, card, choice, others, player,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 558
            player = controller_of(game, card)
            others = [c for c in player.play_area.creatures if c is not card]
            if not others:
                return (3, None)
            _kff = game.choose_cards
            _kfa = (player.id, f'{card.name}: choose a friendly creature to swap battleline positions with', others, 1, 1,)
            _kfk = {'source_card': card, 'intent': DecisionIntent.SWAP, 'affects': Affects.FRIENDLY}
            F.L = [game, card, choice, others, player]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 563
            choice = _sent
            player.play_area.swap(card, choice[0])
            game.log.add('swap', card=card.name, iid=card.instance_id, other=choice[0].name, other_iid=choice[0].instance_id)
            return (3, None)

def _kfb_sanctum_guardian_after(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U]


def _kfr_sergeant_zakiel_play(F, _sent, _kfN):
    # effects/named/sanctum.py:571 sergeant_zakiel_play
    (game, card, area, choice, do_it, neighbors, player,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 571
            player = controller_of(game, card)
            area = player.play_area
            neighbors = area.neighbors(card)
            if not neighbors:
                return (3, None)
            _kff = game.yes_no
            _kfa = (player.id, f'{card.name}: ready and fight with a neighboring creature?',)
            _kfk = {'source_card': card, 'intent': DecisionIntent.OPTIONAL_TRIGGER}
            F.L = [game, card, area, choice, do_it, neighbors, player]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 577
            do_it = _sent
            if not do_it:
                return (3, None)
            _kff = game.choose_cards
            _kfa = (player.id, f'{card.name}: choose a neighboring creature', neighbors, 1, 1,)
            _kfk = {'source_card': card, 'intent': DecisionIntent.READY, 'affects': Affects.FRIENDLY}
            F.L = [game, card, area, choice, do_it, neighbors, player]
            F.pc = 2
            return (1, _kff, _kfa, _kfk)
        elif _pc == 2:  # line 583
            choice = _sent
            _kff = game.ready_and_fight
            _kfa = (choice[0],)
            _kfk = None
            F.L = [game, card, area, choice, do_it, neighbors, player]
            F.pc = 3
            return (1, _kff, _kfa, _kfk)
        elif _pc == 3:  # line 587
            return (3, None)

def _kfb_sergeant_zakiel_play(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U, _kf_U, _kf_U]


def _kfr_gatekeeper(F, _sent, _kfN):
    # effects/named/sanctum.py:600 gatekeeper
    (game, card, opponent,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 600
            opponent = opponent_of(game, card)
            if opponent.aember >= 7:
                steps.capture(game, card, opponent.aember - 5)
            else:
                steps.shortfall(game, card, f'captures nothing: {{pos:{opponent.id}}} Æmber is below 7', 'Opponent below 7')
            return (3, None)
            _kfd = None
            F.L = [game, card, opponent]
            F.pc = 1
            return (2, _kfd)
        elif _pc == 1:  # line 607
            return (3, None)

def _kfb_gatekeeper(game, card):
    return [game, card, _kf_U]


def _kfr_veemos_lightbringer(F, _sent, _kfN):
    # effects/named/sanctum.py:614 veemos_lightbringer
    (game, card, targets,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 614
            targets = [c for c in game.all_creatures('any', card) if 'elusive' in game.get_keywords(c)]
            if not targets:
                steps.shortfall(game, card, 'destroys nothing: there is no elusive creature in play', 'No elusive creature')
                return (3, None)
            _kff = game.destroy_cards
            _kfa = (targets,)
            _kfk = None
            F.L = [game, card, targets]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 619
            return (3, None)

def _kfb_veemos_lightbringer(game, card):
    return [game, card, _kf_U]


# (qualname, first line, step, binder, slots, freevar slots, nested code (name, line), line of each pc)
ROUTINES = [
    ('begone', 15, _kfr_begone, _kfb_begone, ('game', 'card', 'mode', 'player', 'targets'), (), (), {0: 15, 1: 17, 2: 27}),
    ('blinding_light', 30, _kfr_blinding_light, _kfb_blinding_light, ('game', 'card', 'chosen', 'player', 't', 'targets'), (), (), {0: 30, 1: 32}),
    ('charge', 41, _kfr_charge, _kfb_charge, ('game', '_kfc_card', 'handler', '_kfc_player'), (), (('handler', 44),), {0: 41, 1: 59}),
    ('charge.<locals>.handler', 44, _kfr_charge__handler, _kfb_charge__handler, ('g', 'event', 'choice', 'options', '_kfc_card', '_kfc_player'), ((4, 'card'), (5, 'player')), (), {0: 44, 1: 50, 2: 55}),
    ('cleansing_wave', 62, _kfr_cleansing_wave, _kfb_cleansing_wave, ('game', 'card', 'healed_count', 'player', 't', 'targets'), (), (), {0: 62, 1: 74}),
    ('clear_mind', 77, _kfr_clear_mind, _kfb_clear_mind, ('game', 'card', 'c', 'player'), (), (), {0: 77, 1: 82}),
    ('doorstep_to_heaven', 85, _kfr_doorstep_to_heaven, _kfb_doorstep_to_heaven, ('game', 'card', 'lost', 'p'), (), (), {0: 85, 1: 92}),
    ('glorious_few', 95, _kfr_glorious_few, _kfb_glorious_few, ('game', 'card', 'excess', 'opponent', 'player'), (), (), {0: 95, 1: 104}),
    ('honorable_claim', 107, _kfr_honorable_claim, _kfb_honorable_claim, ('game', 'card', 'player', 't', 'targets'), (), (), {0: 107, 1: 116}),
    ('inspiration', 119, _kfr_inspiration, _kfb_inspiration, ('game', 'card', 'choice', 'creatures', 'player', 'target'), (), (), {0: 119, 1: 125, 2: 131}),
    ('mighty_lance', 134, _kfr_mighty_lance, _kfb_mighty_lance, ('game', 'card', 'area', 'choice', 'hit_neighbor', 'nchoice', 'neighbors', 'options', 'target'), (), (), {0: 134, 1: 139, 2: 149, 3: 150, 4: 148, 5: 151, 6: 150, 7: 150, 8: 151, 9: 158}),
    ('oath_of_poverty', 161, _kfr_oath_of_poverty, _kfb_oath_of_poverty, ('game', 'card', 'a', 'area', 'destroyed', 'player', 'targets'), (), (), {0: 161, 1: 178}),
    ('one_stood_against_many', 181, _kfr_one_stood_against_many, _kfb_one_stood_against_many, ('game', 'card', '_', 'choice', 'creatures', 'fighter', 'fought_ids', 'player', 'target', '_kfs0', '_kfi1'), (), (), {0: 181, 1: 187, 2: 193, 3: 194, 4: 193, 5: 195, 6: 194, 7: 194, 8: 196, 9: 198, 10: 197, 11: 197}),
    ('radiant_truth', 202, _kfr_radiant_truth, _kfb_radiant_truth, ('game', 'card', 'opponent', 't', 'targets'), (), (), {0: 202, 1: 211}),
    ('take_hostages', 214, _kfr_take_hostages, _kfb_take_hostages, ('game', '_kfc_card', 'handler'), (), (('handler', 215),), {0: 214, 1: 223}),
    ('take_hostages.<locals>.handler', 215, _kfr_take_hostages__handler, _kfb_take_hostages__handler, ('g', 'event', '_kfc_card'), ((2, 'card'),), (), {0: 215, 1: 219}),
    ('terms_of_redress', 226, _kfr_terms_of_redress, _kfb_terms_of_redress, ('game', 'card', 'choice', 'creatures', 'player'), (), (), {0: 226, 1: 232}),
    ('the_harder_they_come', 239, _kfr_the_harder_they_come, _kfb_the_harder_they_come, ('game', 'card', 'choice', 'options'), (), (), {0: 239, 1: 244}),
    ('the_spirits_way', 251, _kfr_the_spirits_way, _kfb_the_spirits_way, ('game', 'card', 'targets'), (), (), {0: 251, 1: 256}),
    ('epic_quest_play', 261, _kfr_epic_quest_play, _kfb_epic_quest_play, ('game', 'card', 'player', 't', 'targets'), (), (), {0: 261, 1: 273}),
    ('epic_quest_omni', 276, _kfr_epic_quest_omni, _kfb_epic_quest_omni, ('game', 'card', 'name_to_house', 'player', 'sanctum_played'), (), (), {0: 276, 1: 287, 2: 288}),
    ('gorm_of_omm', 291, _kfr_gorm_of_omm, _kfb_gorm_of_omm, ('game', 'card', 'area', 'choice', 'options', 'owner', 'target'), (), (), {0: 291, 1: 292, 2: 297}),
    ('hallowed_blaster', 311, _kfr_hallowed_blaster, _kfb_hallowed_blaster, ('game', 'card', 'choice', 'options'), (), (), {0: 311, 1: 316}),
    ('potion_of_invulnerability', 323, _kfr_potion_of_invulnerability, _kfb_potion_of_invulnerability, ('game', 'card', 'player'), (), (), {0: 323, 1: 325}),
    ('sigil_of_brotherhood', 342, _kfr_sigil_of_brotherhood, _kfb_sigil_of_brotherhood, ('game', 'card', 'c', 'player'), (), (), {0: 342, 1: 344}),
    ('whispering_reliquary', 351, _kfr_whispering_reliquary, _kfb_whispering_reliquary, ('game', 'card', 'choice', 'options'), (), (), {0: 351, 1: 356}),
    ('commander_remiel', 375, _kfr_commander_remiel, _kfb_commander_remiel, ('game', 'card', 'choice', 'options', 'player'), (), (), {0: 375, 1: 381, 2: 385}),
    ('duma_the_martyr_destroyed', 388, _kfr_duma_the_martyr_destroyed, _kfb_duma_the_martyr_destroyed, ('game', 'card', 'c', 'player'), (), (), {0: 388, 1: 395}),
    ('francus_on_destroyed_fighting', 398, _kfr_francus_on_destroyed_fighting, _kfb_francus_on_destroyed_fighting, ('game', 'survivor', 'victim'), (), (), {0: 398, 1: 401}),
    ('grey_monk_after_reap', 411, _kfr_grey_monk_after_reap, _kfb_grey_monk_after_reap, ('game', 'card', 'choice', 'options'), (), (), {0: 411, 1: 416}),
    ('hayyel_the_merchant_register.<locals>.handler', 424, _kfr_hayyel_the_merchant_register__handler, _kfb_hayyel_the_merchant_register__handler, ('g', 'event', '_kfc_card'), ((2, 'card'),), (), {0: 424, 1: 428}),
    ('horseman_of_death', 433, _kfr_horseman_of_death, _kfb_horseman_of_death, ('game', 'card', 'player', 't', 'targets'), (), (), {0: 433, 1: 444}),
    ('horseman_of_famine', 447, _kfr_horseman_of_famine, _kfb_horseman_of_famine, ('game', 'card', 'least', 'targets'), (), (), {0: 447, 1: 449, 2: 455}),
    ('horseman_of_pestilence', 458, _kfr_horseman_of_pestilence, _kfb_horseman_of_pestilence, ('game', 'card', 't', 'targets'), (), (), {0: 458, 1: 465}),
    ('horseman_of_war', 468, _kfr_horseman_of_war, _kfb_horseman_of_war, ('game', 'card', 'c', 'player'), (), (), {0: 468, 1: 475}),
    ('jehu_the_bureaucrat_register.<locals>.handler', 479, _kfr_jehu_the_bureaucrat_register__handler, _kfb_jehu_the_bureaucrat_register__handler, ('g', 'event', '_kfc_card'), ((2, 'card'),), (), {0: 479, 1: 483}),
    ('lady_maxena_play', 488, _kfr_lady_maxena_play, _kfb_lady_maxena_play, ('game', 'card', 'choice', 'options'), (), (), {0: 488, 1: 493}),
    ('lady_maxena_action', 500, _kfr_lady_maxena_action, _kfb_lady_maxena_action, ('game', 'card'), (), (), {0: 500, 1: 503}),
    ('lord_golgotha_before_fight', 506, _kfr_lord_golgotha_before_fight, _kfb_lord_golgotha_before_fight, ('game', 'card', 'target', 'area', 'n', 'neighbors'), (), (), {0: 506, 1: 512}),
    ('numquid_the_fair', 515, _kfr_numquid_the_fair, _kfb_numquid_the_fair, ('game', 'card', 'choice', 'opponent', 'options', 'player'), (), (), {0: 515, 1: 518, 2: 519, 3: 518, 4: 523, 5: 527}),
    ('protectrix_after_reap', 539, _kfr_protectrix_after_reap, _kfb_protectrix_after_reap, ('game', 'card', 'choice', 'do_it', 'options', 'target'), (), (), {0: 539, 1: 543, 2: 548}),
    ('sanctum_guardian_after', 558, _kfr_sanctum_guardian_after, _kfb_sanctum_guardian_after, ('game', 'card', 'choice', 'others', 'player'), (), (), {0: 558, 1: 563}),
    ('sergeant_zakiel_play', 571, _kfr_sergeant_zakiel_play, _kfb_sergeant_zakiel_play, ('game', 'card', 'area', 'choice', 'do_it', 'neighbors', 'player'), (), (), {0: 571, 1: 577, 2: 583, 3: 587}),
    ('gatekeeper', 600, _kfr_gatekeeper, _kfb_gatekeeper, ('game', 'card', 'opponent'), (), (), {0: 600, 1: 607}),
    ('veemos_lightbringer', 614, _kfr_veemos_lightbringer, _kfb_veemos_lightbringer, ('game', 'card', 'targets'), (), (), {0: 614, 1: 619}),
]
