"""Generated by tools/compile_engine.py from keyforge/effects/named/untamed.py -- do not edit.

Each pausing function of the source, as a routine for keyforge/vm.py's Machine:
`_kfr_*` runs it from a frame's pc, `_kfb_*` binds a call into a frame's locals.
"""

# fmt: off
# flake8: noqa
SOURCE = 'keyforge/effects/named/untamed.py'
SOURCE_SHA256 = '3ec894ce00adafa40065ef033f3beffd1bba42dbf6d0af8ad5bbe1b53de9be4e'

# Placeholder defaults: the loader rebuilds every function here in the source module's globals,
# with the original function's own defaults.
_kf_U = None


def _kfr_cooperative_hunting(F, _sent, _kfN):
    # effects/named/untamed.py:15 cooperative_hunting
    (game, card, choice, hit, i, n, options, player, _kfs0, _kfi1,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 15
            player = controller_of(game, card)
            n = len(player.play_area.creatures)
            if n == 0:
                steps.shortfall(game, card, 'deals no damage: you have no friendly creature in play', 'No friendly creature')
                return (3, None)
            hit = []
            _kfs0 = _kf_seq(range(n))
            _kfi1 = 0
            _pc = 1
            continue
        elif _pc == 1:  # line 22
            _pc = 2 if _kfi1 < len(_kfs0) else 3
            continue
        elif _pc == 2:  # line 23
            i = _kfs0[_kfi1]
            _kfi1 += 1
            options = game.all_creatures('any', card)
            _pc = 4 if not options else 5
            continue
        elif _pc == 3:  # line 22
            _kff = game.check_destroyed
            _kfa = (hit,)
            _kfk = None
            F.L = [game, card, choice, hit, i, n, options, player, _kfs0, _kfi1]
            F.pc = 8
            return (1, _kff, _kfa, _kfk)
        elif _pc == 4:  # line 25
            _pc = 3
            continue
        elif _pc == 5:  # line 24
            _pc = 6
            continue
        elif _pc == 6:  # line 24
            _kff = game.choose_cards
            _kfa = (player.id, f'{card.name}: deal 1 damage to a creature ({i + 1}/{n})', options, 1, 1,)
            _kfk = {'source_card': card, 'intent': DecisionIntent.DAMAGE, 'affects': Affects.ANY}
            F.L = [game, card, choice, hit, i, n, options, player, _kfs0, _kfi1]
            F.pc = 7
            return (1, _kff, _kfa, _kfk)
        elif _pc == 7:  # line 26
            choice = _sent
            steps.deal_damage(game, choice[0], 1)
            hit.append(choice[0])
            _pc = 1
            continue
        elif _pc == 8:  # line 32
            return (3, None)

def _kfb_cooperative_hunting(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U, _kf_U, _kf_U, _kf_U, _kf_U, _kf_U]


def _kfr_curiosity(F, _sent, _kfN):
    # effects/named/untamed.py:35 curiosity
    (game, card, targets,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 35
            targets = [c for c in game.all_creatures('any', card) if 'Scientist' in c.tags]
            if not targets:
                steps.shortfall(game, card, 'destroys nothing: there is no Scientist creature in play', 'No Scientist creature')
                return (3, None)
            _kff = game.destroy_cards
            _kfa = (targets,)
            _kfk = None
            F.L = [game, card, targets]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 40
            return (3, None)

def _kfb_curiosity(game, card):
    return [game, card, _kf_U]


def _kfr_fertility_chant(F, _sent, _kfN):
    # effects/named/untamed.py:43 fertility_chant
    (game, card,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 43
            steps.gain(game, opponent_of(game, card), 2)
            return (3, None)
            _kfd = None
            F.L = [game, card]
            F.pc = 1
            return (2, _kfd)
        elif _pc == 1:  # line 46
            return (3, None)

def _kfb_fertility_chant(game, card):
    return [game, card]


def _kfr_full_moon(F, _sent, _kfN):
    # effects/named/untamed.py:49 full_moon
    (game, _kfc_card, handler,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 49
            handler = _kf_fn(_kfN[0], globals(), None, None, {'card': _kfc_card})
            game.active_effects.add(TriggerEffect(_kfc_card.cell_contents, _kfc_card.cell_contents.controller, 'card_played', handler, remaining_duration=1))
            return (3, None)
            _kfd = None
            F.L = [game, _kfc_card, handler]
            F.pc = 1
            return (2, _kfd)
        elif _pc == 1:  # line 58
            return (3, None)

def _kfb_full_moon(game, card):
    return [game, _kf_cell(card), _kf_U]


def _kfr_full_moon__handler(F, _sent, _kfN):
    # effects/named/untamed.py:50 full_moon.<locals>.handler
    (g, event, _kfc_card,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 50
            if event['card'].type == CardType.CREATURE:
                steps.gain(g, g.players[_kfc_card.cell_contents.controller], 1)
            return (3, None)
            _kfd = None
            F.L = [g, event, _kfc_card]
            F.pc = 1
            return (2, _kfd)
        elif _pc == 1:  # line 54
            return (3, None)

def _kfb_full_moon__handler(g, event):
    return [g, event, _kf_U]


def _kfr_grasping_vines(F, _sent, _kfN):
    # effects/named/untamed.py:61 grasping_vines
    (game, card, a, choice, options, player,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 61
            player = controller_of(game, card)
            options = list(game.players[1].play_area.artifacts) + list(game.players[2].play_area.artifacts)
            if not options:
                steps.shortfall(game, card, 'returns nothing: there is no artifact in play', 'No artifacts')
                return (3, None)
            _kff = game.choose_cards
            _kfa = (player.id, f"{card.name}: choose up to 3 artifacts to return to their owners' hands", options, 0, min(3, len(options)),)
            _kfk = {'source_card': card, 'intent': DecisionIntent.RETURN_TO_HAND, 'affects': Affects.ANY, 'optional': True}
            F.L = [game, card, a, choice, options, player]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 67
            choice = _sent
            for a in choice:
                steps.return_to_hand(game, a)
            return (3, None)

def _kfb_grasping_vines(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U, _kf_U]


def _kfr__lose_one_then_maybe_forge(F, _sent, _kfN):
    # effects/named/untamed.py:75 _lose_one_then_maybe_forge
    (game, card, do_it, player,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 75
            player = controller_of(game, card)
            if not steps.lose(game, player, 1):
                return (3, None)
            _kff = game.yes_no
            _kfa = (player.id, f'{card.name}: forge a key at current cost?',)
            _kfk = {'source_card': card, 'intent': DecisionIntent.OPTIONAL_TRIGGER}
            F.L = [game, card, do_it, player]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 79
            do_it = _sent
            if not do_it:
                return (3, None)
            _kff = game.forge_key
            _kfa = (player.id,)
            _kfk = {'source': card}
            F.L = [game, card, do_it, player]
            F.pc = 2
            return (1, _kff, _kfa, _kfk)
        elif _pc == 2:  # line 84
            return (3, None)

def _kfb__lose_one_then_maybe_forge(game, card):
    return [game, card, _kf_U, _kf_U]


def _kfr_key_charge(F, _sent, _kfN):
    # effects/named/untamed.py:87 key_charge
    (game, card,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 87
            _kff = _lose_one_then_maybe_forge
            _kfa = (game, card,)
            _kfk = None
            F.L = [game, card]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 88
            return (3, None)

def _kfb_key_charge(game, card):
    return [game, card]


def _kfr_lifeweb(F, _sent, _kfN):
    # effects/named/untamed.py:91 lifeweb
    (game, card, n, opponent, player,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 91
            player = controller_of(game, card)
            opponent = opponent_of(game, card)
            n = game.creatures_played_on_turn(opponent.id, game.turn_number - 1)
            if n >= 3:
                steps.steal(game, opponent, player, 2, source=card)
            else:
                steps.shortfall(game, card, 'steals nothing: your opponent played fewer than 3 creatures on their previous turn', 'Not enough creatures played')
            return (3, None)
            _kfd = None
            F.L = [game, card, n, opponent, player]
            F.pc = 1
            return (2, _kfd)
        elif _pc == 1:  # line 100
            return (3, None)

def _kfb_lifeweb(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U]


def _kfr_lost_in_the_woods(F, _sent, _kfN):
    # effects/named/untamed.py:103 lost_in_the_woods
    (game, card, area, c, enemy_choice, enemy_options, friendly_choice, friendly_options, n, opponent, owner, player,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 103
            player = controller_of(game, card)
            opponent = opponent_of(game, card)
            friendly_options = list(player.play_area.creatures)
            friendly_choice = []
            _pc = 1 if friendly_options else 2
            continue
        elif _pc == 1:  # line 113
            n = min(2, len(friendly_options))
            _kff = game.choose_cards
            _kfa = (player.id, f"{card.name}: choose {n} friendly creature{('s' if n != 1 else '')}", friendly_options, n, n,)
            _kfk = {'source_card': card, 'intent': DecisionIntent.SHUFFLE_IN, 'affects': Affects.FRIENDLY}
            F.L = [game, card, area, c, enemy_choice, enemy_options, friendly_choice, friendly_options, n, opponent, owner, player]
            F.pc = 4
            return (1, _kff, _kfa, _kfk)
        elif _pc == 2:  # line 112
            _pc = 3
            continue
        elif _pc == 3:  # line 112
            enemy_options = list(opponent.play_area.creatures)
            enemy_choice = []
            _pc = 5 if enemy_options else 6
            continue
        elif _pc == 4:  # line 114
            friendly_choice = _sent
            _pc = 3
            continue
        elif _pc == 5:  # line 121
            n = min(2, len(enemy_options))
            _kff = game.choose_cards
            _kfa = (player.id, f"{card.name}: choose {n} enemy creature{('s' if n != 1 else '')}", enemy_options, n, n,)
            _kfk = {'source_card': card, 'intent': DecisionIntent.SHUFFLE_IN, 'affects': Affects.ENEMY}
            F.L = [game, card, area, c, enemy_choice, enemy_options, friendly_choice, friendly_options, n, opponent, owner, player]
            F.pc = 8
            return (1, _kff, _kfa, _kfk)
        elif _pc == 6:  # line 120
            _pc = 7
            continue
        elif _pc == 7:  # line 120
            for c in friendly_choice + enemy_choice:
                owner = game.players[c.owner]
                area = game.find_play_area(c)
                if area is not None:
                    area.remove(c)
                    game.leave_play(c)
                    owner.deck.shuffle_in([c], game.event_rng('reshuffle', owner.id))
                    game.log.add('shuffle_into_deck', card=c.name, iid=c.instance_id, owner=owner.id)
            if not friendly_choice and (not enemy_choice):
                steps.shortfall(game, card, 'does nothing: there is no creature in play', 'No creature')
            return (3, None)
        elif _pc == 8:  # line 122
            enemy_choice = _sent
            _pc = 7
            continue

def _kfb_lost_in_the_woods(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U, _kf_U, _kf_U, _kf_U, _kf_U, _kf_U, _kf_U, _kf_U]


def _kfr_mimicry_play(F, _sent, _kfN):
    # effects/named/untamed.py:138 mimicry_play
    (game, card, choice, copied, opponent, options, player,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 138
            player = controller_of(game, card)
            opponent = opponent_of(game, card)
            options = [c for c in opponent.discard.cards() if c.type == CardType.ACTION and c.name != 'Mimicry']
            if not options:
                steps.shortfall(game, card, "does nothing: there is no action card in your opponent's discard pile", 'No action card')
                return (3, None)
            _kff = game.choose_cards
            _kfa = (player.id, f"{card.name}: choose an action card in your opponent's discard pile to copy", options, 1, 1,)
            _kfk = {'source_card': card, 'intent': DecisionIntent.COPY, 'affects': Affects.ENEMY}
            F.L = [game, card, choice, copied, opponent, options, player]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 147
            choice = _sent
            copied = choice[0]
            game.log.add('mimicry_copy', card=card.name, iid=card.instance_id, copied=copied.name)
            card.house_override = copied.house
            _pc = 2 if copied.card_def.on_play is not None else 3
            continue
        elif _pc == 2:  # line 160
            _kff = copied.card_def.on_play
            _kfa = (game, card,)
            _kfk = None
            F.L = [game, card, choice, copied, opponent, options, player]
            F.pc = 5
            return (1, _kff, _kfa, _kfk)
        elif _pc == 3:  # line 159
            _pc = 4
            continue
        elif _pc == 4:  # line 159
            return (3, None)
        elif _pc == 5:  # line 160
            _pc = 4
            continue

def _kfb_mimicry_play(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U, _kf_U, _kf_U]


def _kfr_natures_call(F, _sent, _kfN):
    # effects/named/untamed.py:163 natures_call
    (game, card, c, choice, options,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 163
            options = game.all_creatures('any', card)
            if not options:
                steps.shortfall(game, card, 'returns nothing: there is no creature in play', 'No creature')
                return (3, None)
            _kff = game.choose_cards
            _kfa = (card.controller, f"{card.name}: choose up to 3 creatures to return to their owners' hands", options, 0, min(3, len(options)),)
            _kfk = {'source_card': card, 'intent': DecisionIntent.RETURN_TO_HAND, 'affects': Affects.ANY, 'optional': True}
            F.L = [game, card, c, choice, options]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 168
            choice = _sent
            for c in choice:
                steps.return_to_hand(game, c)
            return (3, None)

def _kfb_natures_call(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U]


def _kfr_nocturnal_maneuver(F, _sent, _kfN):
    # effects/named/untamed.py:176 nocturnal_maneuver
    (game, card, c, choice, options,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 176
            options = [c for c in game.all_creatures('any', card) if not c.Exhausted]
            if not options:
                steps.shortfall(game, card, 'does nothing: there is no ready creature in play', 'No ready creature')
                return (3, None)
            _kff = game.choose_cards
            _kfa = (card.controller, f'{card.name}: choose up to 3 creatures to exhaust', options, 0, min(3, len(options)),)
            _kfk = {'source_card': card, 'intent': DecisionIntent.EXHAUST, 'affects': Affects.ANY, 'optional': True}
            F.L = [game, card, c, choice, options]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 181
            choice = _sent
            for c in choice:
                steps.exhaust(game, c)
            return (3, None)

def _kfb_nocturnal_maneuver(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U]


def _kfr_perilous_wild(F, _sent, _kfN):
    # effects/named/untamed.py:189 perilous_wild
    (game, card, targets,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 189
            targets = [c for c in game.all_creatures('any', card) if 'elusive' in game.get_keywords(c)]
            if not targets:
                steps.shortfall(game, card, 'destroys nothing: there is no elusive creature in play', 'No elusive creature')
                return (3, None)
            _kff = game.destroy_cards
            _kfa = (targets,)
            _kfk = None
            F.L = [game, card, targets]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 194
            return (3, None)

def _kfb_perilous_wild(game, card):
    return [game, card, _kf_U]


def _kfr_regrowth(F, _sent, _kfN):
    # effects/named/untamed.py:197 regrowth
    (game, card, choice, options, player, target,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 197
            player = controller_of(game, card)
            options = [c for c in player.discard.cards() if c.type == CardType.CREATURE]
            if not options:
                steps.shortfall(game, card, 'returns nothing: your discard pile has no creature', 'No creature in discard')
                return (3, None)
            _kff = game.choose_cards
            _kfa = (player.id, f'{card.name}: choose a creature to return to your hand', options, 1, 1,)
            _kfk = {'source_card': card, 'intent': DecisionIntent.RETURN_TO_HAND, 'affects': Affects.FRIENDLY}
            F.L = [game, card, choice, options, player, target]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 203
            choice = _sent
            target = choice[0]
            player.discard.remove(target)
            player.hand.add(target)
            game.log.add('return_to_hand', card=target.name, iid=target.instance_id, owner=player.id)
            return (3, None)

def _kfb_regrowth(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U, _kf_U]


def _kfr_save_the_pack(F, _sent, _kfN):
    # effects/named/untamed.py:213 save_the_pack
    (game, card, player, targets,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 213
            player = controller_of(game, card)
            targets = [c for c in game.all_creatures('any', card) if c.type_object.damage > 0]
            _kff = game.destroy_cards
            _kfa = (targets,)
            _kfk = None
            F.L = [game, card, player, targets]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 216
            if not targets:
                steps.shortfall(game, card, 'destroys nothing: no creature in play has any damage', 'No damaged creature')
            steps.gain_chains(game, player, card, 1)
            return (3, None)

def _kfb_save_the_pack(game, card):
    return [game, card, _kf_U, _kf_U]


def _kfr_scout(F, _sent, _kfN):
    # effects/named/untamed.py:222 scout
    (game, card, c, choice, _kfc_chosen_ids, mod, options, player, _kfs0, _kfi1,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 222
            player = controller_of(game, card)
            options = player.play_area.creatures
            if not options:
                steps.shortfall(game, card, 'does nothing: there is no friendly creature in play', 'No creature')
                return (3, None)
            _kff = game.choose_cards
            _kfa = (player.id, f'{card.name}: choose up to 2 friendly creatures to gain skirmish', options, 0, min(2, len(options)),)
            _kfk = {'source_card': card, 'intent': DecisionIntent.MODIFY, 'affects': Affects.FRIENDLY, 'optional': True}
            F.L = [game, card, c, choice, _kfc_chosen_ids, mod, options, player, _kfs0, _kfi1]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 228
            choice = _sent
            if not choice:
                return (3, None)
            _kfc_chosen_ids.cell_contents = frozenset((c.instance_id for c in choice))
            mod = _kf_fn(_kfN[0], globals(), None, None, {'chosen_ids': _kfc_chosen_ids})
            game.active_effects.add(ModifierEffect(card, player.id, 'keywords', mod))
            game._end_of_turn_cleanups.append(('remove_effects_from_source', card.instance_id))
            _kfs0 = _kf_seq(choice)
            _kfi1 = 0
            _pc = 2
            continue
        elif _pc == 2:  # line 241
            _pc = 3 if _kfi1 < len(_kfs0) else 4
            continue
        elif _pc == 3:  # line 242
            c = _kfs0[_kfi1]
            _kfi1 += 1
            _kff = game.ready_and_fight
            _kfa = (c,)
            _kfk = None
            F.L = [game, card, c, choice, _kfc_chosen_ids, mod, options, player, _kfs0, _kfi1]
            F.pc = 5
            return (1, _kff, _kfa, _kfk)
        elif _pc == 4:  # line 241
            return (3, None)
        elif _pc == 5:  # line 242
            _pc = 2
            continue

def _kfb_scout(game, card):
    return [game, card, _kf_U, _kf_U, _kf_cell(), _kf_U, _kf_U, _kf_U, _kf_U, _kf_U]


def _kfr_stampede(F, _sent, _kfN):
    # effects/named/untamed.py:245 stampede
    (game, card, player, total_uses,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 245
            player = controller_of(game, card)
            total_uses = sum(player.used_this_turn.values())
            if total_uses >= 3:
                steps.steal(game, opponent_of(game, card), player, 2, source=card)
            else:
                steps.shortfall(game, card, 'steals nothing: you have not used 3 or more creatures this turn', 'Not enough creatures used')
            return (3, None)
            _kfd = None
            F.L = [game, card, player, total_uses]
            F.pc = 1
            return (2, _kfd)
        elif _pc == 1:  # line 257
            return (3, None)

def _kfb_stampede(game, card):
    return [game, card, _kf_U, _kf_U]


def _kfr_the_common_cold(F, _sent, _kfN):
    # effects/named/untamed.py:260 the_common_cold
    (game, card, destroyed, do_it, remaining_mars, t, targets,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 260
            targets = game.all_creatures('any', card)
            for t in targets:
                steps.deal_damage(game, t, 1)
            _kff = game.check_destroyed
            _kfa = (targets,)
            _kfk = None
            F.L = [game, card, destroyed, do_it, remaining_mars, t, targets]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 264
            destroyed = _sent
            remaining_mars = [c for c in game.all_creatures('any', card) if c.house == House.MARS and c not in destroyed]
            if not remaining_mars:
                return (3, None)
            _kff = game.yes_no
            _kfa = (card.controller, f'{card.name}: destroy all Mars creatures?',)
            _kfk = {'source_card': card, 'intent': DecisionIntent.OPTIONAL_TRIGGER}
            F.L = [game, card, destroyed, do_it, remaining_mars, t, targets]
            F.pc = 2
            return (1, _kff, _kfa, _kfk)
        elif _pc == 2:  # line 268
            do_it = _sent
            _pc = 3 if do_it else 4
            continue
        elif _pc == 3:  # line 272
            _kff = game.destroy_cards
            _kfa = (remaining_mars,)
            _kfk = None
            F.L = [game, card, destroyed, do_it, remaining_mars, t, targets]
            F.pc = 6
            return (1, _kff, _kfa, _kfk)
        elif _pc == 4:  # line 271
            _pc = 5
            continue
        elif _pc == 5:  # line 271
            return (3, None)
        elif _pc == 6:  # line 272
            _pc = 5
            continue

def _kfb_the_common_cold(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U, _kf_U, _kf_U]


def _kfr_troop_call(F, _sent, _kfN):
    # effects/named/untamed.py:275 troop_call
    (game, card, c, from_discard, from_play, player,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 275
            player = controller_of(game, card)
            from_discard = [c for c in player.discard.cards() if 'Niffle' in c.tags]
            from_play = [c for c in player.play_area.creatures if 'Niffle' in c.tags]
            if not from_discard and (not from_play):
                steps.shortfall(game, card, 'returns nothing: you have no friendly Niffle creature in play or in your discard pile', 'No Niffle creature')
                return (3, None)
            for c in from_discard:
                player.discard.remove(c)
                player.hand.add(c)
                game.log.add('return_to_hand', card=c.name, iid=c.instance_id, owner=player.id)
            for c in from_play:
                steps.return_to_hand(game, c)
            return (3, None)
            _kfd = None
            F.L = [game, card, c, from_discard, from_play, player]
            F.pc = 1
            return (2, _kfd)
        elif _pc == 1:  # line 289
            return (3, None)

def _kfb_troop_call(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U, _kf_U]


def _kfr_vigor(F, _sent, _kfN):
    # effects/named/untamed.py:292 vigor
    (game, card, choice, healed, options,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 292
            options = game.all_creatures('any', card)
            if not options:
                steps.shortfall(game, card, 'heals nothing: there is no creature in play', 'No creature')
                return (3, None)
            _kff = game.choose_cards
            _kfa = (card.controller, f'{card.name}: choose a creature to heal up to 3 damage from', options, 1, 1,)
            _kfk = {'source_card': card, 'intent': DecisionIntent.HEAL, 'affects': Affects.ANY}
            F.L = [game, card, choice, healed, options]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 297
            choice = _sent
            healed = steps.heal(game, choice[0], 3)
            if healed == 3:
                steps.gain(game, controller_of(game, card), 1)
            return (3, None)

def _kfb_vigor(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U]


def _kfr_word_of_returning(F, _sent, _kfN):
    # effects/named/untamed.py:306 word_of_returning
    (game, card, n, opponent, t, targets, total_returned,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 306
            opponent = opponent_of(game, card)
            targets = [c for c in opponent.play_area.creatures if c.aember_captured > 0]
            if not targets:
                steps.shortfall(game, card, 'does nothing: no enemy creature has Æmber on it', 'No Æmber to return')
                return (3, None)
            total_returned = 0
            for t in targets:
                n = t.aember_captured
                steps.deal_damage(game, t, n)
                total_returned += n
                t.aember_captured = 0
            if total_returned:
                steps.gain(game, controller_of(game, card), total_returned)
            _kff = game.check_destroyed
            _kfa = (targets,)
            _kfk = None
            F.L = [game, card, n, opponent, t, targets, total_returned]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 320
            return (3, None)

def _kfb_word_of_returning(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U, _kf_U, _kf_U]


def _kfr_bear_flute(F, _sent, _kfN):
    # effects/named/untamed.py:325 bear_flute
    (game, card, bears_in_play, c, choice, found, player, remaining_discard, target,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 325
            player = controller_of(game, card)
            bears_in_play = [c for c in game.all_creatures('any', card) if c.name == 'Ancient Bear']
            _pc = 1 if bears_in_play else 2
            continue
        elif _pc == 1:  # line 334
            target = bears_in_play[0]
            _pc = 4 if len(bears_in_play) > 1 else 5
            continue
        elif _pc == 2:  # line 333
            _pc = 3
            continue
        elif _pc == 3:  # line 333
            found = [c for c in player.deck.cards() if c.name == 'Ancient Bear'] + [c for c in player.discard.cards() if c.name == 'Ancient Bear']
            if not found:
                steps.shortfall(game, card, 'finds no Ancient Bear in play or in your deck or discard pile', 'No Ancient Bear')
                return (3, None)
            for c in found:
                if not player.deck.remove(c):
                    player.discard.remove(c)
                player.hand.add(c)
                game.log.add('return_to_hand', card=c.name, iid=c.instance_id, owner=player.id, visible_to={player.id})
            remaining_discard = player.discard.take_all()
            player.deck.shuffle_in(remaining_discard, game.event_rng('reshuffle', player.id))
            return (3, None)
        elif _pc == 4:  # line 336
            _kff = game.choose_cards
            _kfa = (player.id, f'{card.name}: choose an Ancient Bear to fully heal', bears_in_play, 1, 1,)
            _kfk = {'source_card': card, 'intent': DecisionIntent.HEAL, 'affects': Affects.ANY}
            F.L = [game, card, bears_in_play, c, choice, found, player, remaining_discard, target]
            F.pc = 7
            return (1, _kff, _kfa, _kfk)
        elif _pc == 5:  # line 335
            _pc = 6
            continue
        elif _pc == 6:  # line 335
            steps.fully_heal(game, target)
            return (3, None)
            _pc = 3
            continue
        elif _pc == 7:  # line 336
            choice = _sent
            target = choice[0]
            _pc = 6
            continue

def _kfb_bear_flute(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U, _kf_U, _kf_U, _kf_U, _kf_U]


def _kfr_nepenthe_seed(F, _sent, _kfN):
    # effects/named/untamed.py:359 nepenthe_seed
    (game, card, choice, options, player, target,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 359
            player = controller_of(game, card)
            _kff = steps.sacrifice
            _kfa = (game, card,)
            _kfk = None
            F.L = [game, card, choice, options, player, target]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 361
            options = player.discard.cards()
            if not options:
                return (3, None)
            _kff = game.choose_cards
            _kfa = (player.id, f'{card.name}: choose a card to return to your hand', options, 1, 1,)
            _kfk = {'source_card': card, 'intent': DecisionIntent.RETURN_TO_HAND, 'affects': Affects.FRIENDLY}
            F.L = [game, card, choice, options, player, target]
            F.pc = 2
            return (1, _kff, _kfa, _kfk)
        elif _pc == 2:  # line 365
            choice = _sent
            target = choice[0]
            player.discard.remove(target)
            player.hand.add(target)
            game.log.add('return_to_hand', card=target.name, iid=target.instance_id, owner=player.id)
            return (3, None)

def _kfb_nepenthe_seed(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U, _kf_U]


def _kfr_ritual_of_balance(F, _sent, _kfN):
    # effects/named/untamed.py:375 ritual_of_balance
    (game, card, opponent,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 375
            opponent = opponent_of(game, card)
            if opponent.aember >= 6:
                steps.steal(game, opponent, controller_of(game, card), 1, source=card)
            else:
                steps.shortfall(game, card, f'steals nothing: {{pos:{opponent.id}}} Æmber is below 6', 'Opponent below 6')
            return (3, None)
            _kfd = None
            F.L = [game, card, opponent]
            F.pc = 1
            return (2, _kfd)
        elif _pc == 1:  # line 382
            return (3, None)

def _kfb_ritual_of_balance(game, card):
    return [game, card, _kf_U]


def _kfr_ritual_of_the_hunt(F, _sent, _kfN):
    # effects/named/untamed.py:385 ritual_of_the_hunt
    (game, card, c, player,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 385
            player = controller_of(game, card)
            _kff = steps.sacrifice
            _kfa = (game, card,)
            _kfk = None
            F.L = [game, card, c, player]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 387
            game.active_effects.add(DurationEffect(card, player.id, 1, player.id, 'UsePermittedHouse', 'add', House.UNTAMED))
            for c in player.play_area.creatures:
                if c.house == House.UNTAMED:
                    c.CanBeUsed = True
            return (3, None)

def _kfb_ritual_of_the_hunt(game, card):
    return [game, card, _kf_U, _kf_U]


def _kfr_world_tree(F, _sent, _kfN):
    # effects/named/untamed.py:394 world_tree
    (game, card, choice, options, player, target,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 394
            player = controller_of(game, card)
            options = [c for c in player.discard.cards() if c.type == CardType.CREATURE]
            if not options:
                steps.shortfall(game, card, 'returns nothing: your discard pile has no creature', 'No creature in discard')
                return (3, None)
            _kff = game.choose_cards
            _kfa = (player.id, f'{card.name}: choose a creature to return to the top of your deck', options, 1, 1,)
            _kfk = {'source_card': card, 'intent': DecisionIntent.SHUFFLE_IN, 'affects': Affects.FRIENDLY}
            F.L = [game, card, choice, options, player, target]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 400
            choice = _sent
            target = choice[0]
            player.discard.remove(target)
            player.deck.put_on_top(target)
            game.log.add('put_on_top', player=player.id, card=target.name, iid=target.instance_id)
            return (3, None)

def _kfb_world_tree(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U, _kf_U]


def _kfr_bigtwig_after_reap(F, _sent, _kfN):
    # effects/named/untamed.py:412 bigtwig_after_reap
    (game, card, choice, options, target,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 412
            options = game.all_creatures('any', card)
            if not options:
                steps.shortfall(game, card, 'does nothing: there is no creature in play', 'No creature')
                return (3, None)
            _kff = game.choose_cards
            _kfa = (card.controller, f'{card.name}: choose a creature to stun and exhaust', options, 1, 1,)
            _kfk = {'source_card': card, 'intent': DecisionIntent.STUN, 'affects': Affects.ANY}
            F.L = [game, card, choice, options, target]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 417
            choice = _sent
            target = choice[0]
            steps.stun(game, target)
            steps.exhaust(game, target)
            return (3, None)

def _kfb_bigtwig_after_reap(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U]


def _kfr_witch_of_the_wilds_register__handler(F, _sent, _kfN):
    # effects/named/untamed.py:427 witch_of_the_wilds_register.<locals>.handler
    (g, event, player, _kfc_card,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 427
            if event['player'] == _kfc_card.cell_contents.controller and event['house'] != House.UNTAMED:
                player = g.players[_kfc_card.cell_contents.controller]
                player.ExtraHousePlayable[House.UNTAMED] = player.ExtraHousePlayable.get(House.UNTAMED, 0) + 1
            return (3, None)
            _kfd = None
            F.L = [g, event, player, _kfc_card]
            F.pc = 1
            return (2, _kfd)
        elif _pc == 1:  # line 436
            return (3, None)

def _kfb_witch_of_the_wilds_register__handler(g, event):
    return [g, event, _kf_U, _kf_U]


def _kfr_chota_hazri(F, _sent, _kfN):
    # effects/named/untamed.py:441 chota_hazri
    (game, card,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 441
            _kff = _lose_one_then_maybe_forge
            _kfa = (game, card,)
            _kfk = None
            F.L = [game, card]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 442
            return (3, None)

def _kfb_chota_hazri(game, card):
    return [game, card]


def _kfr_flaxia(F, _sent, _kfN):
    # effects/named/untamed.py:445 flaxia
    (game, card, opponent, player,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 445
            player = controller_of(game, card)
            opponent = opponent_of(game, card)
            if len(player.play_area.creatures) > len(opponent.play_area.creatures):
                steps.gain(game, player, 2)
            else:
                steps.shortfall(game, card, 'gains nothing: you do not control more creatures than your opponent', 'Not enough creatures')
            return (3, None)
            _kfd = None
            F.L = [game, card, opponent, player]
            F.pc = 1
            return (2, _kfd)
        elif _pc == 1:  # line 453
            return (3, None)

def _kfb_flaxia(game, card):
    return [game, card, _kf_U, _kf_U]


def _kfr_giant_sloth_register__handler(F, _sent, _kfN):
    # effects/named/untamed.py:457 giant_sloth_register.<locals>.handler
    (g, event, _kfc_card,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 457
            if event['player'] == _kfc_card.cell_contents.controller and event['card'].house == House.UNTAMED:
                g.players[_kfc_card.cell_contents.controller].discarded_untamed_this_turn = True
            return (3, None)
            _kfd = None
            F.L = [g, event, _kfc_card]
            F.pc = 1
            return (2, _kfd)
        elif _pc == 1:  # line 461
            return (3, None)

def _kfb_giant_sloth_register__handler(g, event):
    return [g, event, _kf_U]


def _kfr_giant_sloth_action(F, _sent, _kfN):
    # effects/named/untamed.py:470 giant_sloth_action
    (game, card,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 470
            steps.gain(game, controller_of(game, card), 3)
            return (3, None)
            _kfd = None
            F.L = [game, card]
            F.pc = 1
            return (2, _kfd)
        elif _pc == 1:  # line 473
            return (3, None)

def _kfb_giant_sloth_action(game, card):
    return [game, card]


def _kfr_inka_the_spider_effect(F, _sent, _kfN):
    # effects/named/untamed.py:486 inka_the_spider_effect
    (game, card, choice, options,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 486
            options = game.all_creatures('any', card)
            if not options:
                steps.shortfall(game, card, 'stuns nothing: there is no creature in play', 'No creature')
                return (3, None)
            _kff = game.choose_cards
            _kfa = (card.controller, f'{card.name}: choose a creature to stun', options, 1, 1,)
            _kfk = {'source_card': card, 'intent': DecisionIntent.STUN, 'affects': Affects.ANY}
            F.L = [game, card, choice, options]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 491
            choice = _sent
            steps.stun(game, choice[0])
            return (3, None)

def _kfb_inka_the_spider_effect(game, card):
    return [game, card, _kf_U, _kf_U]


def _kfr_kindrith_longshot_after_reap(F, _sent, _kfN):
    # effects/named/untamed.py:498 kindrith_longshot_after_reap
    (game, card, choice, options,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 498
            options = game.all_creatures('any', card)
            if not options:
                steps.shortfall(game, card, 'deals no damage: there is no creature in play', 'No creature')
                return (3, None)
            _kff = game.choose_cards
            _kfa = (card.controller, f'{card.name}: deal 2 damage to a creature', options, 1, 1,)
            _kfk = {'source_card': card, 'intent': DecisionIntent.DAMAGE, 'affects': Affects.ANY}
            F.L = [game, card, choice, options]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 503
            choice = _sent
            steps.deal_damage(game, choice[0], 2)
            _kff = game.check_destroyed
            _kfa = (choice,)
            _kfk = None
            F.L = [game, card, choice, options]
            F.pc = 2
            return (1, _kff, _kfa, _kfk)
        elif _pc == 2:  # line 508
            return (3, None)

def _kfb_kindrith_longshot_after_reap(game, card):
    return [game, card, _kf_U, _kf_U]


def _kfr_lupo_the_scarred_play(F, _sent, _kfN):
    # effects/named/untamed.py:511 lupo_the_scarred_play
    (game, card, choice, options,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 511
            options = opponent_of(game, card).play_area.creatures
            if not options:
                steps.shortfall(game, card, 'deals no damage: there is no enemy creature in play', 'No enemy creature')
                return (3, None)
            _kff = game.choose_cards
            _kfa = (card.controller, f'{card.name}: choose an enemy creature', options, 1, 1,)
            _kfk = {'source_card': card, 'intent': DecisionIntent.DAMAGE, 'affects': Affects.ENEMY}
            F.L = [game, card, choice, options]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 516
            choice = _sent
            steps.deal_damage(game, choice[0], 2)
            _kff = game.check_destroyed
            _kfa = (choice,)
            _kfk = None
            F.L = [game, card, choice, options]
            F.pc = 2
            return (1, _kff, _kfa, _kfk)
        elif _pc == 2:  # line 521
            return (3, None)

def _kfb_lupo_the_scarred_play(game, card):
    return [game, card, _kf_U, _kf_U]


def _kfr_piranha_monkeys_effect(F, _sent, _kfN):
    # effects/named/untamed.py:551 piranha_monkeys_effect
    (game, card, t, targets,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 551
            targets = [c for c in game.all_creatures('any', card) if c is not card]
            if not targets:
                steps.shortfall(game, card, 'deals no damage: there is no other creature in play', 'No other creature')
                return (3, None)
            for t in targets:
                steps.deal_damage(game, t, 2)
            _kff = game.check_destroyed
            _kfa = (targets,)
            _kfk = None
            F.L = [game, card, t, targets]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 558
            return (3, None)

def _kfb_piranha_monkeys_effect(game, card):
    return [game, card, _kf_U, _kf_U]


def _kfr_teliga_register__handler(F, _sent, _kfN):
    # effects/named/untamed.py:562 teliga_register.<locals>.handler
    (g, event, _kfc_card,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 562
            if event['player'] != _kfc_card.cell_contents.controller and event['card'].type == CardType.CREATURE:
                steps.gain(g, g.players[_kfc_card.cell_contents.controller], 1)
            return (3, None)
            _kfd = None
            F.L = [g, event, _kfc_card]
            F.pc = 1
            return (2, _kfd)
        elif _pc == 1:  # line 566
            return (3, None)

def _kfb_teliga_register__handler(g, event):
    return [g, event, _kf_U]


def _kfr_hunting_witch_register__handler(F, _sent, _kfN):
    # effects/named/untamed.py:572 hunting_witch_register.<locals>.handler
    (g, event, played, _kfc_card,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 572
            played = event['card']
            if event['player'] == _kfc_card.cell_contents.controller and played is not _kfc_card.cell_contents and (played.type == CardType.CREATURE):
                steps.gain(g, g.players[_kfc_card.cell_contents.controller], 1)
            return (3, None)
            _kfd = None
            F.L = [g, event, played, _kfc_card]
            F.pc = 1
            return (2, _kfd)
        elif _pc == 1:  # line 577
            return (3, None)

def _kfb_hunting_witch_register__handler(g, event):
    return [g, event, _kf_U, _kf_U]


def _kfr_witch_of_the_eye_after_reap(F, _sent, _kfN):
    # effects/named/untamed.py:582 witch_of_the_eye_after_reap
    (game, card, choice, options, player, target,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 582
            player = controller_of(game, card)
            options = [c for c in player.discard.cards() if c is not card]
            if not options:
                steps.shortfall(game, card, 'returns nothing: your discard pile is empty', 'Discard pile is empty')
                return (3, None)
            _kff = game.choose_cards
            _kfa = (player.id, f'{card.name}: choose a card to return to your hand', options, 1, 1,)
            _kfk = {'source_card': card, 'intent': DecisionIntent.RETURN_TO_HAND, 'affects': Affects.FRIENDLY}
            F.L = [game, card, choice, options, player, target]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 588
            choice = _sent
            target = choice[0]
            player.discard.remove(target)
            player.hand.add(target)
            game.log.add('return_to_hand', card=target.name, iid=target.instance_id, owner=player.id)
            return (3, None)

def _kfb_witch_of_the_eye_after_reap(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U, _kf_U]


# (qualname, first line, step, binder, slots, freevar slots, nested code (name, line), line of each pc)
ROUTINES = [
    ('cooperative_hunting', 15, _kfr_cooperative_hunting, _kfb_cooperative_hunting, ('game', 'card', 'choice', 'hit', 'i', 'n', 'options', 'player', '_kfs0', '_kfi1'), (), (), {0: 15, 1: 22, 2: 23, 3: 22, 4: 25, 5: 24, 6: 24, 7: 26, 8: 32}),
    ('curiosity', 35, _kfr_curiosity, _kfb_curiosity, ('game', 'card', 'targets'), (), (), {0: 35, 1: 40}),
    ('fertility_chant', 43, _kfr_fertility_chant, _kfb_fertility_chant, ('game', 'card'), (), (), {0: 43, 1: 46}),
    ('full_moon', 49, _kfr_full_moon, _kfb_full_moon, ('game', '_kfc_card', 'handler'), (), (('handler', 50),), {0: 49, 1: 58}),
    ('full_moon.<locals>.handler', 50, _kfr_full_moon__handler, _kfb_full_moon__handler, ('g', 'event', '_kfc_card'), ((2, 'card'),), (), {0: 50, 1: 54}),
    ('grasping_vines', 61, _kfr_grasping_vines, _kfb_grasping_vines, ('game', 'card', 'a', 'choice', 'options', 'player'), (), (), {0: 61, 1: 67}),
    ('_lose_one_then_maybe_forge', 75, _kfr__lose_one_then_maybe_forge, _kfb__lose_one_then_maybe_forge, ('game', 'card', 'do_it', 'player'), (), (), {0: 75, 1: 79, 2: 84}),
    ('key_charge', 87, _kfr_key_charge, _kfb_key_charge, ('game', 'card'), (), (), {0: 87, 1: 88}),
    ('lifeweb', 91, _kfr_lifeweb, _kfb_lifeweb, ('game', 'card', 'n', 'opponent', 'player'), (), (), {0: 91, 1: 100}),
    ('lost_in_the_woods', 103, _kfr_lost_in_the_woods, _kfb_lost_in_the_woods, ('game', 'card', 'area', 'c', 'enemy_choice', 'enemy_options', 'friendly_choice', 'friendly_options', 'n', 'opponent', 'owner', 'player'), (), (), {0: 103, 1: 113, 2: 112, 3: 112, 4: 114, 5: 121, 6: 120, 7: 120, 8: 122}),
    ('mimicry_play', 138, _kfr_mimicry_play, _kfb_mimicry_play, ('game', 'card', 'choice', 'copied', 'opponent', 'options', 'player'), (), (), {0: 138, 1: 147, 2: 160, 3: 159, 4: 159, 5: 160}),
    ('natures_call', 163, _kfr_natures_call, _kfb_natures_call, ('game', 'card', 'c', 'choice', 'options'), (), (), {0: 163, 1: 168}),
    ('nocturnal_maneuver', 176, _kfr_nocturnal_maneuver, _kfb_nocturnal_maneuver, ('game', 'card', 'c', 'choice', 'options'), (), (), {0: 176, 1: 181}),
    ('perilous_wild', 189, _kfr_perilous_wild, _kfb_perilous_wild, ('game', 'card', 'targets'), (), (), {0: 189, 1: 194}),
    ('regrowth', 197, _kfr_regrowth, _kfb_regrowth, ('game', 'card', 'choice', 'options', 'player', 'target'), (), (), {0: 197, 1: 203}),
    ('save_the_pack', 213, _kfr_save_the_pack, _kfb_save_the_pack, ('game', 'card', 'player', 'targets'), (), (), {0: 213, 1: 216}),
    ('scout', 222, _kfr_scout, _kfb_scout, ('game', 'card', 'c', 'choice', '_kfc_chosen_ids', 'mod', 'options', 'player', '_kfs0', '_kfi1'), (), (('mod', 236),), {0: 222, 1: 228, 2: 241, 3: 242, 4: 241, 5: 242}),
    ('stampede', 245, _kfr_stampede, _kfb_stampede, ('game', 'card', 'player', 'total_uses'), (), (), {0: 245, 1: 257}),
    ('the_common_cold', 260, _kfr_the_common_cold, _kfb_the_common_cold, ('game', 'card', 'destroyed', 'do_it', 'remaining_mars', 't', 'targets'), (), (), {0: 260, 1: 264, 2: 268, 3: 272, 4: 271, 5: 271, 6: 272}),
    ('troop_call', 275, _kfr_troop_call, _kfb_troop_call, ('game', 'card', 'c', 'from_discard', 'from_play', 'player'), (), (), {0: 275, 1: 289}),
    ('vigor', 292, _kfr_vigor, _kfb_vigor, ('game', 'card', 'choice', 'healed', 'options'), (), (), {0: 292, 1: 297}),
    ('word_of_returning', 306, _kfr_word_of_returning, _kfb_word_of_returning, ('game', 'card', 'n', 'opponent', 't', 'targets', 'total_returned'), (), (), {0: 306, 1: 320}),
    ('bear_flute', 325, _kfr_bear_flute, _kfb_bear_flute, ('game', 'card', 'bears_in_play', 'c', 'choice', 'found', 'player', 'remaining_discard', 'target'), (), (), {0: 325, 1: 334, 2: 333, 3: 333, 4: 336, 5: 335, 6: 335, 7: 336}),
    ('nepenthe_seed', 359, _kfr_nepenthe_seed, _kfb_nepenthe_seed, ('game', 'card', 'choice', 'options', 'player', 'target'), (), (), {0: 359, 1: 361, 2: 365}),
    ('ritual_of_balance', 375, _kfr_ritual_of_balance, _kfb_ritual_of_balance, ('game', 'card', 'opponent'), (), (), {0: 375, 1: 382}),
    ('ritual_of_the_hunt', 385, _kfr_ritual_of_the_hunt, _kfb_ritual_of_the_hunt, ('game', 'card', 'c', 'player'), (), (), {0: 385, 1: 387}),
    ('world_tree', 394, _kfr_world_tree, _kfb_world_tree, ('game', 'card', 'choice', 'options', 'player', 'target'), (), (), {0: 394, 1: 400}),
    ('bigtwig_after_reap', 412, _kfr_bigtwig_after_reap, _kfb_bigtwig_after_reap, ('game', 'card', 'choice', 'options', 'target'), (), (), {0: 412, 1: 417}),
    ('witch_of_the_wilds_register.<locals>.handler', 427, _kfr_witch_of_the_wilds_register__handler, _kfb_witch_of_the_wilds_register__handler, ('g', 'event', 'player', '_kfc_card'), ((3, 'card'),), (), {0: 427, 1: 436}),
    ('chota_hazri', 441, _kfr_chota_hazri, _kfb_chota_hazri, ('game', 'card'), (), (), {0: 441, 1: 442}),
    ('flaxia', 445, _kfr_flaxia, _kfb_flaxia, ('game', 'card', 'opponent', 'player'), (), (), {0: 445, 1: 453}),
    ('giant_sloth_register.<locals>.handler', 457, _kfr_giant_sloth_register__handler, _kfb_giant_sloth_register__handler, ('g', 'event', '_kfc_card'), ((2, 'card'),), (), {0: 457, 1: 461}),
    ('giant_sloth_action', 470, _kfr_giant_sloth_action, _kfb_giant_sloth_action, ('game', 'card'), (), (), {0: 470, 1: 473}),
    ('inka_the_spider_effect', 486, _kfr_inka_the_spider_effect, _kfb_inka_the_spider_effect, ('game', 'card', 'choice', 'options'), (), (), {0: 486, 1: 491}),
    ('kindrith_longshot_after_reap', 498, _kfr_kindrith_longshot_after_reap, _kfb_kindrith_longshot_after_reap, ('game', 'card', 'choice', 'options'), (), (), {0: 498, 1: 503, 2: 508}),
    ('lupo_the_scarred_play', 511, _kfr_lupo_the_scarred_play, _kfb_lupo_the_scarred_play, ('game', 'card', 'choice', 'options'), (), (), {0: 511, 1: 516, 2: 521}),
    ('piranha_monkeys_effect', 551, _kfr_piranha_monkeys_effect, _kfb_piranha_monkeys_effect, ('game', 'card', 't', 'targets'), (), (), {0: 551, 1: 558}),
    ('teliga_register.<locals>.handler', 562, _kfr_teliga_register__handler, _kfb_teliga_register__handler, ('g', 'event', '_kfc_card'), ((2, 'card'),), (), {0: 562, 1: 566}),
    ('hunting_witch_register.<locals>.handler', 572, _kfr_hunting_witch_register__handler, _kfb_hunting_witch_register__handler, ('g', 'event', 'played', '_kfc_card'), ((3, 'card'),), (), {0: 572, 1: 577}),
    ('witch_of_the_eye_after_reap', 582, _kfr_witch_of_the_eye_after_reap, _kfb_witch_of_the_eye_after_reap, ('game', 'card', 'choice', 'options', 'player', 'target'), (), (), {0: 582, 1: 588}),
]
