"""Generated by tools/compile_engine.py from keyforge/effects/named/untamed.py -- do not edit.

Each pausing function of the source, as a routine for keyforge/vm.py's Machine:
`_kfmk_*` makes a routine: called with the original arguments it runs a fresh call;
called as `routine(_kfF=frame, _sent=sent)` it resumes a frame.
"""

# fmt: off
# flake8: noqa
SOURCE = 'keyforge/effects/named/untamed.py'
SOURCE_SHA256 = 'e15db8a951d81d8d06ca8ca7edda78d44a3dd997f2907914f6d2dcc87340dc44'

# Placeholder defaults: the loader rebuilds every function here in the source module's globals,
# with the original function's own defaults.
_kf_U = None


def _kfmk_cooperative_hunting(_kfN, _kfR):
  def _kfr_cooperative_hunting(game=_kf_U, card=_kf_U, *, _kfF=None, _sent=None, _kf_closure=None):
    # effects/named/untamed.py:15 cooperative_hunting
    if _kfF is None:  # a fresh call: Python bound the arguments
        choice = hit = i = n = options = player = _kfs0 = _kfi1 = _kf_U
        _pc = 0
    else:  # resuming a suspended frame
        (game, card, choice, hit, i, n, options, player, _kfs0, _kfi1,) = _kfF.L
        _pc = _kfF.pc
    if not _pc:
        player = controller_of(game, card)
        n = len(player.play_area.creatures)
        if n == 0:
            steps.shortfall(game, card, 'deals no damage: you have no friendly creature in play', 'No friendly creature')
            return
        hit = []
    if not _pc:
        _kfs0 = _kf_seq(range(n))
        _kfi1 = 0
    while (not _pc and _kfi1 < len(_kfs0)) or _pc == 1:
        if not _pc:
            i = _kfs0[_kfi1]
            _kfi1 += 1
        if not _pc:
            options = game.all_creatures('any', card)
            if not options:
                break
        if not _pc:
            _sent = _kf_step(game.choose_cards)(player.id, f'{card.name}: deal 1 damage to a creature ({i + 1}/{n})', options, 1, 1, source_card=card, intent=DecisionIntent.DAMAGE, affects=Affects.ANY)
            if type(_sent) is _kf_S:
                if _kfF is None:
                    _kfF = _kf_Frame(_kfR, [game, card, choice, hit, i, n, options, player, _kfs0, _kfi1])
                    _kfF.pc = 1
                    _sent.frames.append(_kfF)
                else:
                    _kfF.L = [game, card, choice, hit, i, n, options, player, _kfs0, _kfi1]
                    _kfF.pc = 1
                return _sent
            choice = _sent
        elif _pc == 1:
            _pc = 0
            choice = _sent
        steps.deal_damage(game, choice[0], 1)
        hit.append(choice[0])
    if not _pc:
        _sent = _kf_step(game.check_destroyed)(hit)
        if type(_sent) is _kf_S:
            if _kfF is None:
                _kfF = _kf_Frame(_kfR, [game, card, choice, hit, i, n, options, player, _kfs0, _kfi1])
                _kfF.pc = 2
                _sent.frames.append(_kfF)
            else:
                _kfF.L = [game, card, choice, hit, i, n, options, player, _kfs0, _kfi1]
                _kfF.pc = 2
            return _sent
    elif _pc == 2:
        _pc = 0
    return None
  return _kfr_cooperative_hunting


def _kfmk_curiosity(_kfN, _kfR):
  def _kfr_curiosity(game=_kf_U, card=_kf_U, *, _kfF=None, _sent=None, _kf_closure=None):
    # effects/named/untamed.py:35 curiosity
    if _kfF is None:  # a fresh call: Python bound the arguments
        targets = _kf_U
        _pc = 0
    else:  # resuming a suspended frame
        (game, card, targets,) = _kfF.L
        _pc = _kfF.pc
    if not _pc:
        targets = [c for c in game.all_creatures('any', card) if 'Scientist' in c.tags]
        if not targets:
            steps.shortfall(game, card, 'destroys nothing: there is no Scientist creature in play', 'No Scientist creature')
            return
    if not _pc:
        _sent = _kf_step(game.destroy_cards)(targets)
        if type(_sent) is _kf_S:
            if _kfF is None:
                _kfF = _kf_Frame(_kfR, [game, card, targets])
                _kfF.pc = 1
                _sent.frames.append(_kfF)
            else:
                _kfF.L = [game, card, targets]
                _kfF.pc = 1
            return _sent
    elif _pc == 1:
        _pc = 0
    return None
  return _kfr_curiosity


def _kfmk_fertility_chant(_kfN, _kfR):
  def _kfr_fertility_chant(game=_kf_U, card=_kf_U, *, _kfF=None, _sent=None, _kf_closure=None):
    # effects/named/untamed.py:43 fertility_chant
    if _kfF is None:  # a fresh call: Python bound the arguments
        _pc = 0
    else:  # resuming a suspended frame
        (game, card,) = _kfF.L
        _pc = _kfF.pc
    if not _pc:
        steps.gain(game, opponent_of(game, card), 2)
        return
    if not _pc:
        _kfd = _kf_S(None)
        if _kfF is None:
            _kfF = _kf_Frame(_kfR, [game, card])
            _kfF.pc = 1
            _kfd.frames.append(_kfF)
        else:
            _kfF.L = [game, card]
            _kfF.pc = 1
        return _kfd
    elif _pc == 1:
        _pc = 0
    return None
  return _kfr_fertility_chant


def _kfmk_full_moon(_kfN, _kfR):
  def _kfr_full_moon(game=_kf_U, card=_kf_U, *, _kfF=None, _sent=None, _kf_closure=None):
    # effects/named/untamed.py:49 full_moon
    if _kfF is None:  # a fresh call: Python bound the arguments
        handler = _kf_U
        _kfc_card = _kf_cell(card)
        _pc = 0
    else:  # resuming a suspended frame
        (game, _kfc_card, handler,) = _kfF.L
        _pc = _kfF.pc
    if not _pc:
        handler = _kf_fn(_kfN[0], globals(), None, None, {'card': _kfc_card})
        game.active_effects.add(TriggerEffect(_kfc_card.cell_contents, _kfc_card.cell_contents.controller, 'card_played', handler, remaining_duration=1))
        return
    if not _pc:
        _kfd = _kf_S(None)
        if _kfF is None:
            _kfF = _kf_Frame(_kfR, [game, _kfc_card, handler])
            _kfF.pc = 1
            _kfd.frames.append(_kfF)
        else:
            _kfF.L = [game, _kfc_card, handler]
            _kfF.pc = 1
        return _kfd
    elif _pc == 1:
        _pc = 0
    return None
  return _kfr_full_moon


def _kfmk_full_moon__handler(_kfN, _kfR):
  def _kfr_full_moon__handler(g=_kf_U, event=_kf_U, *, _kfF=None, _sent=None, _kf_closure=None):
    # effects/named/untamed.py:50 full_moon.<locals>.handler
    if _kfF is None:  # a fresh call: Python bound the arguments
        _kfc_card = _kf_closure[0]
        _pc = 0
    else:  # resuming a suspended frame
        (g, event, _kfc_card,) = _kfF.L
        _pc = _kfF.pc
    if not _pc:
        if event['card'].type == CardType.CREATURE:
            steps.gain(g, g.players[_kfc_card.cell_contents.controller], 1)
        return
    if not _pc:
        _kfd = _kf_S(None)
        if _kfF is None:
            _kfF = _kf_Frame(_kfR, [g, event, _kfc_card])
            _kfF.pc = 1
            _kfd.frames.append(_kfF)
        else:
            _kfF.L = [g, event, _kfc_card]
            _kfF.pc = 1
        return _kfd
    elif _pc == 1:
        _pc = 0
    return None
  return _kfr_full_moon__handler


def _kfmk_grasping_vines(_kfN, _kfR):
  def _kfr_grasping_vines(game=_kf_U, card=_kf_U, *, _kfF=None, _sent=None, _kf_closure=None):
    # effects/named/untamed.py:61 grasping_vines
    if _kfF is None:  # a fresh call: Python bound the arguments
        a = choice = options = player = _kf_U
        _pc = 0
    else:  # resuming a suspended frame
        (game, card, a, choice, options, player,) = _kfF.L
        _pc = _kfF.pc
    if not _pc:
        player = controller_of(game, card)
        options = list(game.players[1].play_area.artifacts) + list(game.players[2].play_area.artifacts)
        if not options:
            steps.shortfall(game, card, 'returns nothing: there is no artifact in play', 'No artifacts')
            return
    if not _pc:
        _sent = _kf_step(game.choose_cards)(player.id, f"{card.name}: choose up to 3 artifacts to return to their owners' hands", options, 0, min(3, len(options)), source_card=card, intent=DecisionIntent.RETURN_TO_HAND, affects=Affects.ANY, optional=True)
        if type(_sent) is _kf_S:
            if _kfF is None:
                _kfF = _kf_Frame(_kfR, [game, card, a, choice, options, player])
                _kfF.pc = 1
                _sent.frames.append(_kfF)
            else:
                _kfF.L = [game, card, a, choice, options, player]
                _kfF.pc = 1
            return _sent
        choice = _sent
    elif _pc == 1:
        _pc = 0
        choice = _sent
    for a in choice:
        steps.return_to_hand(game, a)
    return None
  return _kfr_grasping_vines


def _kfmk__lose_one_then_maybe_forge(_kfN, _kfR):
  def _kfr__lose_one_then_maybe_forge(game=_kf_U, card=_kf_U, *, _kfF=None, _sent=None, _kf_closure=None):
    # effects/named/untamed.py:75 _lose_one_then_maybe_forge
    if _kfF is None:  # a fresh call: Python bound the arguments
        do_it = player = _kf_U
        _pc = 0
    else:  # resuming a suspended frame
        (game, card, do_it, player,) = _kfF.L
        _pc = _kfF.pc
    if not _pc:
        player = controller_of(game, card)
        if not steps.lose(game, player, 1):
            return
    if not _pc:
        _sent = _kf_step(game.yes_no)(player.id, f'{card.name}: forge a key at current cost?', source_card=card, intent=DecisionIntent.OPTIONAL_TRIGGER)
        if type(_sent) is _kf_S:
            if _kfF is None:
                _kfF = _kf_Frame(_kfR, [game, card, do_it, player])
                _kfF.pc = 1
                _sent.frames.append(_kfF)
            else:
                _kfF.L = [game, card, do_it, player]
                _kfF.pc = 1
            return _sent
        do_it = _sent
    elif _pc == 1:
        _pc = 0
        do_it = _sent
    if not _pc:
        if not do_it:
            return
    if not _pc:
        _sent = _kf_step(game.forge_key)(player.id, source=card)
        if type(_sent) is _kf_S:
            if _kfF is None:
                _kfF = _kf_Frame(_kfR, [game, card, do_it, player])
                _kfF.pc = 2
                _sent.frames.append(_kfF)
            else:
                _kfF.L = [game, card, do_it, player]
                _kfF.pc = 2
            return _sent
    elif _pc == 2:
        _pc = 0
    return None
  return _kfr__lose_one_then_maybe_forge


def _kfmk_key_charge(_kfN, _kfR):
  def _kfr_key_charge(game=_kf_U, card=_kf_U, *, _kfF=None, _sent=None, _kf_closure=None):
    # effects/named/untamed.py:87 key_charge
    if _kfF is None:  # a fresh call: Python bound the arguments
        _pc = 0
    else:  # resuming a suspended frame
        (game, card,) = _kfF.L
        _pc = _kfF.pc
    if not _pc:
        _sent = _kf_step(_lose_one_then_maybe_forge)(game, card)
        if type(_sent) is _kf_S:
            if _kfF is None:
                _kfF = _kf_Frame(_kfR, [game, card])
                _kfF.pc = 1
                _sent.frames.append(_kfF)
            else:
                _kfF.L = [game, card]
                _kfF.pc = 1
            return _sent
    elif _pc == 1:
        _pc = 0
    return None
  return _kfr_key_charge


def _kfmk_lifeweb(_kfN, _kfR):
  def _kfr_lifeweb(game=_kf_U, card=_kf_U, *, _kfF=None, _sent=None, _kf_closure=None):
    # effects/named/untamed.py:91 lifeweb
    if _kfF is None:  # a fresh call: Python bound the arguments
        n = opponent = player = _kf_U
        _pc = 0
    else:  # resuming a suspended frame
        (game, card, n, opponent, player,) = _kfF.L
        _pc = _kfF.pc
    if not _pc:
        player = controller_of(game, card)
        opponent = opponent_of(game, card)
        n = game.creatures_played_on_turn(opponent.id, game.turn_number - 1)
        if n >= 3:
            steps.steal(game, opponent, player, 2, source=card)
        else:
            steps.shortfall(game, card, 'steals nothing: your opponent played fewer than 3 creatures on their previous turn', 'Not enough creatures played')
        return
    if not _pc:
        _kfd = _kf_S(None)
        if _kfF is None:
            _kfF = _kf_Frame(_kfR, [game, card, n, opponent, player])
            _kfF.pc = 1
            _kfd.frames.append(_kfF)
        else:
            _kfF.L = [game, card, n, opponent, player]
            _kfF.pc = 1
        return _kfd
    elif _pc == 1:
        _pc = 0
    return None
  return _kfr_lifeweb


def _kfmk_lost_in_the_woods(_kfN, _kfR):
  def _kfr_lost_in_the_woods(game=_kf_U, card=_kf_U, *, _kfF=None, _sent=None, _kf_closure=None):
    # effects/named/untamed.py:103 lost_in_the_woods
    if _kfF is None:  # a fresh call: Python bound the arguments
        area = c = enemy_choice = enemy_options = friendly_choice = friendly_options = n = opponent = owner = player = _kf_U
        _pc = 0
    else:  # resuming a suspended frame
        (game, card, area, c, enemy_choice, enemy_options, friendly_choice, friendly_options, n, opponent, owner, player,) = _kfF.L
        _pc = _kfF.pc
    if not _pc:
        player = controller_of(game, card)
        opponent = opponent_of(game, card)
        friendly_options = list(player.play_area.creatures)
        friendly_choice = []
    if (not _pc and (friendly_options)) or _pc == 1:
        if not _pc:
            n = min(2, len(friendly_options))
        if not _pc:
            _sent = _kf_step(game.choose_cards)(player.id, f"{card.name}: choose {n} friendly creature{('s' if n != 1 else '')}", friendly_options, n, n, source_card=card, intent=DecisionIntent.SHUFFLE_IN, affects=Affects.FRIENDLY)
            if type(_sent) is _kf_S:
                if _kfF is None:
                    _kfF = _kf_Frame(_kfR, [game, card, area, c, enemy_choice, enemy_options, friendly_choice, friendly_options, n, opponent, owner, player])
                    _kfF.pc = 1
                    _sent.frames.append(_kfF)
                else:
                    _kfF.L = [game, card, area, c, enemy_choice, enemy_options, friendly_choice, friendly_options, n, opponent, owner, player]
                    _kfF.pc = 1
                return _sent
            friendly_choice = _sent
        elif _pc == 1:
            _pc = 0
            friendly_choice = _sent
    if not _pc:
        enemy_options = list(opponent.play_area.creatures)
        enemy_choice = []
    if (not _pc and (enemy_options)) or _pc == 2:
        if not _pc:
            n = min(2, len(enemy_options))
        if not _pc:
            _sent = _kf_step(game.choose_cards)(player.id, f"{card.name}: choose {n} enemy creature{('s' if n != 1 else '')}", enemy_options, n, n, source_card=card, intent=DecisionIntent.SHUFFLE_IN, affects=Affects.ENEMY)
            if type(_sent) is _kf_S:
                if _kfF is None:
                    _kfF = _kf_Frame(_kfR, [game, card, area, c, enemy_choice, enemy_options, friendly_choice, friendly_options, n, opponent, owner, player])
                    _kfF.pc = 2
                    _sent.frames.append(_kfF)
                else:
                    _kfF.L = [game, card, area, c, enemy_choice, enemy_options, friendly_choice, friendly_options, n, opponent, owner, player]
                    _kfF.pc = 2
                return _sent
            enemy_choice = _sent
        elif _pc == 2:
            _pc = 0
            enemy_choice = _sent
    for c in friendly_choice + enemy_choice:
        owner = game.players[c.owner]
        area = game.find_play_area(c)
        if area is not None:
            area.remove(c)
            game.leave_play(c)
            owner.deck.shuffle_in([c], game.event_rng('reshuffle', owner.id))
            game.log.add('shuffle_into_deck', card=c.name, iid=c.instance_id, owner=owner.id)
    if not friendly_choice and (not enemy_choice):
        steps.shortfall(game, card, 'does nothing: there is no creature in play', 'No creature')
    return None
  return _kfr_lost_in_the_woods


def _kfmk_mimicry_play(_kfN, _kfR):
  def _kfr_mimicry_play(game=_kf_U, card=_kf_U, *, _kfF=None, _sent=None, _kf_closure=None):
    # effects/named/untamed.py:138 mimicry_play
    if _kfF is None:  # a fresh call: Python bound the arguments
        choice = copied = opponent = options = player = _kf_U
        _pc = 0
    else:  # resuming a suspended frame
        (game, card, choice, copied, opponent, options, player,) = _kfF.L
        _pc = _kfF.pc
    if not _pc:
        player = controller_of(game, card)
        opponent = opponent_of(game, card)
        options = [c for c in opponent.discard.cards() if c.type == CardType.ACTION and c.name != 'Mimicry']
        if not options:
            steps.shortfall(game, card, "does nothing: there is no action card in your opponent's discard pile", 'No action card')
            return
    if not _pc:
        _sent = _kf_step(game.choose_cards)(player.id, f"{card.name}: choose an action card in your opponent's discard pile to copy", options, 1, 1, source_card=card, intent=DecisionIntent.COPY, affects=Affects.ENEMY)
        if type(_sent) is _kf_S:
            if _kfF is None:
                _kfF = _kf_Frame(_kfR, [game, card, choice, copied, opponent, options, player])
                _kfF.pc = 1
                _sent.frames.append(_kfF)
            else:
                _kfF.L = [game, card, choice, copied, opponent, options, player]
                _kfF.pc = 1
            return _sent
        choice = _sent
    elif _pc == 1:
        _pc = 0
        choice = _sent
    if not _pc:
        copied = choice[0]
        game.log.add('mimicry_copy', card=card.name, iid=card.instance_id, copied=copied.name)
        card.house_override = copied.house
    if (not _pc and (copied.card_def.on_play is not None)) or _pc == 2:
        if not _pc:
            _sent = _kf_step(copied.card_def.on_play)(game, card)
            if type(_sent) is _kf_S:
                if _kfF is None:
                    _kfF = _kf_Frame(_kfR, [game, card, choice, copied, opponent, options, player])
                    _kfF.pc = 2
                    _sent.frames.append(_kfF)
                else:
                    _kfF.L = [game, card, choice, copied, opponent, options, player]
                    _kfF.pc = 2
                return _sent
        elif _pc == 2:
            _pc = 0
    return None
  return _kfr_mimicry_play


def _kfmk_natures_call(_kfN, _kfR):
  def _kfr_natures_call(game=_kf_U, card=_kf_U, *, _kfF=None, _sent=None, _kf_closure=None):
    # effects/named/untamed.py:163 natures_call
    if _kfF is None:  # a fresh call: Python bound the arguments
        c = choice = options = _kf_U
        _pc = 0
    else:  # resuming a suspended frame
        (game, card, c, choice, options,) = _kfF.L
        _pc = _kfF.pc
    if not _pc:
        options = game.all_creatures('any', card)
        if not options:
            steps.shortfall(game, card, 'returns nothing: there is no creature in play', 'No creature')
            return
    if not _pc:
        _sent = _kf_step(game.choose_cards)(card.controller, f"{card.name}: choose up to 3 creatures to return to their owners' hands", options, 0, min(3, len(options)), source_card=card, intent=DecisionIntent.RETURN_TO_HAND, affects=Affects.ANY, optional=True)
        if type(_sent) is _kf_S:
            if _kfF is None:
                _kfF = _kf_Frame(_kfR, [game, card, c, choice, options])
                _kfF.pc = 1
                _sent.frames.append(_kfF)
            else:
                _kfF.L = [game, card, c, choice, options]
                _kfF.pc = 1
            return _sent
        choice = _sent
    elif _pc == 1:
        _pc = 0
        choice = _sent
    for c in choice:
        steps.return_to_hand(game, c)
    return None
  return _kfr_natures_call


def _kfmk_nocturnal_maneuver(_kfN, _kfR):
  def _kfr_nocturnal_maneuver(game=_kf_U, card=_kf_U, *, _kfF=None, _sent=None, _kf_closure=None):
    # effects/named/untamed.py:176 nocturnal_maneuver
    if _kfF is None:  # a fresh call: Python bound the arguments
        c = choice = options = _kf_U
        _pc = 0
    else:  # resuming a suspended frame
        (game, card, c, choice, options,) = _kfF.L
        _pc = _kfF.pc
    if not _pc:
        options = [c for c in game.all_creatures('any', card) if not c.Exhausted]
        if not options:
            steps.shortfall(game, card, 'does nothing: there is no ready creature in play', 'No ready creature')
            return
    if not _pc:
        _sent = _kf_step(game.choose_cards)(card.controller, f'{card.name}: choose up to 3 creatures to exhaust', options, 0, min(3, len(options)), source_card=card, intent=DecisionIntent.EXHAUST, affects=Affects.ANY, optional=True)
        if type(_sent) is _kf_S:
            if _kfF is None:
                _kfF = _kf_Frame(_kfR, [game, card, c, choice, options])
                _kfF.pc = 1
                _sent.frames.append(_kfF)
            else:
                _kfF.L = [game, card, c, choice, options]
                _kfF.pc = 1
            return _sent
        choice = _sent
    elif _pc == 1:
        _pc = 0
        choice = _sent
    for c in choice:
        steps.exhaust(game, c)
    return None
  return _kfr_nocturnal_maneuver


def _kfmk_perilous_wild(_kfN, _kfR):
  def _kfr_perilous_wild(game=_kf_U, card=_kf_U, *, _kfF=None, _sent=None, _kf_closure=None):
    # effects/named/untamed.py:189 perilous_wild
    if _kfF is None:  # a fresh call: Python bound the arguments
        targets = _kf_U
        _pc = 0
    else:  # resuming a suspended frame
        (game, card, targets,) = _kfF.L
        _pc = _kfF.pc
    if not _pc:
        targets = [c for c in game.all_creatures('any', card) if 'elusive' in game.get_keywords(c)]
        if not targets:
            steps.shortfall(game, card, 'destroys nothing: there is no elusive creature in play', 'No elusive creature')
            return
    if not _pc:
        _sent = _kf_step(game.destroy_cards)(targets)
        if type(_sent) is _kf_S:
            if _kfF is None:
                _kfF = _kf_Frame(_kfR, [game, card, targets])
                _kfF.pc = 1
                _sent.frames.append(_kfF)
            else:
                _kfF.L = [game, card, targets]
                _kfF.pc = 1
            return _sent
    elif _pc == 1:
        _pc = 0
    return None
  return _kfr_perilous_wild


def _kfmk_regrowth(_kfN, _kfR):
  def _kfr_regrowth(game=_kf_U, card=_kf_U, *, _kfF=None, _sent=None, _kf_closure=None):
    # effects/named/untamed.py:197 regrowth
    if _kfF is None:  # a fresh call: Python bound the arguments
        choice = options = player = target = _kf_U
        _pc = 0
    else:  # resuming a suspended frame
        (game, card, choice, options, player, target,) = _kfF.L
        _pc = _kfF.pc
    if not _pc:
        player = controller_of(game, card)
        options = [c for c in player.discard.cards() if c.type == CardType.CREATURE]
        if not options:
            steps.shortfall(game, card, 'returns nothing: your discard pile has no creature', 'No creature in discard')
            return
    if not _pc:
        _sent = _kf_step(game.choose_cards)(player.id, f'{card.name}: choose a creature to return to your hand', options, 1, 1, source_card=card, intent=DecisionIntent.RETURN_TO_HAND, affects=Affects.FRIENDLY)
        if type(_sent) is _kf_S:
            if _kfF is None:
                _kfF = _kf_Frame(_kfR, [game, card, choice, options, player, target])
                _kfF.pc = 1
                _sent.frames.append(_kfF)
            else:
                _kfF.L = [game, card, choice, options, player, target]
                _kfF.pc = 1
            return _sent
        choice = _sent
    elif _pc == 1:
        _pc = 0
        choice = _sent
    target = choice[0]
    player.discard.remove(target)
    player.hand.add(target)
    game.log.add('return_to_hand', card=target.name, iid=target.instance_id, owner=player.id)
    return None
  return _kfr_regrowth


def _kfmk_save_the_pack(_kfN, _kfR):
  def _kfr_save_the_pack(game=_kf_U, card=_kf_U, *, _kfF=None, _sent=None, _kf_closure=None):
    # effects/named/untamed.py:213 save_the_pack
    if _kfF is None:  # a fresh call: Python bound the arguments
        player = targets = _kf_U
        _pc = 0
    else:  # resuming a suspended frame
        (game, card, player, targets,) = _kfF.L
        _pc = _kfF.pc
    if not _pc:
        player = controller_of(game, card)
        targets = [c for c in game.all_creatures('any', card) if c.type_object.damage > 0]
    if not _pc:
        _sent = _kf_step(game.destroy_cards)(targets)
        if type(_sent) is _kf_S:
            if _kfF is None:
                _kfF = _kf_Frame(_kfR, [game, card, player, targets])
                _kfF.pc = 1
                _sent.frames.append(_kfF)
            else:
                _kfF.L = [game, card, player, targets]
                _kfF.pc = 1
            return _sent
    elif _pc == 1:
        _pc = 0
    if not targets:
        steps.shortfall(game, card, 'destroys nothing: no creature in play has any damage', 'No damaged creature')
    steps.gain_chains(game, player, card, 1)
    return None
  return _kfr_save_the_pack


def _kfmk_scout(_kfN, _kfR):
  def _kfr_scout(game=_kf_U, card=_kf_U, *, _kfF=None, _sent=None, _kf_closure=None):
    # effects/named/untamed.py:222 scout
    if _kfF is None:  # a fresh call: Python bound the arguments
        c = choice = mod = options = player = _kfs0 = _kfi1 = _kf_U
        _kfc_chosen_ids = _kf_cell()
        _pc = 0
    else:  # resuming a suspended frame
        (game, card, c, choice, _kfc_chosen_ids, mod, options, player, _kfs0, _kfi1,) = _kfF.L
        _pc = _kfF.pc
    if not _pc:
        player = controller_of(game, card)
        options = player.play_area.creatures
        if not options:
            steps.shortfall(game, card, 'does nothing: there is no friendly creature in play', 'No creature')
            return
    if not _pc:
        _sent = _kf_step(game.choose_cards)(player.id, f'{card.name}: choose up to 2 friendly creatures to gain skirmish', options, 0, min(2, len(options)), source_card=card, intent=DecisionIntent.MODIFY, affects=Affects.FRIENDLY, optional=True)
        if type(_sent) is _kf_S:
            if _kfF is None:
                _kfF = _kf_Frame(_kfR, [game, card, c, choice, _kfc_chosen_ids, mod, options, player, _kfs0, _kfi1])
                _kfF.pc = 1
                _sent.frames.append(_kfF)
            else:
                _kfF.L = [game, card, c, choice, _kfc_chosen_ids, mod, options, player, _kfs0, _kfi1]
                _kfF.pc = 1
            return _sent
        choice = _sent
    elif _pc == 1:
        _pc = 0
        choice = _sent
    if not _pc:
        if not choice:
            return
        _kfc_chosen_ids.cell_contents = frozenset((c.instance_id for c in choice))
        mod = _kf_fn(_kfN[0], globals(), None, None, {'chosen_ids': _kfc_chosen_ids})
        game.active_effects.add(ModifierEffect(card, player.id, 'keywords', mod))
        game._end_of_turn_cleanups.append(('remove_effects_from_source', card.instance_id))
    if not _pc:
        _kfs0 = _kf_seq(choice)
        _kfi1 = 0
    while (not _pc and _kfi1 < len(_kfs0)) or _pc == 2:
        if not _pc:
            c = _kfs0[_kfi1]
            _kfi1 += 1
        if not _pc:
            _sent = _kf_step(game.ready_and_fight)(c)
            if type(_sent) is _kf_S:
                if _kfF is None:
                    _kfF = _kf_Frame(_kfR, [game, card, c, choice, _kfc_chosen_ids, mod, options, player, _kfs0, _kfi1])
                    _kfF.pc = 2
                    _sent.frames.append(_kfF)
                else:
                    _kfF.L = [game, card, c, choice, _kfc_chosen_ids, mod, options, player, _kfs0, _kfi1]
                    _kfF.pc = 2
                return _sent
        elif _pc == 2:
            _pc = 0
    return None
  return _kfr_scout


def _kfmk_stampede(_kfN, _kfR):
  def _kfr_stampede(game=_kf_U, card=_kf_U, *, _kfF=None, _sent=None, _kf_closure=None):
    # effects/named/untamed.py:245 stampede
    if _kfF is None:  # a fresh call: Python bound the arguments
        player = total_uses = _kf_U
        _pc = 0
    else:  # resuming a suspended frame
        (game, card, player, total_uses,) = _kfF.L
        _pc = _kfF.pc
    if not _pc:
        player = controller_of(game, card)
        total_uses = sum(player.used_this_turn.values())
        if total_uses >= 3:
            steps.steal(game, opponent_of(game, card), player, 2, source=card)
        else:
            steps.shortfall(game, card, 'steals nothing: you have not used 3 or more creatures this turn', 'Not enough creatures used')
        return
    if not _pc:
        _kfd = _kf_S(None)
        if _kfF is None:
            _kfF = _kf_Frame(_kfR, [game, card, player, total_uses])
            _kfF.pc = 1
            _kfd.frames.append(_kfF)
        else:
            _kfF.L = [game, card, player, total_uses]
            _kfF.pc = 1
        return _kfd
    elif _pc == 1:
        _pc = 0
    return None
  return _kfr_stampede


def _kfmk_the_common_cold(_kfN, _kfR):
  def _kfr_the_common_cold(game=_kf_U, card=_kf_U, *, _kfF=None, _sent=None, _kf_closure=None):
    # effects/named/untamed.py:260 the_common_cold
    if _kfF is None:  # a fresh call: Python bound the arguments
        destroyed = do_it = remaining_mars = t = targets = _kf_U
        _pc = 0
    else:  # resuming a suspended frame
        (game, card, destroyed, do_it, remaining_mars, t, targets,) = _kfF.L
        _pc = _kfF.pc
    if not _pc:
        targets = game.all_creatures('any', card)
        for t in targets:
            steps.deal_damage(game, t, 1)
    if not _pc:
        _sent = _kf_step(game.check_destroyed)(targets)
        if type(_sent) is _kf_S:
            if _kfF is None:
                _kfF = _kf_Frame(_kfR, [game, card, destroyed, do_it, remaining_mars, t, targets])
                _kfF.pc = 1
                _sent.frames.append(_kfF)
            else:
                _kfF.L = [game, card, destroyed, do_it, remaining_mars, t, targets]
                _kfF.pc = 1
            return _sent
        destroyed = _sent
    elif _pc == 1:
        _pc = 0
        destroyed = _sent
    if not _pc:
        remaining_mars = [c for c in game.all_creatures('any', card) if c.house == House.MARS and c not in destroyed]
        if not remaining_mars:
            return
    if not _pc:
        _sent = _kf_step(game.yes_no)(card.controller, f'{card.name}: destroy all Mars creatures?', source_card=card, intent=DecisionIntent.OPTIONAL_TRIGGER)
        if type(_sent) is _kf_S:
            if _kfF is None:
                _kfF = _kf_Frame(_kfR, [game, card, destroyed, do_it, remaining_mars, t, targets])
                _kfF.pc = 2
                _sent.frames.append(_kfF)
            else:
                _kfF.L = [game, card, destroyed, do_it, remaining_mars, t, targets]
                _kfF.pc = 2
            return _sent
        do_it = _sent
    elif _pc == 2:
        _pc = 0
        do_it = _sent
    if (not _pc and (do_it)) or _pc == 3:
        if not _pc:
            _sent = _kf_step(game.destroy_cards)(remaining_mars)
            if type(_sent) is _kf_S:
                if _kfF is None:
                    _kfF = _kf_Frame(_kfR, [game, card, destroyed, do_it, remaining_mars, t, targets])
                    _kfF.pc = 3
                    _sent.frames.append(_kfF)
                else:
                    _kfF.L = [game, card, destroyed, do_it, remaining_mars, t, targets]
                    _kfF.pc = 3
                return _sent
        elif _pc == 3:
            _pc = 0
    return None
  return _kfr_the_common_cold


def _kfmk_troop_call(_kfN, _kfR):
  def _kfr_troop_call(game=_kf_U, card=_kf_U, *, _kfF=None, _sent=None, _kf_closure=None):
    # effects/named/untamed.py:275 troop_call
    if _kfF is None:  # a fresh call: Python bound the arguments
        c = from_discard = from_play = player = _kf_U
        _pc = 0
    else:  # resuming a suspended frame
        (game, card, c, from_discard, from_play, player,) = _kfF.L
        _pc = _kfF.pc
    if not _pc:
        player = controller_of(game, card)
        from_discard = [c for c in player.discard.cards() if 'Niffle' in c.tags]
        from_play = [c for c in player.play_area.creatures if 'Niffle' in c.tags]
        if not from_discard and (not from_play):
            steps.shortfall(game, card, 'returns nothing: you have no friendly Niffle creature in play or in your discard pile', 'No Niffle creature')
            return
        for c in from_discard:
            player.discard.remove(c)
            player.hand.add(c)
            game.log.add('return_to_hand', card=c.name, iid=c.instance_id, owner=player.id)
        for c in from_play:
            steps.return_to_hand(game, c)
        return
    if not _pc:
        _kfd = _kf_S(None)
        if _kfF is None:
            _kfF = _kf_Frame(_kfR, [game, card, c, from_discard, from_play, player])
            _kfF.pc = 1
            _kfd.frames.append(_kfF)
        else:
            _kfF.L = [game, card, c, from_discard, from_play, player]
            _kfF.pc = 1
        return _kfd
    elif _pc == 1:
        _pc = 0
    return None
  return _kfr_troop_call


def _kfmk_vigor(_kfN, _kfR):
  def _kfr_vigor(game=_kf_U, card=_kf_U, *, _kfF=None, _sent=None, _kf_closure=None):
    # effects/named/untamed.py:292 vigor
    if _kfF is None:  # a fresh call: Python bound the arguments
        choice = healed = options = _kf_U
        _pc = 0
    else:  # resuming a suspended frame
        (game, card, choice, healed, options,) = _kfF.L
        _pc = _kfF.pc
    if not _pc:
        options = game.all_creatures('any', card)
        if not options:
            steps.shortfall(game, card, 'heals nothing: there is no creature in play', 'No creature')
            return
    if not _pc:
        _sent = _kf_step(game.choose_cards)(card.controller, f'{card.name}: choose a creature to heal up to 3 damage from', options, 1, 1, source_card=card, intent=DecisionIntent.HEAL, affects=Affects.ANY)
        if type(_sent) is _kf_S:
            if _kfF is None:
                _kfF = _kf_Frame(_kfR, [game, card, choice, healed, options])
                _kfF.pc = 1
                _sent.frames.append(_kfF)
            else:
                _kfF.L = [game, card, choice, healed, options]
                _kfF.pc = 1
            return _sent
        choice = _sent
    elif _pc == 1:
        _pc = 0
        choice = _sent
    healed = steps.heal(game, choice[0], 3)
    if healed == 3:
        steps.gain(game, controller_of(game, card), 1)
    return None
  return _kfr_vigor


def _kfmk_word_of_returning(_kfN, _kfR):
  def _kfr_word_of_returning(game=_kf_U, card=_kf_U, *, _kfF=None, _sent=None, _kf_closure=None):
    # effects/named/untamed.py:306 word_of_returning
    if _kfF is None:  # a fresh call: Python bound the arguments
        n = opponent = t = targets = total_returned = _kf_U
        _pc = 0
    else:  # resuming a suspended frame
        (game, card, n, opponent, t, targets, total_returned,) = _kfF.L
        _pc = _kfF.pc
    if not _pc:
        opponent = opponent_of(game, card)
        targets = [c for c in opponent.play_area.creatures if c.aember_captured > 0]
        if not targets:
            steps.shortfall(game, card, 'does nothing: no enemy creature has Æmber on it', 'No Æmber to return')
            return
        total_returned = 0
        for t in targets:
            n = t.aember_captured
            steps.deal_damage(game, t, n)
            total_returned += n
            t.aember_captured = 0
        if total_returned:
            steps.gain(game, controller_of(game, card), total_returned)
    if not _pc:
        _sent = _kf_step(game.check_destroyed)(targets)
        if type(_sent) is _kf_S:
            if _kfF is None:
                _kfF = _kf_Frame(_kfR, [game, card, n, opponent, t, targets, total_returned])
                _kfF.pc = 1
                _sent.frames.append(_kfF)
            else:
                _kfF.L = [game, card, n, opponent, t, targets, total_returned]
                _kfF.pc = 1
            return _sent
    elif _pc == 1:
        _pc = 0
    return None
  return _kfr_word_of_returning


def _kfmk_bear_flute(_kfN, _kfR):
  def _kfr_bear_flute(game=_kf_U, card=_kf_U, *, _kfF=None, _sent=None, _kf_closure=None):
    # effects/named/untamed.py:325 bear_flute
    if _kfF is None:  # a fresh call: Python bound the arguments
        bears_in_play = c = choice = found = player = remaining_discard = target = _kf_U
        _pc = 0
    else:  # resuming a suspended frame
        (game, card, bears_in_play, c, choice, found, player, remaining_discard, target,) = _kfF.L
        _pc = _kfF.pc
    if not _pc:
        player = controller_of(game, card)
        bears_in_play = [c for c in game.all_creatures('any', card) if c.name == 'Ancient Bear']
    if (not _pc and (bears_in_play)) or _pc == 1:
        if not _pc:
            target = bears_in_play[0]
        if (not _pc and (len(bears_in_play) > 1)) or _pc == 1:
            if not _pc:
                _sent = _kf_step(game.choose_cards)(player.id, f'{card.name}: choose an Ancient Bear to fully heal', bears_in_play, 1, 1, source_card=card, intent=DecisionIntent.HEAL, affects=Affects.ANY)
                if type(_sent) is _kf_S:
                    if _kfF is None:
                        _kfF = _kf_Frame(_kfR, [game, card, bears_in_play, c, choice, found, player, remaining_discard, target])
                        _kfF.pc = 1
                        _sent.frames.append(_kfF)
                    else:
                        _kfF.L = [game, card, bears_in_play, c, choice, found, player, remaining_discard, target]
                        _kfF.pc = 1
                    return _sent
                choice = _sent
            elif _pc == 1:
                _pc = 0
                choice = _sent
            target = choice[0]
        steps.fully_heal(game, target)
        return
    found = [c for c in player.deck.cards() if c.name == 'Ancient Bear'] + [c for c in player.discard.cards() if c.name == 'Ancient Bear']
    if not found:
        steps.shortfall(game, card, 'finds no Ancient Bear in play or in your deck or discard pile', 'No Ancient Bear')
        return
    for c in found:
        if not player.deck.remove(c):
            player.discard.remove(c)
        player.hand.add(c)
        game.log.add('return_to_hand', card=c.name, iid=c.instance_id, owner=player.id, visible_to={player.id})
    remaining_discard = player.discard.take_all()
    player.deck.shuffle_in(remaining_discard, game.event_rng('reshuffle', player.id))
    return None
  return _kfr_bear_flute


def _kfmk_nepenthe_seed(_kfN, _kfR):
  def _kfr_nepenthe_seed(game=_kf_U, card=_kf_U, *, _kfF=None, _sent=None, _kf_closure=None):
    # effects/named/untamed.py:359 nepenthe_seed
    if _kfF is None:  # a fresh call: Python bound the arguments
        choice = options = player = target = _kf_U
        _pc = 0
    else:  # resuming a suspended frame
        (game, card, choice, options, player, target,) = _kfF.L
        _pc = _kfF.pc
    if not _pc:
        player = controller_of(game, card)
    if not _pc:
        _sent = _kf_step(steps.sacrifice)(game, card)
        if type(_sent) is _kf_S:
            if _kfF is None:
                _kfF = _kf_Frame(_kfR, [game, card, choice, options, player, target])
                _kfF.pc = 1
                _sent.frames.append(_kfF)
            else:
                _kfF.L = [game, card, choice, options, player, target]
                _kfF.pc = 1
            return _sent
    elif _pc == 1:
        _pc = 0
    if not _pc:
        options = player.discard.cards()
        if not options:
            return
    if not _pc:
        _sent = _kf_step(game.choose_cards)(player.id, f'{card.name}: choose a card to return to your hand', options, 1, 1, source_card=card, intent=DecisionIntent.RETURN_TO_HAND, affects=Affects.FRIENDLY)
        if type(_sent) is _kf_S:
            if _kfF is None:
                _kfF = _kf_Frame(_kfR, [game, card, choice, options, player, target])
                _kfF.pc = 2
                _sent.frames.append(_kfF)
            else:
                _kfF.L = [game, card, choice, options, player, target]
                _kfF.pc = 2
            return _sent
        choice = _sent
    elif _pc == 2:
        _pc = 0
        choice = _sent
    target = choice[0]
    player.discard.remove(target)
    player.hand.add(target)
    game.log.add('return_to_hand', card=target.name, iid=target.instance_id, owner=player.id)
    return None
  return _kfr_nepenthe_seed


def _kfmk_ritual_of_balance(_kfN, _kfR):
  def _kfr_ritual_of_balance(game=_kf_U, card=_kf_U, *, _kfF=None, _sent=None, _kf_closure=None):
    # effects/named/untamed.py:375 ritual_of_balance
    if _kfF is None:  # a fresh call: Python bound the arguments
        opponent = _kf_U
        _pc = 0
    else:  # resuming a suspended frame
        (game, card, opponent,) = _kfF.L
        _pc = _kfF.pc
    if not _pc:
        opponent = opponent_of(game, card)
        if opponent.aember >= 6:
            steps.steal(game, opponent, controller_of(game, card), 1, source=card)
        else:
            steps.shortfall(game, card, f'steals nothing: {{pos:{opponent.id}}} Æmber is below 6', 'Opponent below 6')
        return
    if not _pc:
        _kfd = _kf_S(None)
        if _kfF is None:
            _kfF = _kf_Frame(_kfR, [game, card, opponent])
            _kfF.pc = 1
            _kfd.frames.append(_kfF)
        else:
            _kfF.L = [game, card, opponent]
            _kfF.pc = 1
        return _kfd
    elif _pc == 1:
        _pc = 0
    return None
  return _kfr_ritual_of_balance


def _kfmk_ritual_of_the_hunt(_kfN, _kfR):
  def _kfr_ritual_of_the_hunt(game=_kf_U, card=_kf_U, *, _kfF=None, _sent=None, _kf_closure=None):
    # effects/named/untamed.py:385 ritual_of_the_hunt
    if _kfF is None:  # a fresh call: Python bound the arguments
        c = player = _kf_U
        _pc = 0
    else:  # resuming a suspended frame
        (game, card, c, player,) = _kfF.L
        _pc = _kfF.pc
    if not _pc:
        player = controller_of(game, card)
    if not _pc:
        _sent = _kf_step(steps.sacrifice)(game, card)
        if type(_sent) is _kf_S:
            if _kfF is None:
                _kfF = _kf_Frame(_kfR, [game, card, c, player])
                _kfF.pc = 1
                _sent.frames.append(_kfF)
            else:
                _kfF.L = [game, card, c, player]
                _kfF.pc = 1
            return _sent
    elif _pc == 1:
        _pc = 0
    game.active_effects.add(DurationEffect(card, player.id, 1, player.id, 'UsePermittedHouse', 'add', House.UNTAMED))
    for c in player.play_area.creatures:
        if c.house == House.UNTAMED:
            c.CanBeUsed = True
    return None
  return _kfr_ritual_of_the_hunt


def _kfmk_world_tree(_kfN, _kfR):
  def _kfr_world_tree(game=_kf_U, card=_kf_U, *, _kfF=None, _sent=None, _kf_closure=None):
    # effects/named/untamed.py:394 world_tree
    if _kfF is None:  # a fresh call: Python bound the arguments
        choice = options = player = target = _kf_U
        _pc = 0
    else:  # resuming a suspended frame
        (game, card, choice, options, player, target,) = _kfF.L
        _pc = _kfF.pc
    if not _pc:
        player = controller_of(game, card)
        options = [c for c in player.discard.cards() if c.type == CardType.CREATURE]
        if not options:
            steps.shortfall(game, card, 'returns nothing: your discard pile has no creature', 'No creature in discard')
            return
    if not _pc:
        _sent = _kf_step(game.choose_cards)(player.id, f'{card.name}: choose a creature to return to the top of your deck', options, 1, 1, source_card=card, intent=DecisionIntent.SHUFFLE_IN, affects=Affects.FRIENDLY)
        if type(_sent) is _kf_S:
            if _kfF is None:
                _kfF = _kf_Frame(_kfR, [game, card, choice, options, player, target])
                _kfF.pc = 1
                _sent.frames.append(_kfF)
            else:
                _kfF.L = [game, card, choice, options, player, target]
                _kfF.pc = 1
            return _sent
        choice = _sent
    elif _pc == 1:
        _pc = 0
        choice = _sent
    target = choice[0]
    player.discard.remove(target)
    player.deck.put_on_top(target)
    game.log.add('put_on_top', player=player.id, card=target.name, iid=target.instance_id)
    return None
  return _kfr_world_tree


def _kfmk_bigtwig_after_reap(_kfN, _kfR):
  def _kfr_bigtwig_after_reap(game=_kf_U, card=_kf_U, *, _kfF=None, _sent=None, _kf_closure=None):
    # effects/named/untamed.py:412 bigtwig_after_reap
    if _kfF is None:  # a fresh call: Python bound the arguments
        choice = options = target = _kf_U
        _pc = 0
    else:  # resuming a suspended frame
        (game, card, choice, options, target,) = _kfF.L
        _pc = _kfF.pc
    if not _pc:
        options = game.all_creatures('any', card)
        if not options:
            steps.shortfall(game, card, 'does nothing: there is no creature in play', 'No creature')
            return
    if not _pc:
        _sent = _kf_step(game.choose_cards)(card.controller, f'{card.name}: choose a creature to stun and exhaust', options, 1, 1, source_card=card, intent=DecisionIntent.STUN, affects=Affects.ANY)
        if type(_sent) is _kf_S:
            if _kfF is None:
                _kfF = _kf_Frame(_kfR, [game, card, choice, options, target])
                _kfF.pc = 1
                _sent.frames.append(_kfF)
            else:
                _kfF.L = [game, card, choice, options, target]
                _kfF.pc = 1
            return _sent
        choice = _sent
    elif _pc == 1:
        _pc = 0
        choice = _sent
    target = choice[0]
    steps.stun(game, target)
    steps.exhaust(game, target)
    return None
  return _kfr_bigtwig_after_reap


def _kfmk_witch_of_the_wilds_register__handler(_kfN, _kfR):
  def _kfr_witch_of_the_wilds_register__handler(g=_kf_U, event=_kf_U, *, _kfF=None, _sent=None, _kf_closure=None):
    # effects/named/untamed.py:427 witch_of_the_wilds_register.<locals>.handler
    if _kfF is None:  # a fresh call: Python bound the arguments
        player = _kf_U
        _kfc_card = _kf_closure[0]
        _pc = 0
    else:  # resuming a suspended frame
        (g, event, player, _kfc_card,) = _kfF.L
        _pc = _kfF.pc
    if not _pc:
        if event['player'] == _kfc_card.cell_contents.controller and event['house'] != House.UNTAMED:
            player = g.players[_kfc_card.cell_contents.controller]
            player.ExtraHousePlayable[House.UNTAMED] = player.ExtraHousePlayable.get(House.UNTAMED, 0) + 1
        return
    if not _pc:
        _kfd = _kf_S(None)
        if _kfF is None:
            _kfF = _kf_Frame(_kfR, [g, event, player, _kfc_card])
            _kfF.pc = 1
            _kfd.frames.append(_kfF)
        else:
            _kfF.L = [g, event, player, _kfc_card]
            _kfF.pc = 1
        return _kfd
    elif _pc == 1:
        _pc = 0
    return None
  return _kfr_witch_of_the_wilds_register__handler


def _kfmk_chota_hazri(_kfN, _kfR):
  def _kfr_chota_hazri(game=_kf_U, card=_kf_U, *, _kfF=None, _sent=None, _kf_closure=None):
    # effects/named/untamed.py:441 chota_hazri
    if _kfF is None:  # a fresh call: Python bound the arguments
        _pc = 0
    else:  # resuming a suspended frame
        (game, card,) = _kfF.L
        _pc = _kfF.pc
    if not _pc:
        _sent = _kf_step(_lose_one_then_maybe_forge)(game, card)
        if type(_sent) is _kf_S:
            if _kfF is None:
                _kfF = _kf_Frame(_kfR, [game, card])
                _kfF.pc = 1
                _sent.frames.append(_kfF)
            else:
                _kfF.L = [game, card]
                _kfF.pc = 1
            return _sent
    elif _pc == 1:
        _pc = 0
    return None
  return _kfr_chota_hazri


def _kfmk_flaxia(_kfN, _kfR):
  def _kfr_flaxia(game=_kf_U, card=_kf_U, *, _kfF=None, _sent=None, _kf_closure=None):
    # effects/named/untamed.py:445 flaxia
    if _kfF is None:  # a fresh call: Python bound the arguments
        opponent = player = _kf_U
        _pc = 0
    else:  # resuming a suspended frame
        (game, card, opponent, player,) = _kfF.L
        _pc = _kfF.pc
    if not _pc:
        player = controller_of(game, card)
        opponent = opponent_of(game, card)
        if len(player.play_area.creatures) > len(opponent.play_area.creatures):
            steps.gain(game, player, 2)
        else:
            steps.shortfall(game, card, 'gains nothing: you do not control more creatures than your opponent', 'Not enough creatures')
        return
    if not _pc:
        _kfd = _kf_S(None)
        if _kfF is None:
            _kfF = _kf_Frame(_kfR, [game, card, opponent, player])
            _kfF.pc = 1
            _kfd.frames.append(_kfF)
        else:
            _kfF.L = [game, card, opponent, player]
            _kfF.pc = 1
        return _kfd
    elif _pc == 1:
        _pc = 0
    return None
  return _kfr_flaxia


def _kfmk_giant_sloth_register__handler(_kfN, _kfR):
  def _kfr_giant_sloth_register__handler(g=_kf_U, event=_kf_U, *, _kfF=None, _sent=None, _kf_closure=None):
    # effects/named/untamed.py:457 giant_sloth_register.<locals>.handler
    if _kfF is None:  # a fresh call: Python bound the arguments
        _kfc_card = _kf_closure[0]
        _pc = 0
    else:  # resuming a suspended frame
        (g, event, _kfc_card,) = _kfF.L
        _pc = _kfF.pc
    if not _pc:
        if event['player'] == _kfc_card.cell_contents.controller and event['card'].house == House.UNTAMED:
            g.players[_kfc_card.cell_contents.controller].discarded_untamed_this_turn = True
        return
    if not _pc:
        _kfd = _kf_S(None)
        if _kfF is None:
            _kfF = _kf_Frame(_kfR, [g, event, _kfc_card])
            _kfF.pc = 1
            _kfd.frames.append(_kfF)
        else:
            _kfF.L = [g, event, _kfc_card]
            _kfF.pc = 1
        return _kfd
    elif _pc == 1:
        _pc = 0
    return None
  return _kfr_giant_sloth_register__handler


def _kfmk_giant_sloth_action(_kfN, _kfR):
  def _kfr_giant_sloth_action(game=_kf_U, card=_kf_U, *, _kfF=None, _sent=None, _kf_closure=None):
    # effects/named/untamed.py:470 giant_sloth_action
    if _kfF is None:  # a fresh call: Python bound the arguments
        _pc = 0
    else:  # resuming a suspended frame
        (game, card,) = _kfF.L
        _pc = _kfF.pc
    if not _pc:
        steps.gain(game, controller_of(game, card), 3)
        return
    if not _pc:
        _kfd = _kf_S(None)
        if _kfF is None:
            _kfF = _kf_Frame(_kfR, [game, card])
            _kfF.pc = 1
            _kfd.frames.append(_kfF)
        else:
            _kfF.L = [game, card]
            _kfF.pc = 1
        return _kfd
    elif _pc == 1:
        _pc = 0
    return None
  return _kfr_giant_sloth_action


def _kfmk_inka_the_spider_effect(_kfN, _kfR):
  def _kfr_inka_the_spider_effect(game=_kf_U, card=_kf_U, *, _kfF=None, _sent=None, _kf_closure=None):
    # effects/named/untamed.py:486 inka_the_spider_effect
    if _kfF is None:  # a fresh call: Python bound the arguments
        choice = options = _kf_U
        _pc = 0
    else:  # resuming a suspended frame
        (game, card, choice, options,) = _kfF.L
        _pc = _kfF.pc
    if not _pc:
        options = game.all_creatures('any', card)
        if not options:
            steps.shortfall(game, card, 'stuns nothing: there is no creature in play', 'No creature')
            return
    if not _pc:
        _sent = _kf_step(game.choose_cards)(card.controller, f'{card.name}: choose a creature to stun', options, 1, 1, source_card=card, intent=DecisionIntent.STUN, affects=Affects.ANY)
        if type(_sent) is _kf_S:
            if _kfF is None:
                _kfF = _kf_Frame(_kfR, [game, card, choice, options])
                _kfF.pc = 1
                _sent.frames.append(_kfF)
            else:
                _kfF.L = [game, card, choice, options]
                _kfF.pc = 1
            return _sent
        choice = _sent
    elif _pc == 1:
        _pc = 0
        choice = _sent
    steps.stun(game, choice[0])
    return None
  return _kfr_inka_the_spider_effect


def _kfmk_kindrith_longshot_after_reap(_kfN, _kfR):
  def _kfr_kindrith_longshot_after_reap(game=_kf_U, card=_kf_U, *, _kfF=None, _sent=None, _kf_closure=None):
    # effects/named/untamed.py:498 kindrith_longshot_after_reap
    if _kfF is None:  # a fresh call: Python bound the arguments
        choice = options = _kf_U
        _pc = 0
    else:  # resuming a suspended frame
        (game, card, choice, options,) = _kfF.L
        _pc = _kfF.pc
    if not _pc:
        options = game.all_creatures('any', card)
        if not options:
            steps.shortfall(game, card, 'deals no damage: there is no creature in play', 'No creature')
            return
    if not _pc:
        _sent = _kf_step(game.choose_cards)(card.controller, f'{card.name}: deal 2 damage to a creature', options, 1, 1, source_card=card, intent=DecisionIntent.DAMAGE, affects=Affects.ANY)
        if type(_sent) is _kf_S:
            if _kfF is None:
                _kfF = _kf_Frame(_kfR, [game, card, choice, options])
                _kfF.pc = 1
                _sent.frames.append(_kfF)
            else:
                _kfF.L = [game, card, choice, options]
                _kfF.pc = 1
            return _sent
        choice = _sent
    elif _pc == 1:
        _pc = 0
        choice = _sent
    if not _pc:
        steps.deal_damage(game, choice[0], 2)
    if not _pc:
        _sent = _kf_step(game.check_destroyed)(choice)
        if type(_sent) is _kf_S:
            if _kfF is None:
                _kfF = _kf_Frame(_kfR, [game, card, choice, options])
                _kfF.pc = 2
                _sent.frames.append(_kfF)
            else:
                _kfF.L = [game, card, choice, options]
                _kfF.pc = 2
            return _sent
    elif _pc == 2:
        _pc = 0
    return None
  return _kfr_kindrith_longshot_after_reap


def _kfmk_lupo_the_scarred_play(_kfN, _kfR):
  def _kfr_lupo_the_scarred_play(game=_kf_U, card=_kf_U, *, _kfF=None, _sent=None, _kf_closure=None):
    # effects/named/untamed.py:511 lupo_the_scarred_play
    if _kfF is None:  # a fresh call: Python bound the arguments
        choice = options = _kf_U
        _pc = 0
    else:  # resuming a suspended frame
        (game, card, choice, options,) = _kfF.L
        _pc = _kfF.pc
    if not _pc:
        options = opponent_of(game, card).play_area.creatures
        if not options:
            steps.shortfall(game, card, 'deals no damage: there is no enemy creature in play', 'No enemy creature')
            return
    if not _pc:
        _sent = _kf_step(game.choose_cards)(card.controller, f'{card.name}: choose an enemy creature', options, 1, 1, source_card=card, intent=DecisionIntent.DAMAGE, affects=Affects.ENEMY)
        if type(_sent) is _kf_S:
            if _kfF is None:
                _kfF = _kf_Frame(_kfR, [game, card, choice, options])
                _kfF.pc = 1
                _sent.frames.append(_kfF)
            else:
                _kfF.L = [game, card, choice, options]
                _kfF.pc = 1
            return _sent
        choice = _sent
    elif _pc == 1:
        _pc = 0
        choice = _sent
    if not _pc:
        steps.deal_damage(game, choice[0], 2)
    if not _pc:
        _sent = _kf_step(game.check_destroyed)(choice)
        if type(_sent) is _kf_S:
            if _kfF is None:
                _kfF = _kf_Frame(_kfR, [game, card, choice, options])
                _kfF.pc = 2
                _sent.frames.append(_kfF)
            else:
                _kfF.L = [game, card, choice, options]
                _kfF.pc = 2
            return _sent
    elif _pc == 2:
        _pc = 0
    return None
  return _kfr_lupo_the_scarred_play


def _kfmk_piranha_monkeys_effect(_kfN, _kfR):
  def _kfr_piranha_monkeys_effect(game=_kf_U, card=_kf_U, *, _kfF=None, _sent=None, _kf_closure=None):
    # effects/named/untamed.py:551 piranha_monkeys_effect
    if _kfF is None:  # a fresh call: Python bound the arguments
        t = targets = _kf_U
        _pc = 0
    else:  # resuming a suspended frame
        (game, card, t, targets,) = _kfF.L
        _pc = _kfF.pc
    if not _pc:
        targets = [c for c in game.all_creatures('any', card) if c is not card]
        if not targets:
            steps.shortfall(game, card, 'deals no damage: there is no other creature in play', 'No other creature')
            return
        for t in targets:
            steps.deal_damage(game, t, 2)
    if not _pc:
        _sent = _kf_step(game.check_destroyed)(targets)
        if type(_sent) is _kf_S:
            if _kfF is None:
                _kfF = _kf_Frame(_kfR, [game, card, t, targets])
                _kfF.pc = 1
                _sent.frames.append(_kfF)
            else:
                _kfF.L = [game, card, t, targets]
                _kfF.pc = 1
            return _sent
    elif _pc == 1:
        _pc = 0
    return None
  return _kfr_piranha_monkeys_effect


def _kfmk_teliga_register__handler(_kfN, _kfR):
  def _kfr_teliga_register__handler(g=_kf_U, event=_kf_U, *, _kfF=None, _sent=None, _kf_closure=None):
    # effects/named/untamed.py:562 teliga_register.<locals>.handler
    if _kfF is None:  # a fresh call: Python bound the arguments
        _kfc_card = _kf_closure[0]
        _pc = 0
    else:  # resuming a suspended frame
        (g, event, _kfc_card,) = _kfF.L
        _pc = _kfF.pc
    if not _pc:
        if event['player'] != _kfc_card.cell_contents.controller and event['card'].type == CardType.CREATURE:
            steps.gain(g, g.players[_kfc_card.cell_contents.controller], 1)
        return
    if not _pc:
        _kfd = _kf_S(None)
        if _kfF is None:
            _kfF = _kf_Frame(_kfR, [g, event, _kfc_card])
            _kfF.pc = 1
            _kfd.frames.append(_kfF)
        else:
            _kfF.L = [g, event, _kfc_card]
            _kfF.pc = 1
        return _kfd
    elif _pc == 1:
        _pc = 0
    return None
  return _kfr_teliga_register__handler


def _kfmk_hunting_witch_register__handler(_kfN, _kfR):
  def _kfr_hunting_witch_register__handler(g=_kf_U, event=_kf_U, *, _kfF=None, _sent=None, _kf_closure=None):
    # effects/named/untamed.py:572 hunting_witch_register.<locals>.handler
    if _kfF is None:  # a fresh call: Python bound the arguments
        played = _kf_U
        _kfc_card = _kf_closure[0]
        _pc = 0
    else:  # resuming a suspended frame
        (g, event, played, _kfc_card,) = _kfF.L
        _pc = _kfF.pc
    if not _pc:
        played = event['card']
        if event['player'] == _kfc_card.cell_contents.controller and played is not _kfc_card.cell_contents and (played.type == CardType.CREATURE):
            steps.gain(g, g.players[_kfc_card.cell_contents.controller], 1)
        return
    if not _pc:
        _kfd = _kf_S(None)
        if _kfF is None:
            _kfF = _kf_Frame(_kfR, [g, event, played, _kfc_card])
            _kfF.pc = 1
            _kfd.frames.append(_kfF)
        else:
            _kfF.L = [g, event, played, _kfc_card]
            _kfF.pc = 1
        return _kfd
    elif _pc == 1:
        _pc = 0
    return None
  return _kfr_hunting_witch_register__handler


def _kfmk_witch_of_the_eye_after_reap(_kfN, _kfR):
  def _kfr_witch_of_the_eye_after_reap(game=_kf_U, card=_kf_U, *, _kfF=None, _sent=None, _kf_closure=None):
    # effects/named/untamed.py:582 witch_of_the_eye_after_reap
    if _kfF is None:  # a fresh call: Python bound the arguments
        choice = options = player = target = _kf_U
        _pc = 0
    else:  # resuming a suspended frame
        (game, card, choice, options, player, target,) = _kfF.L
        _pc = _kfF.pc
    if not _pc:
        player = controller_of(game, card)
        options = [c for c in player.discard.cards() if c is not card]
        if not options:
            steps.shortfall(game, card, 'returns nothing: your discard pile is empty', 'Discard pile is empty')
            return
    if not _pc:
        _sent = _kf_step(game.choose_cards)(player.id, f'{card.name}: choose a card to return to your hand', options, 1, 1, source_card=card, intent=DecisionIntent.RETURN_TO_HAND, affects=Affects.FRIENDLY)
        if type(_sent) is _kf_S:
            if _kfF is None:
                _kfF = _kf_Frame(_kfR, [game, card, choice, options, player, target])
                _kfF.pc = 1
                _sent.frames.append(_kfF)
            else:
                _kfF.L = [game, card, choice, options, player, target]
                _kfF.pc = 1
            return _sent
        choice = _sent
    elif _pc == 1:
        _pc = 0
        choice = _sent
    target = choice[0]
    player.discard.remove(target)
    player.hand.add(target)
    game.log.add('return_to_hand', card=target.name, iid=target.instance_id, owner=player.id)
    return None
  return _kfr_witch_of_the_eye_after_reap


# (qualname, first line, routine factory, slots, free variables, nested code (name, line),
#  line of each resume id, (exception slot, resume ids inside a try region) or None)
ROUTINES = [
    ('cooperative_hunting', 15, _kfmk_cooperative_hunting, ('game', 'card', 'choice', 'hit', 'i', 'n', 'options', 'player', '_kfs0', '_kfi1'), (), (), {1: 26, 2: 32}, None),
    ('curiosity', 35, _kfmk_curiosity, ('game', 'card', 'targets'), (), (), {1: 40}, None),
    ('fertility_chant', 43, _kfmk_fertility_chant, ('game', 'card'), (), (), {1: 46}, None),
    ('full_moon', 49, _kfmk_full_moon, ('game', '_kfc_card', 'handler'), (), (('handler', 50),), {1: 58}, None),
    ('full_moon.<locals>.handler', 50, _kfmk_full_moon__handler, ('g', 'event', '_kfc_card'), ('card',), (), {1: 54}, None),
    ('grasping_vines', 61, _kfmk_grasping_vines, ('game', 'card', 'a', 'choice', 'options', 'player'), (), (), {1: 67}, None),
    ('_lose_one_then_maybe_forge', 75, _kfmk__lose_one_then_maybe_forge, ('game', 'card', 'do_it', 'player'), (), (), {1: 79, 2: 84}, None),
    ('key_charge', 87, _kfmk_key_charge, ('game', 'card'), (), (), {1: 88}, None),
    ('lifeweb', 91, _kfmk_lifeweb, ('game', 'card', 'n', 'opponent', 'player'), (), (), {1: 100}, None),
    ('lost_in_the_woods', 103, _kfmk_lost_in_the_woods, ('game', 'card', 'area', 'c', 'enemy_choice', 'enemy_options', 'friendly_choice', 'friendly_options', 'n', 'opponent', 'owner', 'player'), (), (), {1: 114, 2: 122}, None),
    ('mimicry_play', 138, _kfmk_mimicry_play, ('game', 'card', 'choice', 'copied', 'opponent', 'options', 'player'), (), (), {1: 147, 2: 160}, None),
    ('natures_call', 163, _kfmk_natures_call, ('game', 'card', 'c', 'choice', 'options'), (), (), {1: 168}, None),
    ('nocturnal_maneuver', 176, _kfmk_nocturnal_maneuver, ('game', 'card', 'c', 'choice', 'options'), (), (), {1: 181}, None),
    ('perilous_wild', 189, _kfmk_perilous_wild, ('game', 'card', 'targets'), (), (), {1: 194}, None),
    ('regrowth', 197, _kfmk_regrowth, ('game', 'card', 'choice', 'options', 'player', 'target'), (), (), {1: 203}, None),
    ('save_the_pack', 213, _kfmk_save_the_pack, ('game', 'card', 'player', 'targets'), (), (), {1: 216}, None),
    ('scout', 222, _kfmk_scout, ('game', 'card', 'c', 'choice', '_kfc_chosen_ids', 'mod', 'options', 'player', '_kfs0', '_kfi1'), (), (('mod', 236),), {1: 228, 2: 242}, None),
    ('stampede', 245, _kfmk_stampede, ('game', 'card', 'player', 'total_uses'), (), (), {1: 257}, None),
    ('the_common_cold', 260, _kfmk_the_common_cold, ('game', 'card', 'destroyed', 'do_it', 'remaining_mars', 't', 'targets'), (), (), {1: 264, 2: 268, 3: 272}, None),
    ('troop_call', 275, _kfmk_troop_call, ('game', 'card', 'c', 'from_discard', 'from_play', 'player'), (), (), {1: 289}, None),
    ('vigor', 292, _kfmk_vigor, ('game', 'card', 'choice', 'healed', 'options'), (), (), {1: 297}, None),
    ('word_of_returning', 306, _kfmk_word_of_returning, ('game', 'card', 'n', 'opponent', 't', 'targets', 'total_returned'), (), (), {1: 320}, None),
    ('bear_flute', 325, _kfmk_bear_flute, ('game', 'card', 'bears_in_play', 'c', 'choice', 'found', 'player', 'remaining_discard', 'target'), (), (), {1: 336}, None),
    ('nepenthe_seed', 359, _kfmk_nepenthe_seed, ('game', 'card', 'choice', 'options', 'player', 'target'), (), (), {1: 361, 2: 365}, None),
    ('ritual_of_balance', 375, _kfmk_ritual_of_balance, ('game', 'card', 'opponent'), (), (), {1: 382}, None),
    ('ritual_of_the_hunt', 385, _kfmk_ritual_of_the_hunt, ('game', 'card', 'c', 'player'), (), (), {1: 387}, None),
    ('world_tree', 394, _kfmk_world_tree, ('game', 'card', 'choice', 'options', 'player', 'target'), (), (), {1: 400}, None),
    ('bigtwig_after_reap', 412, _kfmk_bigtwig_after_reap, ('game', 'card', 'choice', 'options', 'target'), (), (), {1: 417}, None),
    ('witch_of_the_wilds_register.<locals>.handler', 427, _kfmk_witch_of_the_wilds_register__handler, ('g', 'event', 'player', '_kfc_card'), ('card',), (), {1: 436}, None),
    ('chota_hazri', 441, _kfmk_chota_hazri, ('game', 'card'), (), (), {1: 442}, None),
    ('flaxia', 445, _kfmk_flaxia, ('game', 'card', 'opponent', 'player'), (), (), {1: 453}, None),
    ('giant_sloth_register.<locals>.handler', 457, _kfmk_giant_sloth_register__handler, ('g', 'event', '_kfc_card'), ('card',), (), {1: 461}, None),
    ('giant_sloth_action', 470, _kfmk_giant_sloth_action, ('game', 'card'), (), (), {1: 473}, None),
    ('inka_the_spider_effect', 486, _kfmk_inka_the_spider_effect, ('game', 'card', 'choice', 'options'), (), (), {1: 491}, None),
    ('kindrith_longshot_after_reap', 498, _kfmk_kindrith_longshot_after_reap, ('game', 'card', 'choice', 'options'), (), (), {1: 503, 2: 508}, None),
    ('lupo_the_scarred_play', 511, _kfmk_lupo_the_scarred_play, ('game', 'card', 'choice', 'options'), (), (), {1: 516, 2: 521}, None),
    ('piranha_monkeys_effect', 551, _kfmk_piranha_monkeys_effect, ('game', 'card', 't', 'targets'), (), (), {1: 558}, None),
    ('teliga_register.<locals>.handler', 562, _kfmk_teliga_register__handler, ('g', 'event', '_kfc_card'), ('card',), (), {1: 566}, None),
    ('hunting_witch_register.<locals>.handler', 572, _kfmk_hunting_witch_register__handler, ('g', 'event', 'played', '_kfc_card'), ('card',), (), {1: 577}, None),
    ('witch_of_the_eye_after_reap', 582, _kfmk_witch_of_the_eye_after_reap, ('game', 'card', 'choice', 'options', 'player', 'target'), (), (), {1: 588}, None),
]
