"""Generated by tools/compile_engine.py from keyforge/effects/steps.py -- do not edit.

Each pausing function of the source, as a routine for keyforge/vm.py's Machine:
`_kfr_*` runs it from a frame's pc, `_kfb_*` binds a call into a frame's locals.
"""

# fmt: off
# flake8: noqa
SOURCE = 'keyforge/effects/steps.py'
SOURCE_SHA256 = '89d9244453ec6c0cae509aa60d23a44f3527b05b6e5390d933a9b3d3c04fa766'

# Placeholder defaults: the loader rebuilds every function here in the source module's globals,
# with the original function's own defaults.
_kf_U = None


def _kfr_discard_from_hand(F, _sent, _kfN):
    # effects/steps.py:145 discard_from_hand
    (game, player, card,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 145
            if not player.hand.remove(card):
                return (3, False)
            player.discard.push(card)
            game.log.add('discard', player=player.id, card=card.name, iid=card.instance_id)
            _kff = game._fire_event
            _kfa = ('card_discarded_from_hand', {'player': player.id, 'card': card},)
            _kfk = None
            F.L = [game, player, card]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 150
            return (3, True)
            return (3, None)

def _kfb_discard_from_hand(game, player, card):
    return [game, player, card]


def _kfr_discard_random(F, _sent, _kfN):
    # effects/steps.py:154 discard_random
    (game, player, source, card, cards,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 154
            cards = player.hand.cards()
            if not cards:
                if source is not None:
                    shortfall(game, source, f'discards nothing: {{pos:{player.id}}} hand is empty', 'Hand is empty')
                return (3, False)
            card = portable_choice(game.event_rng('random_discard', player.id), cards)
            player.hand.remove(card)
            player.discard.push(card)
            game.log.add('discard_random', player=player.id, card=card.name, iid=card.instance_id)
            _kff = game._fire_event
            _kfa = ('card_discarded_from_hand', {'player': player.id, 'card': card},)
            _kfk = None
            F.L = [game, player, source, card, cards]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 164
            return (3, True)
            return (3, None)

def _kfb_discard_random(game, player, source=_kf_U):
    return [game, player, source, _kf_U, _kf_U]


def _kfr_sacrifice(F, _sent, _kfN):
    # effects/steps.py:290 sacrifice
    (game, card, destroyed,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 290
            'Destroy a card in play (sacrifice uses the same Destroy pipeline).'
            if game.find_play_area(card) is None:
                return (3, False)
            _kff = game.destroy_cards
            _kfa = ([card],)
            _kfk = None
            F.L = [game, card, destroyed]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 294
            destroyed = _sent
            return (3, card in destroyed)
            return (3, None)

def _kfb_sacrifice(game, card):
    return [game, card, _kf_U]


def _kfr_use_creature(F, _sent, _kfN):
    # effects/steps.py:330 use_creature
    (game, card,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 330
            'Reap, fight, or use the Action of a friendly creature, whichever is\n    possible and legal (ignoring house). Generator: may need a fight target.'
            _kff = game.use_creature_ability
            _kfa = (card,)
            _kfk = None
            F.L = [game, card]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 333
            return (3, True)
            return (3, None)

def _kfb_use_creature(game, card):
    return [game, card]


# (qualname, first line, step, binder, slots, freevar slots, nested code (name, line), line of each pc)
ROUTINES = [
    ('discard_from_hand', 145, _kfr_discard_from_hand, _kfb_discard_from_hand, ('game', 'player', 'card'), (), (), {0: 145, 1: 150}),
    ('discard_random', 154, _kfr_discard_random, _kfb_discard_random, ('game', 'player', 'source', 'card', 'cards'), (), (), {0: 154, 1: 164}),
    ('sacrifice', 290, _kfr_sacrifice, _kfb_sacrifice, ('game', 'card', 'destroyed'), (), (), {0: 290, 1: 294}),
    ('use_creature', 330, _kfr_use_creature, _kfb_use_creature, ('game', 'card'), (), (), {0: 330, 1: 333}),
]
