"""Generated by tools/compile_engine.py from keyforge/effects/named/brobnar.py -- do not edit.

Each pausing function of the source, as a routine for keyforge/vm.py's Machine:
`_kfr_*` runs it from a frame's pc, `_kfb_*` binds a call into a frame's locals.
"""

# fmt: off
# flake8: noqa
SOURCE = 'keyforge/effects/named/brobnar.py'
SOURCE_SHA256 = '158b3cc0a67144100c9b7833c0704cfe69ecc5667cc821c2df35c3ce508c6422'

# Placeholder defaults: the loader rebuilds every function here in the source module's globals,
# with the original function's own defaults.
_kf_U = None


def _kfr_anger(F, _sent, _kfN):
    # effects/named/brobnar.py:15 anger
    (game, card, choice, creatures, player,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 15
            player = controller_of(game, card)
            creatures = player.play_area.creatures
            if not creatures:
                steps.shortfall(game, card, 'does nothing: there is no friendly creature in play', 'No creature')
                return (3, None)
            _kff = game.choose_cards
            _kfa = (player.id, f'{card.name}: choose a friendly creature to ready and fight with', creatures, 1, 1,)
            _kfk = {'source_card': card, 'intent': DecisionIntent.READY, 'affects': Affects.FRIENDLY}
            F.L = [game, card, choice, creatures, player]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 21
            choice = _sent
            _kff = game.ready_and_fight
            _kfa = (choice[0],)
            _kfk = None
            F.L = [game, card, choice, creatures, player]
            F.pc = 2
            return (1, _kff, _kfa, _kfk)
        elif _pc == 2:  # line 25
            return (3, None)

def _kfb_anger(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U]


def _kfr_barehanded(F, _sent, _kfN):
    # effects/named/brobnar.py:28 barehanded
    (game, card, a, area, artifacts, order, owner,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 28
            artifacts = list(game.players[1].play_area.artifacts) + list(game.players[2].play_area.artifacts)
            if not artifacts:
                steps.shortfall(game, card, 'does nothing: there are no artifacts in play', 'No artifacts')
                return (3, None)
            order = artifacts
            _pc = 1 if len(artifacts) > 1 else 2
            continue
        elif _pc == 1:  # line 35
            _kff = game.order_effects
            _kfa = (card.controller, artifacts, f"{card.name}: choose the order these go to their decks' tops",)
            _kfk = {'source_card': card}
            F.L = [game, card, a, area, artifacts, order, owner]
            F.pc = 4
            return (1, _kff, _kfa, _kfk)
        elif _pc == 2:  # line 34
            _pc = 3
            continue
        elif _pc == 3:  # line 34
            for a in order:
                owner = game.players[a.owner]
                area = game.find_play_area(a)
                if area is not None:
                    area.remove(a)
                    game.leave_play(a)
                owner.deck.put_on_top(a)
                game.log.add('put_on_top', player=owner.id, card=a.name, iid=a.instance_id)
            return (3, None)
        elif _pc == 4:  # line 35
            order = _sent
            _pc = 3
            continue

def _kfb_barehanded(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U, _kf_U, _kf_U]


def _kfr_blood_money(F, _sent, _kfN):
    # effects/named/brobnar.py:49 blood_money
    (game, card, choice, opponent, options,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 49
            opponent = opponent_of(game, card)
            options = list(opponent.play_area.creatures)
            if not options:
                steps.shortfall(game, card, 'places nothing: there is no enemy creature in play', 'No enemy creature')
                return (3, None)
            _kff = game.choose_cards
            _kfa = (card.controller, f'{card.name}: choose an enemy creature', options, 1, 1,)
            _kfk = {'source_card': card, 'intent': DecisionIntent.CAPTURE, 'affects': Affects.ENEMY}
            F.L = [game, card, choice, opponent, options]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 55
            choice = _sent
            steps.place_aember(game, choice[0], 2)
            return (3, None)

def _kfb_blood_money(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U]


def _kfr_brothers_in_battle(F, _sent, _kfN):
    # effects/named/brobnar.py:62 brothers_in_battle
    (game, card, chosen, player,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 62
            player = controller_of(game, card)
            _kff = game.choose_house
            _kfa = (player.id, f'{card.name}: choose a house', list(House),)
            _kfk = None
            F.L = [game, card, chosen, player]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 64
            chosen = _sent
            game.active_effects.add(DurationEffect(card, player.id, 1, player.id, 'FightPermittedHouse', 'add', chosen))
            game.log.add('duration_effect', card=card.name, iid=card.instance_id, variable='FightPermittedHouse', op='add', value=chosen.value, player=player.id, affected=[player.id])
            return (3, None)

def _kfb_brothers_in_battle(game, card):
    return [game, card, _kf_U, _kf_U]


def _kfr_burn_the_stockpile(F, _sent, _kfN):
    # effects/named/brobnar.py:72 burn_the_stockpile
    (game, card, opponent,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 72
            opponent = opponent_of(game, card)
            if opponent.aember >= 7:
                steps.lose(game, opponent, 4)
            else:
                steps.shortfall(game, card, f'does nothing: {{pos:{opponent.id}}} Æmber is below 7', 'Opponent below 7')
            return (3, None)
            _kfd = None
            F.L = [game, card, opponent]
            F.pc = 1
            return (2, _kfd)
        elif _pc == 1:  # line 79
            return (3, None)

def _kfb_burn_the_stockpile(game, card):
    return [game, card, _kf_U]


def _kfr_champions_challenge(F, _sent, _kfN):
    # effects/named/brobnar.py:82 champions_challenge
    (game, card, enemy_creatures, friendly_creatures, opponent, player, survivor_enemy, survivor_friendly,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 82
            player = controller_of(game, card)
            opponent = opponent_of(game, card)
            enemy_creatures = list(opponent.play_area.creatures)
            _kff = choose_most_powerful
            _kfa = (game, player.id, enemy_creatures, f'{card.name}: choose the enemy creature to survive (most powerful)',)
            _kfk = {'source_card': card}
            F.L = [game, card, enemy_creatures, friendly_creatures, opponent, player, survivor_enemy, survivor_friendly]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 87
            survivor_enemy = _sent
            _kff = game.destroy_cards
            _kfa = ([c for c in enemy_creatures if c is not survivor_enemy],)
            _kfk = None
            F.L = [game, card, enemy_creatures, friendly_creatures, opponent, player, survivor_enemy, survivor_friendly]
            F.pc = 2
            return (1, _kff, _kfa, _kfk)
        elif _pc == 2:  # line 91
            friendly_creatures = list(player.play_area.creatures)
            _kff = choose_most_powerful
            _kfa = (game, player.id, friendly_creatures, f'{card.name}: choose the friendly creature to survive (most powerful)',)
            _kfk = {'source_card': card}
            F.L = [game, card, enemy_creatures, friendly_creatures, opponent, player, survivor_enemy, survivor_friendly]
            F.pc = 3
            return (1, _kff, _kfa, _kfk)
        elif _pc == 3:  # line 94
            survivor_friendly = _sent
            _kff = game.destroy_cards
            _kfa = ([c for c in friendly_creatures if c is not survivor_friendly],)
            _kfk = None
            F.L = [game, card, enemy_creatures, friendly_creatures, opponent, player, survivor_enemy, survivor_friendly]
            F.pc = 4
            return (1, _kff, _kfa, _kfk)
        elif _pc == 4:  # line 98
            _pc = 5 if survivor_friendly is not None and (not survivor_friendly.destroyed) else 6
            continue
        elif _pc == 5:  # line 101
            _kff = game.ready_and_fight
            _kfa = (survivor_friendly,)
            _kfk = None
            F.L = [game, card, enemy_creatures, friendly_creatures, opponent, player, survivor_enemy, survivor_friendly]
            F.pc = 8
            return (1, _kff, _kfa, _kfk)
        elif _pc == 6:  # line 100
            _pc = 7
            continue
        elif _pc == 7:  # line 100
            return (3, None)
        elif _pc == 8:  # line 101
            _pc = 7
            continue

def _kfb_champions_challenge(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U, _kf_U, _kf_U, _kf_U]


def _kfr_cowards_end(F, _sent, _kfN):
    # effects/named/brobnar.py:104 cowards_end
    (game, card, player, targets,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 104
            player = controller_of(game, card)
            targets = [c for c in game.all_creatures('any', card) if c.type_object.damage == 0]
            _kff = game.destroy_cards
            _kfa = (targets,)
            _kfk = None
            F.L = [game, card, player, targets]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 107
            if not targets:
                steps.shortfall(game, card, 'destroys nothing: every creature in play already has damage on it', 'No undamaged creature')
            steps.gain_chains(game, player, card, 3)
            return (3, None)

def _kfb_cowards_end(game, card):
    return [game, card, _kf_U, _kf_U]


def _kfr_follow_the_leader(F, _sent, _kfN):
    # effects/named/brobnar.py:113 follow_the_leader
    (game, card, player,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 113
            player = controller_of(game, card)
            game.active_effects.add(DurationEffect(card, player.id, 1, player.id, 'FightPermittedHouse', 'add', True))
            game.log.add('duration_effect', card=card.name, iid=card.instance_id, variable='FightPermittedHouse', op='add', value='any house', player=player.id, affected=[player.id])
            return (3, None)
            _kfd = None
            F.L = [game, card, player]
            F.pc = 1
            return (2, _kfd)
        elif _pc == 1:  # line 121
            return (3, None)

def _kfb_follow_the_leader(game, card):
    return [game, card, _kf_U]


def _kfr__grant_gain_on_enemy_destroyed_this_turn__handler(F, _sent, _kfN):
    # effects/named/brobnar.py:125 _grant_gain_on_enemy_destroyed_this_turn.<locals>.handler
    (g, event, _kfc_card,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 125
            if event['card'].controller != _kfc_card.cell_contents.controller:
                steps.gain(g, g.players[_kfc_card.cell_contents.controller], 1)
            return (3, None)
            _kfd = None
            F.L = [g, event, _kfc_card]
            F.pc = 1
            return (2, _kfd)
        elif _pc == 1:  # line 129
            return (3, None)

def _kfb__grant_gain_on_enemy_destroyed_this_turn__handler(g, event):
    return [g, event, _kf_U]


def _kfr_loot_the_bodies(F, _sent, _kfN):
    # effects/named/brobnar.py:134 loot_the_bodies
    (game, card,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 134
            _grant_gain_on_enemy_destroyed_this_turn(game, card)
            return (3, None)
            _kfd = None
            F.L = [game, card]
            F.pc = 1
            return (2, _kfd)
        elif _pc == 1:  # line 137
            return (3, None)

def _kfb_loot_the_bodies(game, card):
    return [game, card]


def _kfr_take_that_smartypants(F, _sent, _kfN):
    # effects/named/brobnar.py:140 take_that_smartypants
    (game, card, a, c, logos_count, opponent,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 140
            opponent = opponent_of(game, card)
            logos_count = 0
            for c in opponent.play_area.creatures:
                if c.house == House.LOGOS:
                    logos_count += 1
                logos_count += sum((1 for u in c.type_object.upgrades if u.house == House.LOGOS))
            for a in opponent.play_area.artifacts:
                if a.house == House.LOGOS:
                    logos_count += 1
            if logos_count >= 3:
                steps.steal(game, opponent, controller_of(game, card), 2, source=card)
            else:
                steps.shortfall(game, card, f'steals nothing: {{pos:{opponent.id}}} has fewer than 3 Logos cards in play', 'Not enough Logos cards')
            return (3, None)
            _kfd = None
            F.L = [game, card, a, c, logos_count, opponent]
            F.pc = 1
            return (2, _kfd)
        elif _pc == 1:  # line 155
            return (3, None)

def _kfb_take_that_smartypants(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U, _kf_U]


def _kfr_relentless_assault(F, _sent, _kfN):
    # effects/named/brobnar.py:158 relentless_assault
    (game, card, available, choice, cont, i, player, target, used, _kfs0, _kfi1,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 158
            player = controller_of(game, card)
            used = []
            _kfs0 = _kf_seq(range(3))
            _kfi1 = 0
            _pc = 1
            continue
        elif _pc == 1:  # line 161
            _pc = 2 if _kfi1 < len(_kfs0) else 3
            continue
        elif _pc == 2:  # line 162
            i = _kfs0[_kfi1]
            _kfi1 += 1
            available = [c for c in player.play_area.creatures if c not in used]
            _pc = 4 if not available else 5
            continue
        elif _pc == 3:  # line 161
            return (3, None)
        elif _pc == 4:  # line 164
            _pc = 3
            continue
        elif _pc == 5:  # line 163
            _pc = 6
            continue
        elif _pc == 6:  # line 163
            _pc = 7 if i > 0 else 8
            continue
        elif _pc == 7:  # line 166
            _kff = game.yes_no
            _kfa = (player.id, f'{card.name}: ready and fight with another creature?',)
            _kfk = {'source_card': card, 'intent': DecisionIntent.OPTIONAL_TRIGGER}
            F.L = [game, card, available, choice, cont, i, player, target, used, _kfs0, _kfi1]
            F.pc = 10
            return (1, _kff, _kfa, _kfk)
        elif _pc == 8:  # line 165
            _pc = 9
            continue
        elif _pc == 9:  # line 165
            _kff = game.choose_cards
            _kfa = (player.id, f'{card.name}: choose a friendly creature to ready and fight with', available, 1, 1,)
            _kfk = {'source_card': card, 'intent': DecisionIntent.READY, 'affects': Affects.FRIENDLY}
            F.L = [game, card, available, choice, cont, i, player, target, used, _kfs0, _kfi1]
            F.pc = 14
            return (1, _kff, _kfa, _kfk)
        elif _pc == 10:  # line 166
            cont = _sent
            _pc = 11 if not cont else 12
            continue
        elif _pc == 11:  # line 171
            _pc = 3
            continue
        elif _pc == 12:  # line 170
            _pc = 13
            continue
        elif _pc == 13:  # line 170
            _pc = 9
            continue
        elif _pc == 14:  # line 172
            choice = _sent
            target = choice[0]
            used.append(target)
            _kff = game.ready_and_fight
            _kfa = (target,)
            _kfk = None
            F.L = [game, card, available, choice, cont, i, player, target, used, _kfs0, _kfi1]
            F.pc = 15
            return (1, _kff, _kfa, _kfk)
        elif _pc == 15:  # line 178
            _pc = 1
            continue

def _kfb_relentless_assault(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U, _kf_U, _kf_U, _kf_U, _kf_U, _kf_U, _kf_U]


def _kfr_smith(F, _sent, _kfN):
    # effects/named/brobnar.py:181 smith
    (game, card, opponent, player,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 181
            player = controller_of(game, card)
            opponent = opponent_of(game, card)
            if len(player.play_area.creatures) > len(opponent.play_area.creatures):
                steps.gain(game, player, 2)
            else:
                steps.shortfall(game, card, 'gains nothing: you do not control more creatures than your opponent', 'Not enough creatures')
            return (3, None)
            _kfd = None
            F.L = [game, card, opponent, player]
            F.pc = 1
            return (2, _kfd)
        elif _pc == 1:  # line 189
            return (3, None)

def _kfb_smith(game, card):
    return [game, card, _kf_U, _kf_U]


def _kfr_sound_the_horns(F, _sent, _kfN):
    # effects/named/brobnar.py:192 sound_the_horns
    (game, card, discarded, found, player, top,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 192
            player = controller_of(game, card)
            discarded = []
            found = None
            while not player.deck.is_empty():
                top = player.deck.draw_top()
                player.discard.push(top)
                discarded.append(top)
                game.log.add('discard', player=player.id, card=top.name, iid=top.instance_id)
                if top.type == CardType.CREATURE and top.house == House.BROBNAR:
                    found = top
                    break
            if found is not None:
                player.discard.remove(found)
                player.hand.add(found)
                game.log.add('return_to_hand', card=found.name, iid=found.instance_id, owner=player.id)
            elif not discarded:
                steps.shortfall(game, card, f'discards nothing: {{pos:{player.id}}} deck is empty', 'Deck is empty')
            else:
                steps.shortfall(game, card, f'discards {len(discarded)} card(s) but finds no Brobnar creature', 'No Brobnar creature found')
            return (3, None)
            _kfd = None
            F.L = [game, card, discarded, found, player, top]
            F.pc = 1
            return (2, _kfd)
        elif _pc == 1:  # line 213
            return (3, None)

def _kfb_sound_the_horns(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U, _kf_U]


def _kfr_tremor(F, _sent, _kfN):
    # effects/named/brobnar.py:216 tremor
    (game, card, area, choice, n, neighbors, options, target,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 216
            options = game.all_creatures('any', card)
            if not options:
                steps.shortfall(game, card, 'stuns nothing: there are no creatures in play', 'No creature')
                return (3, None)
            _kff = game.choose_cards
            _kfa = (card.controller, f'{card.name}: choose a creature to stun (with its neighbors)', options, 1, 1,)
            _kfk = {'source_card': card, 'intent': DecisionIntent.STUN, 'affects': Affects.ANY}
            F.L = [game, card, area, choice, n, neighbors, options, target]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 221
            choice = _sent
            target = choice[0]
            area = game.find_play_area(target)
            neighbors = area.neighbors(target) if area is not None else []
            steps.stun(game, target)
            for n in neighbors:
                steps.stun(game, n)
            return (3, None)

def _kfb_tremor(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U, _kf_U, _kf_U, _kf_U]


def _kfr_unguarded_camp(F, _sent, _kfN):
    # effects/named/brobnar.py:233 unguarded_camp
    (game, card, available, choice, excess, i, opponent, player, target, used, _kfs0, _kfi1,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 233
            player = controller_of(game, card)
            opponent = opponent_of(game, card)
            excess = len(player.play_area.creatures) - len(opponent.play_area.creatures)
            if excess <= 0:
                steps.shortfall(game, card, 'captures nothing: you do not have more creatures than your opponent', 'No excess creatures')
                return (3, None)
            used = []
            _kfs0 = _kf_seq(range(excess))
            _kfi1 = 0
            _pc = 1
            continue
        elif _pc == 1:  # line 241
            _pc = 2 if _kfi1 < len(_kfs0) else 3
            continue
        elif _pc == 2:  # line 242
            i = _kfs0[_kfi1]
            _kfi1 += 1
            available = [c for c in player.play_area.creatures if c not in used]
            _pc = 4 if not available else 5
            continue
        elif _pc == 3:  # line 241
            return (3, None)
        elif _pc == 4:  # line 244
            _pc = 3
            continue
        elif _pc == 5:  # line 243
            _pc = 6
            continue
        elif _pc == 6:  # line 243
            _kff = game.choose_cards
            _kfa = (player.id, f'{card.name}: choose a friendly creature to capture 1Æ ({i + 1}/{excess})', available, 1, 1,)
            _kfk = {'source_card': card, 'intent': DecisionIntent.CAPTURE, 'affects': Affects.FRIENDLY}
            F.L = [game, card, available, choice, excess, i, opponent, player, target, used, _kfs0, _kfi1]
            F.pc = 7
            return (1, _kff, _kfa, _kfk)
        elif _pc == 7:  # line 245
            choice = _sent
            target = choice[0]
            used.append(target)
            steps.capture(game, target, 1)
            _pc = 1
            continue

def _kfb_unguarded_camp(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U, _kf_U, _kf_U, _kf_U, _kf_U, _kf_U, _kf_U, _kf_U]


def _kfr_warsong(F, _sent, _kfN):
    # effects/named/brobnar.py:254 warsong
    (game, _kfc_card, handler,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 254
            handler = _kf_fn(_kfN[0], globals(), None, None, {'card': _kfc_card})
            game.active_effects.add(TriggerEffect(_kfc_card.cell_contents, _kfc_card.cell_contents.controller, 'fight_resolved', handler, remaining_duration=1))
            return (3, None)
            _kfd = None
            F.L = [game, _kfc_card, handler]
            F.pc = 1
            return (2, _kfd)
        elif _pc == 1:  # line 263
            return (3, None)

def _kfb_warsong(game, card):
    return [game, _kf_cell(card), _kf_U]


def _kfr_warsong__handler(F, _sent, _kfN):
    # effects/named/brobnar.py:255 warsong.<locals>.handler
    (g, event, _kfc_card,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 255
            if event['attacker'].controller == _kfc_card.cell_contents.controller:
                steps.gain(g, g.players[_kfc_card.cell_contents.controller], 1)
            return (3, None)
            _kfd = None
            F.L = [g, event, _kfc_card]
            F.pc = 1
            return (2, _kfd)
        elif _pc == 1:  # line 259
            return (3, None)

def _kfb_warsong__handler(g, event):
    return [g, event, _kf_U]


def _kfr_autocannon_register__handler(F, _sent, _kfN):
    # effects/named/brobnar.py:269 autocannon_register.<locals>.handler
    (g, event, entered,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 269
            entered = event['card']
            steps.deal_damage(g, entered, 1)
            _kff = g.check_destroyed
            _kfa = ([entered],)
            _kfk = None
            F.L = [g, event, entered]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 272
            return (3, None)

def _kfb_autocannon_register__handler(g, event):
    return [g, event, _kf_U]


def _kfr_gauntlet_of_command(F, _sent, _kfN):
    # effects/named/brobnar.py:284 gauntlet_of_command
    (game, card, choice, creatures, player,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 284
            player = controller_of(game, card)
            creatures = player.play_area.creatures
            if not creatures:
                steps.shortfall(game, card, 'has no friendly creature to ready and fight with', 'No creature')
                return (3, None)
            _kff = game.choose_cards
            _kfa = (player.id, f'{card.name}: choose a friendly creature to ready and fight with', creatures, 1, 1,)
            _kfk = {'source_card': card, 'intent': DecisionIntent.READY, 'affects': Affects.FRIENDLY}
            F.L = [game, card, choice, creatures, player]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 290
            choice = _sent
            _kff = game.ready_and_fight
            _kfa = (choice[0],)
            _kfk = None
            F.L = [game, card, choice, creatures, player]
            F.pc = 2
            return (1, _kff, _kfa, _kfk)
        elif _pc == 2:  # line 294
            return (3, None)

def _kfb_gauntlet_of_command(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U]


def _kfr_mighty_javelin(F, _sent, _kfN):
    # effects/named/brobnar.py:309 mighty_javelin
    (game, card, choice, options,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 309
            _kff = steps.sacrifice
            _kfa = (game, card,)
            _kfk = None
            F.L = [game, card, choice, options]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 310
            options = game.all_creatures('any', card)
            if not options:
                steps.shortfall(game, card, 'deals no damage: there is no creature in play', 'No creature')
                return (3, None)
            _kff = game.choose_cards
            _kfa = (card.controller, f'{card.name}: deal 4 damage to a creature', options, 1, 1,)
            _kfk = {'source_card': card, 'intent': DecisionIntent.DAMAGE, 'affects': Affects.ANY}
            F.L = [game, card, choice, options]
            F.pc = 2
            return (1, _kff, _kfa, _kfk)
        elif _pc == 2:  # line 315
            choice = _sent
            steps.deal_damage(game, choice[0], 4)
            _kff = game.check_destroyed
            _kfa = (choice,)
            _kfk = None
            F.L = [game, card, choice, options]
            F.pc = 3
            return (1, _kff, _kfa, _kfk)
        elif _pc == 3:  # line 320
            return (3, None)

def _kfb_mighty_javelin(game, card):
    return [game, card, _kf_U, _kf_U]


def _kfr_pile_of_skulls_register__handler(F, _sent, _kfN):
    # effects/named/brobnar.py:324 pile_of_skulls_register.<locals>.handler
    (g, event, choice, destroyed_card, friendly, _kfc_card,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 324
            destroyed_card = event['card']
            if destroyed_card.controller == _kfc_card.cell_contents.controller:
                return (3, None)
            if g.active_player_id != _kfc_card.cell_contents.controller:
                return (3, None)
            friendly = g.players[_kfc_card.cell_contents.controller].play_area.creatures
            if not friendly:
                return (3, None)
            _kff = g.choose_cards
            _kfa = (_kfc_card.cell_contents.controller, f'{_kfc_card.cell_contents.name}: choose a friendly creature to capture 1Æ', friendly, 1, 1,)
            _kfk = {'source_card': _kfc_card.cell_contents, 'intent': DecisionIntent.CAPTURE, 'affects': Affects.FRIENDLY}
            F.L = [g, event, choice, destroyed_card, friendly, _kfc_card]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 333
            choice = _sent
            steps.capture(g, choice[0], 1)
            return (3, None)

def _kfb_pile_of_skulls_register__handler(g, event):
    return [g, event, _kf_U, _kf_U, _kf_U, _kf_U]


def _kfr_screechbomb(F, _sent, _kfN):
    # effects/named/brobnar.py:342 screechbomb
    (game, card,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 342
            _kff = steps.sacrifice
            _kfa = (game, card,)
            _kfk = None
            F.L = [game, card]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 343
            steps.lose(game, opponent_of(game, card), 2)
            return (3, None)

def _kfb_screechbomb(game, card):
    return [game, card]


def _kfr_the_warchest(F, _sent, _kfN):
    # effects/named/brobnar.py:347 the_warchest
    (game, card, n, opponent,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 347
            opponent = opponent_of(game, card)
            n = game.creatures_destroyed_in_fight_this_turn(opponent.id)
            if not steps.gain(game, controller_of(game, card), n):
                steps.shortfall(game, card, 'gains nothing: no enemy creature was destroyed in a fight this turn', 'None destroyed in a fight')
            return (3, None)
            _kfd = None
            F.L = [game, card, n, opponent]
            F.pc = 1
            return (2, _kfd)
        elif _pc == 1:  # line 353
            return (3, None)

def _kfb_the_warchest(game, card):
    return [game, card, _kf_U, _kf_U]


def _kfr_bilgum_avalanche_register__handler(F, _sent, _kfN):
    # effects/named/brobnar.py:359 bilgum_avalanche_register.<locals>.handler
    (g, event, t, targets, _kfc_card,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 359
            if event.get('player') != _kfc_card.cell_contents.controller:
                return (3, None)
            targets = g.all_creatures('enemy', _kfc_card.cell_contents)
            for t in targets:
                steps.deal_damage(g, t, 2)
            _kff = g.check_destroyed
            _kfa = (targets,)
            _kfk = None
            F.L = [g, event, t, targets, _kfc_card]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 365
            return (3, None)

def _kfb_bilgum_avalanche_register__handler(g, event):
    return [g, event, _kf_U, _kf_U, _kf_U]


def _kfr_earthshaker(F, _sent, _kfN):
    # effects/named/brobnar.py:382 earthshaker
    (game, card, targets,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 382
            targets = [c for c in game.all_creatures('any', card) if game.get_power(c) <= 3]
            if not targets:
                steps.shortfall(game, card, 'destroys nothing: no creature has power 3 or lower', 'No low-power creature')
                return (3, None)
            _kff = game.destroy_cards
            _kfa = (targets,)
            _kfk = None
            F.L = [game, card, targets]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 387
            return (3, None)

def _kfb_earthshaker(game, card):
    return [game, card, _kf_U]


def _kfr_firespitter_before_fight(F, _sent, _kfN):
    # effects/named/brobnar.py:390 firespitter_before_fight
    (game, card, target, t, targets,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 390
            targets = game.all_creatures('enemy', card)
            for t in targets:
                steps.deal_damage(game, t, 1)
            return (3, None)
            _kfd = None
            F.L = [game, card, target, t, targets]
            F.pc = 1
            return (2, _kfd)
        elif _pc == 1:  # line 395
            return (3, None)

def _kfb_firespitter_before_fight(game, card, target):
    return [game, card, target, _kf_U, _kf_U]


def _kfr_ganger_chieftain_play(F, _sent, _kfN):
    # effects/named/brobnar.py:398 ganger_chieftain_play
    (game, card, area, choice, do_it, neighbors, player,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 398
            player = controller_of(game, card)
            area = player.play_area
            neighbors = area.neighbors(card)
            if not neighbors:
                return (3, None)
            _kff = game.yes_no
            _kfa = (player.id, f'{card.name}: ready and fight with a neighboring creature?',)
            _kfk = {'source_card': card, 'intent': DecisionIntent.OPTIONAL_TRIGGER}
            F.L = [game, card, area, choice, do_it, neighbors, player]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 404
            do_it = _sent
            if not do_it:
                return (3, None)
            _kff = game.choose_cards
            _kfa = (player.id, f'{card.name}: choose a neighboring creature', neighbors, 1, 1,)
            _kfk = {'source_card': card, 'intent': DecisionIntent.READY, 'affects': Affects.FRIENDLY}
            F.L = [game, card, area, choice, do_it, neighbors, player]
            F.pc = 2
            return (1, _kff, _kfa, _kfk)
        elif _pc == 2:  # line 410
            choice = _sent
            _kff = game.ready_and_fight
            _kfa = (choice[0],)
            _kfk = None
            F.L = [game, card, area, choice, do_it, neighbors, player]
            F.pc = 3
            return (1, _kff, _kfa, _kfk)
        elif _pc == 3:  # line 414
            return (3, None)

def _kfb_ganger_chieftain_play(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U, _kf_U, _kf_U]


def _kfr_hebe_the_huge(F, _sent, _kfN):
    # effects/named/brobnar.py:417 hebe_the_huge
    (game, card, t, targets,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 417
            targets = [c for c in game.all_creatures('any', card) if c is not card and c.type_object.damage == 0]
            if not targets:
                steps.shortfall(game, card, 'deals no damage: there is no other undamaged creature', 'No undamaged creature')
                return (3, None)
            for t in targets:
                steps.deal_damage(game, t, 2)
            _kff = game.check_destroyed
            _kfa = (targets,)
            _kfk = None
            F.L = [game, card, t, targets]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 424
            return (3, None)

def _kfb_hebe_the_huge(game, card):
    return [game, card, _kf_U, _kf_U]


def _kfr_kelifi_dragon_after(F, _sent, _kfN):
    # effects/named/brobnar.py:427 kelifi_dragon_after
    (game, card, choice, options,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 427
            steps.gain(game, controller_of(game, card), 1)
            options = game.all_creatures('any', card)
            if not options:
                steps.shortfall(game, card, 'deals no damage: there is no creature in play', 'No creature')
                return (3, None)
            _kff = game.choose_cards
            _kfa = (card.controller, f'{card.name}: deal 5 damage to a creature', options, 1, 1,)
            _kfk = {'source_card': card, 'intent': DecisionIntent.DAMAGE, 'affects': Affects.ANY}
            F.L = [game, card, choice, options]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 433
            choice = _sent
            steps.deal_damage(game, choice[0], 5)
            _kff = game.check_destroyed
            _kfa = (choice,)
            _kfk = None
            F.L = [game, card, choice, options]
            F.pc = 2
            return (1, _kff, _kfa, _kfk)
        elif _pc == 2:  # line 438
            return (3, None)

def _kfb_kelifi_dragon_after(game, card):
    return [game, card, _kf_U, _kf_U]


def _kfr_krump_on_destroyed_fighting(F, _sent, _kfN):
    # effects/named/brobnar.py:450 krump_on_destroyed_fighting
    (game, survivor, victim,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 450
            steps.lose(game, game.players[victim.controller], 1)
            return (3, None)
            _kfd = None
            F.L = [game, survivor, victim]
            F.pc = 1
            return (2, _kfd)
        elif _pc == 1:  # line 453
            return (3, None)

def _kfb_krump_on_destroyed_fighting(game, survivor, victim):
    return [game, survivor, victim]


def _kfr_lomir_flamefist(F, _sent, _kfN):
    # effects/named/brobnar.py:456 lomir_flamefist
    (game, card, opponent,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 456
            opponent = opponent_of(game, card)
            if opponent.aember >= 7:
                steps.lose(game, opponent, 2)
            else:
                steps.shortfall(game, card, f'does nothing: {{pos:{opponent.id}}} Æmber is below 7', 'Opponent below 7')
            return (3, None)
            _kfd = None
            F.L = [game, card, opponent]
            F.pc = 1
            return (2, _kfd)
        elif _pc == 1:  # line 463
            return (3, None)

def _kfb_lomir_flamefist(game, card):
    return [game, card, _kf_U]


def _kfr_mugwump_on_destroyed_fighting(F, _sent, _kfN):
    # effects/named/brobnar.py:466 mugwump_on_destroyed_fighting
    (game, survivor, victim,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 466
            steps.fully_heal(game, survivor)
            survivor.power_counters += 1
            return (3, None)
            _kfd = None
            F.L = [game, survivor, victim]
            F.pc = 1
            return (2, _kfd)
        elif _pc == 1:  # line 470
            return (3, None)

def _kfb_mugwump_on_destroyed_fighting(game, survivor, victim):
    return [game, survivor, victim]


def _kfr_pingle_who_annoys_register__handler(F, _sent, _kfN):
    # effects/named/brobnar.py:474 pingle_who_annoys_register.<locals>.handler
    (g, event, entered, _kfc_card,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 474
            entered = event['card']
            _pc = 1 if entered.controller != _kfc_card.cell_contents.controller else 2
            continue
        elif _pc == 1:  # line 477
            steps.deal_damage(g, entered, 1)
            _kff = g.check_destroyed
            _kfa = ([entered],)
            _kfk = None
            F.L = [g, event, entered, _kfc_card]
            F.pc = 4
            return (1, _kff, _kfa, _kfk)
        elif _pc == 2:  # line 476
            _pc = 3
            continue
        elif _pc == 3:  # line 476
            return (3, None)
        elif _pc == 4:  # line 478
            _pc = 3
            continue

def _kfb_pingle_who_annoys_register__handler(g, event):
    return [g, event, _kf_U, _kf_U]


def _kfr_rock_hurling_giant_register__handler(F, _sent, _kfN):
    # effects/named/brobnar.py:484 rock_hurling_giant_register.<locals>.handler
    (g, event, choice, discarded, do_it, options, _kfc_card,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 484
            if event['player'] != _kfc_card.cell_contents.controller or g.active_player_id != _kfc_card.cell_contents.controller:
                return (3, None)
            discarded = event['card']
            if discarded.house != House.BROBNAR:
                return (3, None)
            options = g.all_creatures('any', _kfc_card.cell_contents)
            if not options:
                return (3, None)
            _kff = g.yes_no
            _kfa = (_kfc_card.cell_contents.controller, f'{_kfc_card.cell_contents.name}: deal 4 damage to a creature?',)
            _kfk = {'source_card': _kfc_card.cell_contents, 'intent': DecisionIntent.OPTIONAL_TRIGGER}
            F.L = [g, event, choice, discarded, do_it, options, _kfc_card]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 493
            do_it = _sent
            if not do_it:
                return (3, None)
            _kff = g.choose_cards
            _kfa = (_kfc_card.cell_contents.controller, f'{_kfc_card.cell_contents.name}: choose a creature', options, 1, 1,)
            _kfk = {'source_card': _kfc_card.cell_contents, 'intent': DecisionIntent.DAMAGE, 'affects': Affects.ANY}
            F.L = [g, event, choice, discarded, do_it, options, _kfc_card]
            F.pc = 2
            return (1, _kff, _kfa, _kfk)
        elif _pc == 2:  # line 499
            choice = _sent
            steps.deal_damage(g, choice[0], 4)
            _kff = g.check_destroyed
            _kfa = (choice,)
            _kfk = None
            F.L = [g, event, choice, discarded, do_it, options, _kfc_card]
            F.pc = 3
            return (1, _kff, _kfa, _kfk)
        elif _pc == 3:  # line 504
            return (3, None)

def _kfb_rock_hurling_giant_register__handler(g, event):
    return [g, event, _kf_U, _kf_U, _kf_U, _kf_U, _kf_U]


def _kfr_rogue_ogre_register__handler(F, _sent, _kfN):
    # effects/named/brobnar.py:510 rogue_ogre_register.<locals>.handler
    (g, event, player, _kfc_card,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 510
            if event['player'] == _kfc_card.cell_contents.controller:
                player = g.players[_kfc_card.cell_contents.controller]
                if sum(player.CardsPlayed.values()) == 1:
                    steps.heal(g, _kfc_card.cell_contents, 2)
                    steps.capture(g, _kfc_card.cell_contents, 1)
            return (3, None)
            _kfd = None
            F.L = [g, event, player, _kfc_card]
            F.pc = 1
            return (2, _kfd)
        elif _pc == 1:  # line 517
            return (3, None)

def _kfb_rogue_ogre_register__handler(g, event):
    return [g, event, _kf_U, _kf_U]


def _kfr_smaaash(F, _sent, _kfN):
    # effects/named/brobnar.py:522 smaaash
    (game, card, choice, options,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 522
            options = game.all_creatures('any', card)
            if not options:
                steps.shortfall(game, card, 'stuns nothing: there are no creatures in play', 'No creature')
                return (3, None)
            _kff = game.choose_cards
            _kfa = (card.controller, f'{card.name}: choose a creature to stun', options, 1, 1,)
            _kfk = {'source_card': card, 'intent': DecisionIntent.STUN, 'affects': Affects.ANY}
            F.L = [game, card, choice, options]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 527
            choice = _sent
            steps.stun(game, choice[0])
            return (3, None)

def _kfb_smaaash(game, card):
    return [game, card, _kf_U, _kf_U]


def _kfr_tireless_crocag_play(F, _sent, _kfN):
    # effects/named/brobnar.py:534 tireless_crocag_play
    (game, card, opponent,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 534
            opponent = opponent_of(game, card)
            _pc = 1 if not opponent.play_area.creatures else 2
            continue
        elif _pc == 1:  # line 537
            _kff = game.destroy_cards
            _kfa = ([card],)
            _kfk = None
            F.L = [game, card, opponent]
            F.pc = 4
            return (1, _kff, _kfa, _kfk)
        elif _pc == 2:  # line 536
            _pc = 3
            continue
        elif _pc == 3:  # line 536
            return (3, None)
        elif _pc == 4:  # line 537
            _pc = 3
            continue

def _kfb_tireless_crocag_play(game, card):
    return [game, card, _kf_U]


def _kfr_tireless_crocag_register__handler(F, _sent, _kfN):
    # effects/named/brobnar.py:541 tireless_crocag_register.<locals>.handler
    (g, event, destroyed_card, opponent_id, _kfc_card,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 541
            destroyed_card = event['card']
            opponent_id = 3 - _kfc_card.cell_contents.controller
            if destroyed_card.controller != opponent_id:
                return (3, None)
            if g.find_play_area(_kfc_card.cell_contents) is None:
                return (3, None)
            _pc = 1 if not g.players[opponent_id].play_area.creatures else 2
            continue
        elif _pc == 1:  # line 549
            _kff = g.destroy_cards
            _kfa = ([_kfc_card.cell_contents],)
            _kfk = None
            F.L = [g, event, destroyed_card, opponent_id, _kfc_card]
            F.pc = 4
            return (1, _kff, _kfa, _kfk)
        elif _pc == 2:  # line 548
            _pc = 3
            continue
        elif _pc == 3:  # line 548
            return (3, None)
        elif _pc == 4:  # line 549
            _pc = 3
            continue

def _kfb_tireless_crocag_register__handler(g, event):
    return [g, event, _kf_U, _kf_U, _kf_U]


def _kfr_wardrummer(F, _sent, _kfN):
    # effects/named/brobnar.py:554 wardrummer
    (game, card, player, t, targets,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 554
            player = controller_of(game, card)
            targets = [c for c in player.play_area.creatures if c is not card and c.house == House.BROBNAR]
            if not targets:
                steps.shortfall(game, card, 'returns nothing: there is no other friendly Brobnar creature in play', 'No other Brobnar creature')
            else:
                for t in targets:
                    steps.return_to_hand(game, t)
            return (3, None)
            _kfd = None
            F.L = [game, card, player, t, targets]
            F.pc = 1
            return (2, _kfd)
        elif _pc == 1:  # line 563
            return (3, None)

def _kfb_wardrummer(game, card):
    return [game, card, _kf_U, _kf_U, _kf_U]


def _kfr__phoenix_heart_effect(F, _sent, _kfN):
    # effects/named/brobnar.py:580 _phoenix_heart_effect
    (game, host_card, t, targets,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 580
            host_card.destined_zone = 'hand'
            targets = [c for c in game.all_creatures('any', host_card) if c is not host_card]
            for t in targets:
                steps.deal_damage(game, t, 3)
            _kff = game.check_destroyed
            _kfa = (targets,)
            _kfk = None
            F.L = [game, host_card, t, targets]
            F.pc = 1
            return (1, _kff, _kfa, _kfk)
        elif _pc == 1:  # line 585
            return (3, None)

def _kfb__phoenix_heart_effect(game, host_card):
    return [game, host_card, _kf_U, _kf_U]


def _kfr_yo_mama_mastery_play(F, _sent, _kfN):
    # effects/named/brobnar.py:588 yo_mama_mastery_play
    (game, card, host,) = F.L
    _pc = F.pc
    while True:
        if _pc == 0:  # line 588
            host = card.type_object.host
            if host is not None:
                steps.fully_heal(game, host)
            return (3, None)
            _kfd = None
            F.L = [game, card, host]
            F.pc = 1
            return (2, _kfd)
        elif _pc == 1:  # line 593
            return (3, None)

def _kfb_yo_mama_mastery_play(game, card):
    return [game, card, _kf_U]


# (qualname, first line, step, binder, slots, freevar slots, nested code (name, line), line of each pc)
ROUTINES = [
    ('anger', 15, _kfr_anger, _kfb_anger, ('game', 'card', 'choice', 'creatures', 'player'), (), (), {0: 15, 1: 21, 2: 25}),
    ('barehanded', 28, _kfr_barehanded, _kfb_barehanded, ('game', 'card', 'a', 'area', 'artifacts', 'order', 'owner'), (), (), {0: 28, 1: 35, 2: 34, 3: 34, 4: 35}),
    ('blood_money', 49, _kfr_blood_money, _kfb_blood_money, ('game', 'card', 'choice', 'opponent', 'options'), (), (), {0: 49, 1: 55}),
    ('brothers_in_battle', 62, _kfr_brothers_in_battle, _kfb_brothers_in_battle, ('game', 'card', 'chosen', 'player'), (), (), {0: 62, 1: 64}),
    ('burn_the_stockpile', 72, _kfr_burn_the_stockpile, _kfb_burn_the_stockpile, ('game', 'card', 'opponent'), (), (), {0: 72, 1: 79}),
    ('champions_challenge', 82, _kfr_champions_challenge, _kfb_champions_challenge, ('game', 'card', 'enemy_creatures', 'friendly_creatures', 'opponent', 'player', 'survivor_enemy', 'survivor_friendly'), (), (), {0: 82, 1: 87, 2: 91, 3: 94, 4: 98, 5: 101, 6: 100, 7: 100, 8: 101}),
    ('cowards_end', 104, _kfr_cowards_end, _kfb_cowards_end, ('game', 'card', 'player', 'targets'), (), (), {0: 104, 1: 107}),
    ('follow_the_leader', 113, _kfr_follow_the_leader, _kfb_follow_the_leader, ('game', 'card', 'player'), (), (), {0: 113, 1: 121}),
    ('_grant_gain_on_enemy_destroyed_this_turn.<locals>.handler', 125, _kfr__grant_gain_on_enemy_destroyed_this_turn__handler, _kfb__grant_gain_on_enemy_destroyed_this_turn__handler, ('g', 'event', '_kfc_card'), ((2, 'card'),), (), {0: 125, 1: 129}),
    ('loot_the_bodies', 134, _kfr_loot_the_bodies, _kfb_loot_the_bodies, ('game', 'card'), (), (), {0: 134, 1: 137}),
    ('take_that_smartypants', 140, _kfr_take_that_smartypants, _kfb_take_that_smartypants, ('game', 'card', 'a', 'c', 'logos_count', 'opponent'), (), (), {0: 140, 1: 155}),
    ('relentless_assault', 158, _kfr_relentless_assault, _kfb_relentless_assault, ('game', 'card', 'available', 'choice', 'cont', 'i', 'player', 'target', 'used', '_kfs0', '_kfi1'), (), (), {0: 158, 1: 161, 2: 162, 3: 161, 4: 164, 5: 163, 6: 163, 7: 166, 8: 165, 9: 165, 10: 166, 11: 171, 12: 170, 13: 170, 14: 172, 15: 178}),
    ('smith', 181, _kfr_smith, _kfb_smith, ('game', 'card', 'opponent', 'player'), (), (), {0: 181, 1: 189}),
    ('sound_the_horns', 192, _kfr_sound_the_horns, _kfb_sound_the_horns, ('game', 'card', 'discarded', 'found', 'player', 'top'), (), (), {0: 192, 1: 213}),
    ('tremor', 216, _kfr_tremor, _kfb_tremor, ('game', 'card', 'area', 'choice', 'n', 'neighbors', 'options', 'target'), (), (), {0: 216, 1: 221}),
    ('unguarded_camp', 233, _kfr_unguarded_camp, _kfb_unguarded_camp, ('game', 'card', 'available', 'choice', 'excess', 'i', 'opponent', 'player', 'target', 'used', '_kfs0', '_kfi1'), (), (), {0: 233, 1: 241, 2: 242, 3: 241, 4: 244, 5: 243, 6: 243, 7: 245}),
    ('warsong', 254, _kfr_warsong, _kfb_warsong, ('game', '_kfc_card', 'handler'), (), (('handler', 255),), {0: 254, 1: 263}),
    ('warsong.<locals>.handler', 255, _kfr_warsong__handler, _kfb_warsong__handler, ('g', 'event', '_kfc_card'), ((2, 'card'),), (), {0: 255, 1: 259}),
    ('autocannon_register.<locals>.handler', 269, _kfr_autocannon_register__handler, _kfb_autocannon_register__handler, ('g', 'event', 'entered'), (), (), {0: 269, 1: 272}),
    ('gauntlet_of_command', 284, _kfr_gauntlet_of_command, _kfb_gauntlet_of_command, ('game', 'card', 'choice', 'creatures', 'player'), (), (), {0: 284, 1: 290, 2: 294}),
    ('mighty_javelin', 309, _kfr_mighty_javelin, _kfb_mighty_javelin, ('game', 'card', 'choice', 'options'), (), (), {0: 309, 1: 310, 2: 315, 3: 320}),
    ('pile_of_skulls_register.<locals>.handler', 324, _kfr_pile_of_skulls_register__handler, _kfb_pile_of_skulls_register__handler, ('g', 'event', 'choice', 'destroyed_card', 'friendly', '_kfc_card'), ((5, 'card'),), (), {0: 324, 1: 333}),
    ('screechbomb', 342, _kfr_screechbomb, _kfb_screechbomb, ('game', 'card'), (), (), {0: 342, 1: 343}),
    ('the_warchest', 347, _kfr_the_warchest, _kfb_the_warchest, ('game', 'card', 'n', 'opponent'), (), (), {0: 347, 1: 353}),
    ('bilgum_avalanche_register.<locals>.handler', 359, _kfr_bilgum_avalanche_register__handler, _kfb_bilgum_avalanche_register__handler, ('g', 'event', 't', 'targets', '_kfc_card'), ((4, 'card'),), (), {0: 359, 1: 365}),
    ('earthshaker', 382, _kfr_earthshaker, _kfb_earthshaker, ('game', 'card', 'targets'), (), (), {0: 382, 1: 387}),
    ('firespitter_before_fight', 390, _kfr_firespitter_before_fight, _kfb_firespitter_before_fight, ('game', 'card', 'target', 't', 'targets'), (), (), {0: 390, 1: 395}),
    ('ganger_chieftain_play', 398, _kfr_ganger_chieftain_play, _kfb_ganger_chieftain_play, ('game', 'card', 'area', 'choice', 'do_it', 'neighbors', 'player'), (), (), {0: 398, 1: 404, 2: 410, 3: 414}),
    ('hebe_the_huge', 417, _kfr_hebe_the_huge, _kfb_hebe_the_huge, ('game', 'card', 't', 'targets'), (), (), {0: 417, 1: 424}),
    ('kelifi_dragon_after', 427, _kfr_kelifi_dragon_after, _kfb_kelifi_dragon_after, ('game', 'card', 'choice', 'options'), (), (), {0: 427, 1: 433, 2: 438}),
    ('krump_on_destroyed_fighting', 450, _kfr_krump_on_destroyed_fighting, _kfb_krump_on_destroyed_fighting, ('game', 'survivor', 'victim'), (), (), {0: 450, 1: 453}),
    ('lomir_flamefist', 456, _kfr_lomir_flamefist, _kfb_lomir_flamefist, ('game', 'card', 'opponent'), (), (), {0: 456, 1: 463}),
    ('mugwump_on_destroyed_fighting', 466, _kfr_mugwump_on_destroyed_fighting, _kfb_mugwump_on_destroyed_fighting, ('game', 'survivor', 'victim'), (), (), {0: 466, 1: 470}),
    ('pingle_who_annoys_register.<locals>.handler', 474, _kfr_pingle_who_annoys_register__handler, _kfb_pingle_who_annoys_register__handler, ('g', 'event', 'entered', '_kfc_card'), ((3, 'card'),), (), {0: 474, 1: 477, 2: 476, 3: 476, 4: 478}),
    ('rock_hurling_giant_register.<locals>.handler', 484, _kfr_rock_hurling_giant_register__handler, _kfb_rock_hurling_giant_register__handler, ('g', 'event', 'choice', 'discarded', 'do_it', 'options', '_kfc_card'), ((6, 'card'),), (), {0: 484, 1: 493, 2: 499, 3: 504}),
    ('rogue_ogre_register.<locals>.handler', 510, _kfr_rogue_ogre_register__handler, _kfb_rogue_ogre_register__handler, ('g', 'event', 'player', '_kfc_card'), ((3, 'card'),), (), {0: 510, 1: 517}),
    ('smaaash', 522, _kfr_smaaash, _kfb_smaaash, ('game', 'card', 'choice', 'options'), (), (), {0: 522, 1: 527}),
    ('tireless_crocag_play', 534, _kfr_tireless_crocag_play, _kfb_tireless_crocag_play, ('game', 'card', 'opponent'), (), (), {0: 534, 1: 537, 2: 536, 3: 536, 4: 537}),
    ('tireless_crocag_register.<locals>.handler', 541, _kfr_tireless_crocag_register__handler, _kfb_tireless_crocag_register__handler, ('g', 'event', 'destroyed_card', 'opponent_id', '_kfc_card'), ((4, 'card'),), (), {0: 541, 1: 549, 2: 548, 3: 548, 4: 549}),
    ('wardrummer', 554, _kfr_wardrummer, _kfb_wardrummer, ('game', 'card', 'player', 't', 'targets'), (), (), {0: 554, 1: 563}),
    ('_phoenix_heart_effect', 580, _kfr__phoenix_heart_effect, _kfb__phoenix_heart_effect, ('game', 'host_card', 't', 'targets'), (), (), {0: 580, 1: 585}),
    ('yo_mama_mastery_play', 588, _kfr_yo_mama_mastery_play, _kfb_yo_mama_mastery_play, ('game', 'card', 'host'), (), (), {0: 588, 1: 593}),
]
