"""Generated by tools/compile_engine.py from keyforge/match.py -- do not edit.

Each pausing function of the source, as a routine for keyforge/vm.py's Machine:
`_kfmk_*` makes a routine: called with the original arguments it runs a fresh call;
called as `routine(_kfF=frame, _sent=sent)` it resumes a frame.
"""

# fmt: off
# flake8: noqa
SOURCE = 'keyforge/match.py'
SOURCE_SHA256 = '984d97dae3e3af8bbe04634932481b5a700861ad25b65672a735cb0212afdd6f'

# Placeholder defaults: the loader rebuilds every function here in the source module's globals,
# with the original function's own defaults.
_kf_U = None


def _kfmk_Match__run(_kfN, _kfR):
  def _kfr_Match__run(self=_kf_U, *, _kfF=None, _sent=None, _kf_closure=None):
    # match.py:191 Match._run
    if _kfF is None:  # a fresh call: Python bound the arguments
        g = seat_decks = _kf_U
        _pc = 0
    else:  # resuming a suspended frame
        (self, g, seat_decks,) = _kfF.L
        _pc = _kfF.pc
    if (not _pc and (self.format in ('archon', 'reversal'))) or _pc == 1:
        if not _pc:
            seat_decks = self.decks if self.format == 'archon' else (self.decks[1], self.decks[0])
        if not _pc:
            _sent = _kf_step(self._play_game)(decks=seat_decks, first_player=self.config.first_player)
            if type(_sent) is _kf_S:
                if _kfF is None:
                    _kfF = _kf_Frame(_kfR, [self, g, seat_decks])
                    _kfF.pc = 1
                    _sent.frames.append(_kfF)
                else:
                    _kfF.L = [self, g, seat_decks]
                    _kfF.pc = 1
                return _sent
        elif _pc == 1:
            _pc = 0
        g = self.games[-1]
        self.result = {'winner': g.winner, 'games': [g.winner], 'format': self.format, 'bid': None, 'reason': None if g.winner is not None else 'game did not conclude'}
        return
    if not _pc:
        _sent = _kf_step(self._run_adaptive)()
        if type(_sent) is _kf_S:
            if _kfF is None:
                _kfF = _kf_Frame(_kfR, [self, g, seat_decks])
                _kfF.pc = 2
                _sent.frames.append(_kfF)
            else:
                _kfF.L = [self, g, seat_decks]
                _kfF.pc = 2
            return _sent
    elif _pc == 2:
        _pc = 0
    return None
  return _kfr_Match__run


def _kfmk_Match__run_adaptive(_kfN, _kfR):
  def _kfr_Match__run_adaptive(self=_kf_U, *, _kfF=None, _sent=None, _kf_closure=None):
    # match.py:203 Match._run_adaptive
    if _kfF is None:  # a fresh call: Python bound the arguments
        amount = bid_deck = bid_owner = g1 = g2 = g3 = loser_pid = next_first = other_deck = seat_decks = starting_chains = winner_pid = _kf_U
        _pc = 0
    else:  # resuming a suspended frame
        (self, amount, bid_deck, bid_owner, g1, g2, g3, loser_pid, next_first, other_deck, seat_decks, starting_chains, winner_pid,) = _kfF.L
        _pc = _kfF.pc
    if not _pc:
        _sent = _kf_step(self._play_game)(decks=self.decks, first_player=self.config.first_player)
        if type(_sent) is _kf_S:
            if _kfF is None:
                _kfF = _kf_Frame(_kfR, [self, amount, bid_deck, bid_owner, g1, g2, g3, loser_pid, next_first, other_deck, seat_decks, starting_chains, winner_pid])
                _kfF.pc = 1
                _sent.frames.append(_kfF)
            else:
                _kfF.L = [self, amount, bid_deck, bid_owner, g1, g2, g3, loser_pid, next_first, other_deck, seat_decks, starting_chains, winner_pid]
                _kfF.pc = 1
            return _sent
    elif _pc == 1:
        _pc = 0
    if not _pc:
        g1 = self.games[-1]
        if g1.winner is None:
            self.result = {'winner': None, 'reason': 'game 1 did not conclude', 'games': [None], 'format': self.format}
            return
    if not _pc:
        _sent = _kf_step(self._choose_first_player)(3 - g1.winner)
        if type(_sent) is _kf_S:
            if _kfF is None:
                _kfF = _kf_Frame(_kfR, [self, amount, bid_deck, bid_owner, g1, g2, g3, loser_pid, next_first, other_deck, seat_decks, starting_chains, winner_pid])
                _kfF.pc = 2
                _sent.frames.append(_kfF)
            else:
                _kfF.L = [self, amount, bid_deck, bid_owner, g1, g2, g3, loser_pid, next_first, other_deck, seat_decks, starting_chains, winner_pid]
                _kfF.pc = 2
            return _sent
        next_first = _sent
    elif _pc == 2:
        _pc = 0
        next_first = _sent
    if not _pc:
        _sent = _kf_step(self._play_game)(decks=(self.decks[1], self.decks[0]), first_player=next_first)
        if type(_sent) is _kf_S:
            if _kfF is None:
                _kfF = _kf_Frame(_kfR, [self, amount, bid_deck, bid_owner, g1, g2, g3, loser_pid, next_first, other_deck, seat_decks, starting_chains, winner_pid])
                _kfF.pc = 3
                _sent.frames.append(_kfF)
            else:
                _kfF.L = [self, amount, bid_deck, bid_owner, g1, g2, g3, loser_pid, next_first, other_deck, seat_decks, starting_chains, winner_pid]
                _kfF.pc = 3
            return _sent
    elif _pc == 3:
        _pc = 0
    if not _pc:
        g2 = self.games[-1]
        if g2.winner is None:
            self.result = {'winner': None, 'reason': 'game 2 did not conclude', 'games': [g1.winner, None], 'format': self.format}
            return
        if g1.winner == g2.winner:
            self.result = {'winner': g1.winner, 'games': [g1.winner, g2.winner], 'format': self.format, 'bid': None, 'reason': None}
            return
        bid_deck = g1.seat_decks[g1.winner]
        bid_owner = 1 if deck_label(bid_deck) == deck_label(self.decks[0]) else 2
        other_deck = self.decks[1] if bid_owner == 1 else self.decks[0]
        self.bidding_deck = bid_deck
    if not _pc:
        _sent = _kf_step(self._run_bid)(bid_owner)
        if type(_sent) is _kf_S:
            if _kfF is None:
                _kfF = _kf_Frame(_kfR, [self, amount, bid_deck, bid_owner, g1, g2, g3, loser_pid, next_first, other_deck, seat_decks, starting_chains, winner_pid])
                _kfF.pc = 4
                _sent.frames.append(_kfF)
            else:
                _kfF.L = [self, amount, bid_deck, bid_owner, g1, g2, g3, loser_pid, next_first, other_deck, seat_decks, starting_chains, winner_pid]
                _kfF.pc = 4
            return _sent
        winner_pid, amount = _sent
    elif _pc == 4:
        _pc = 0
        winner_pid, amount = _sent
    if not _pc:
        self.bidding_deck = None
        self.bid = BidRecord(owner=bid_owner, winner=winner_pid, amount=amount, deck=deck_label(bid_deck))
        loser_pid = 3 - winner_pid
        seat_decks = {winner_pid: bid_deck, loser_pid: other_deck}
        starting_chains = {winner_pid: amount, loser_pid: 0}
    if not _pc:
        _sent = _kf_step(self._choose_first_player)(3 - g2.winner)
        if type(_sent) is _kf_S:
            if _kfF is None:
                _kfF = _kf_Frame(_kfR, [self, amount, bid_deck, bid_owner, g1, g2, g3, loser_pid, next_first, other_deck, seat_decks, starting_chains, winner_pid])
                _kfF.pc = 5
                _sent.frames.append(_kfF)
            else:
                _kfF.L = [self, amount, bid_deck, bid_owner, g1, g2, g3, loser_pid, next_first, other_deck, seat_decks, starting_chains, winner_pid]
                _kfF.pc = 5
            return _sent
        next_first = _sent
    elif _pc == 5:
        _pc = 0
        next_first = _sent
    if not _pc:
        _sent = _kf_step(self._play_game)(decks=(seat_decks[1], seat_decks[2]), first_player=next_first, starting_chains=starting_chains)
        if type(_sent) is _kf_S:
            if _kfF is None:
                _kfF = _kf_Frame(_kfR, [self, amount, bid_deck, bid_owner, g1, g2, g3, loser_pid, next_first, other_deck, seat_decks, starting_chains, winner_pid])
                _kfF.pc = 6
                _sent.frames.append(_kfF)
            else:
                _kfF.L = [self, amount, bid_deck, bid_owner, g1, g2, g3, loser_pid, next_first, other_deck, seat_decks, starting_chains, winner_pid]
                _kfF.pc = 6
            return _sent
    elif _pc == 6:
        _pc = 0
    g3 = self.games[-1]
    self.result = {'winner': g3.winner, 'games': [g1.winner, g2.winner, g3.winner], 'format': self.format, 'bid': self.bid, 'reason': None if g3.winner is not None else 'game 3 did not conclude'}
    return None
  return _kfr_Match__run_adaptive


def _kfmk_Match__play_game(_kfN, _kfR):
  def _kfr_Match__play_game(self=_kf_U, decks=_kf_U, first_player=_kf_U, starting_chains=_kf_U, *, _kfF=None, _sent=None, _kf_closure=None):
    # match.py:254 Match._play_game
    if _kfF is None:  # a fresh call: Python bound the arguments
        choice = game = game_config = record = result = _kf_U
        _pc = 0
    else:  # resuming a suspended frame
        (self, decks, first_player, starting_chains, choice, game, game_config, record, result,) = _kfF.L
        _pc = _kfF.pc
    if not _pc:
        game_config = GameConfig(decks=decks, first_player=first_player, seed=self._next_game_seed(), max_turns=self.config.max_turns, starting_chains=starting_chains)
        game = Game(game_config, execution=self.execution)
        self.current_game = game
    while (not _pc and (not game.is_over)) or _pc == 1:
        if not _pc:
            _kfd = _kf_S(game.pending_decision)
            if _kfF is None:
                _kfF = _kf_Frame(_kfR, [self, decks, first_player, starting_chains, choice, game, game_config, record, result])
                _kfF.pc = 1
                _kfd.frames.append(_kfF)
            else:
                _kfF.L = [self, decks, first_player, starting_chains, choice, game, game_config, record, result]
                _kfF.pc = 1
            return _kfd
        elif _pc == 1:
            _pc = 0
            choice = _sent
        game.submit(choice)
    result = game.result or {}
    record = GameRecord(config=game_config, winner=result.get('winner'), turns=game.turn_number, reason=result.get('reason', ''), seat_decks={1: decks[0], 2: decks[1]}, final_chains={pid: p.chains for pid, p in game.players.items()}, final_keys={pid: p.keys for pid, p in game.players.items()})
    self.games.append(record)
    self.finished_games.append(game)
    self._score_game(record)
    return None
  return _kfr_Match__play_game


def _kfmk_Match__choose_first_player(_kfN, _kfR):
  def _kfr_Match__choose_first_player(self=_kf_U, pid=_kf_U, *, _kfF=None, _sent=None, _kf_closure=None):
    # match.py:281 Match._choose_first_player
    if _kfF is None:  # a fresh call: Python bound the arguments
        choice = _kf_U
        _pc = 0
    else:  # resuming a suspended frame
        (self, pid, choice,) = _kfF.L
        _pc = _kfF.pc
    if not _pc:
        _kfd = _kf_S(Decision(pid, DecisionKind.CHOOSE_FIRST_PLAYER, 'You lost the last game: choose whether to go first or second next game', ['first', 'second'], 1, 1))
        if _kfF is None:
            _kfF = _kf_Frame(_kfR, [self, pid, choice])
            _kfF.pc = 1
            _kfd.frames.append(_kfF)
        else:
            _kfF.L = [self, pid, choice]
            _kfF.pc = 1
        return _kfd
    elif _pc == 1:
        _pc = 0
        choice = _sent
    return pid if choice == 'first' else 3 - pid
    return None
  return _kfr_Match__choose_first_player


def _kfmk_Match__run_bid(_kfN, _kfR):
  def _kfr_Match__run_bid(self=_kf_U, owner_pid=_kf_U, *, _kfF=None, _sent=None, _kf_closure=None):
    # match.py:289 Match._run_bid
    if _kfF is None:  # a fresh call: Python bound the arguments
        choice = current_bid = current_bidder = opponent_pid = options = prompt = standing = turn = winner_pid = _kf_U
        _pc = 0
    else:  # resuming a suspended frame
        (self, owner_pid, choice, current_bid, current_bidder, opponent_pid, options, prompt, standing, turn, winner_pid,) = _kfF.L
        _pc = _kfF.pc
    if not _pc:
        opponent_pid = 3 - owner_pid
        current_bid = 0
        current_bidder: Optional[int] = None
        turn = opponent_pid
    while (not _pc and (True)) or _pc == 1:
        if not _pc:
            options = ['pass'] + list(range(current_bid + 1, MAX_BID + 1))
            if current_bidder is None:
                standing = 'unclaimed at 0'
            elif current_bidder == turn:
                standing = f'{current_bid} chains, by you'
            else:
                standing = f'{current_bid} chains, by your opponent'
            prompt = f'Bid chains to pilot {deck_label(self.bidding_deck)} (won both games). Current bid: {standing}.'
        if not _pc:
            _kfd = _kf_S(Decision(turn, DecisionKind.BID_CHAINS, prompt, options, 1, 1))
            if _kfF is None:
                _kfF = _kf_Frame(_kfR, [self, owner_pid, choice, current_bid, current_bidder, opponent_pid, options, prompt, standing, turn, winner_pid])
                _kfF.pc = 1
                _kfd.frames.append(_kfF)
            else:
                _kfF.L = [self, owner_pid, choice, current_bid, current_bidder, opponent_pid, options, prompt, standing, turn, winner_pid]
                _kfF.pc = 1
            return _kfd
        elif _pc == 1:
            _pc = 0
            choice = _sent
        if choice == 'pass':
            winner_pid = current_bidder if current_bidder is not None else owner_pid
            return (winner_pid, current_bid)
        current_bid = choice
        current_bidder = turn
        if current_bid >= MAX_BID:
            return (current_bidder, current_bid)
        turn = 3 - turn
    return None
  return _kfr_Match__run_bid


# (qualname, first line, routine factory, slots, free variables, nested code (name, line),
#  line of each resume id, (exception slot, resume ids inside a try region) or None)
ROUTINES = [
    ('Match._run', 191, _kfmk_Match__run, ('self', 'g', 'seat_decks'), (), (), {1: 194, 2: 201}, None),
    ('Match._run_adaptive', 203, _kfmk_Match__run_adaptive, ('self', 'amount', 'bid_deck', 'bid_owner', 'g1', 'g2', 'g3', 'loser_pid', 'next_first', 'other_deck', 'seat_decks', 'starting_chains', 'winner_pid'), (), (), {1: 204, 2: 210, 3: 211, 4: 234, 5: 241, 6: 242}, None),
    ('Match._play_game', 254, _kfmk_Match__play_game, ('self', 'decks', 'first_player', 'starting_chains', 'choice', 'game', 'game_config', 'record', 'result'), (), (), {1: 265}, None),
    ('Match._choose_first_player', 281, _kfmk_Match__choose_first_player, ('self', 'pid', 'choice'), (), (), {1: 282}, None),
    ('Match._run_bid', 289, _kfmk_Match__run_bid, ('self', 'owner_pid', 'choice', 'current_bid', 'current_bidder', 'opponent_pid', 'options', 'prompt', 'standing', 'turn', 'winner_pid'), (), (), {1: 307}, None),
]
